### PR TITLE
Replace @pichuang with @tico88612 as zh-tw branch approver

### PR DESCRIPTION
**Pull request by pichuang**
### Describe your changes

Suggest that @pichuang 's own permissions be transferred to @tico88612 , who can contribute more to the glossary project

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by pichuang** [comment]
Based on the past record of actual contribution to zh-tw, @tico88612 is recommended to be the reviewer of the project, in the hope that the project can move forward more continuously.

**Review by nate-double-u — APPROVED** [review]
Thanks for all your work @pichuang, and welcome to the team @tico88612!

**Comment by iamNoah1** [comment]
Thanks @pichuang and welcome @tico88612

**Review by iamNoah1 — APPROVED** [review]

**Comment by tico88612** [comment]
Hi @nate-double-u @iamNoah1 
I still can not assign an issue or edit the PR. Could you help me? Thanks.

image

**Comment by seokho-son** [comment]
- We need to update config.yaml in https://github.com/cncf/people
- The approver (@tico88612) needs to confirm 
  - #723

**Pull request merged**
