### PR TITLE
[bn] Update dev-bn branch with main 

### PR DESCRIPTION
**Pull request by asem-hamid**
### Describe your changes

Update dev-bn branch with main 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by iamNoah1** [comment]
can we have a second approve here @seokho-son, @jihoon-seo @nate-double-u ?!

**Review by nate-double-u — APPROVED** [review]
lgtm

**Comment by nate-double-u** [comment]
Even with @ iamNoah1 and my approval, you'll also need approvals from the Bengali Codeowners:
https://github.com/cncf/glossary/blob/eb80a9906f0dc693e17b2f801da77dd79d67a632/CODEOWNERS#L25-L27

**Review by mitul3737 — APPROVED** [review]
/lgtm

**Review by Imtiaz1234 — APPROVED** [review]
/LGTM

**Comment by nate-double-u** [comment]
Interesting, it still says merging is blocked. I can merge it "without waiting for the req's to be met," but I'm curious why it thinks it's not allowing it automatically now. The system may want more locale codeowner approvals because it's hitting more than just the `bn` directory, but that check shouldn't happen on a dev branch.

**Comment by asem-hamid** [comment]
Thanks for merging @nate-double-u

**Comment by nate-double-u** [comment]
I `squashed` this PR when I probably shouldn't have. @asem-hamid, I've pinged the maintainers channel for their opinion of what the best next step is, but I think that I should pull the `dev-bn` branch, remove the commit that this squash created, then force push back to `dev-bn`. I think that'll bring the branch back in line with where it was, but then we'll need to redo this PR. Sorry about this.

@iamNoah1 @seokho-son

**Comment by asem-hamid** [comment]
@nate-double-u  oh no sweat , Please instruct me what I have to do from my end

**Comment by seokho-son** [comment]
> Interesting, it still says merging is blocked. I can merge it "without waiting for the req's to be met," but I'm curious why it thinks it's not allowing it automatically now. The system may want more locale codeowner approvals because it's hitting more than just the `bn` directory, but that check shouldn't happen on a dev branch.


Hi @nate-double-u 

Thanks for facilitating the PRs to sync the branches. 
Since I’ve mostly handled this work on my own as one of the maintainers, I imagine there might have been some parts that seemed confusing to you. :)

1. PR for Updating the dev-xx Branch (main -> dev-bn)
Currently, the approvers are organized differently for each language (except for English). For example, bn content (/bn/*) is approved by bn content owners. So, when trying to merge the commits from main into dev-bn, many files in other languages are also added to dev-bn due to the various commits added to main over time. As a result, the code owners of languages other than bn need to approve the PR for it to pass the CI checks.
However, these branch update PRs don’t actually require content reviews, so to prevent unnecessary stress for many reviewers, it has been agreed that the maintainer can force merge these without needing approval from each content reviewer. (I’ve primarily handled this)
When merging these PRs, we avoid squashing the commits to retain the commit history, as they are unique commits in the main branch.

2. PR for Merging Localization Work from dev-xx to main (dev-bn -> main)
Modifications in the dev-bn branch only involve Bengali content. The Bengali approvers can only approve content within the /bn/* directory in any branch, including dev-bn.
Therefore, for a PR that merges dev-bn into main, the approval of the Bengali approver is required, followed by an additional review from one of the maintainers before merging into main. (Occasionally, maintainers may make changes to other languages in the dev-bn branch as well.)
If there are an excessive number of commits relative to the number of files modified, we consider that the commit history has not been well managed, and we perform a commit squashing before merging. If the commits are appropriate, then we simply merge as is.

3. Overall...
As you know, the related policies can be found in [this discussion](https://github.com/cncf/glossary/discussions/723). Before a new reviewer/approver joins, we go through a process to ensure they understand these policies well.

**Comment by nate-double-u** [comment]
OK, I'm going to drop the commit made in this PR (afb068f92db6c533fabe95985afd6bded4208f1d) locally, then force-push. This should reset `dev-bn` to where it was before I merged this. I think this'll be cleaner than doing a revert commit.

I'll have to take branch protections off temporarily while i do this, I'll let you know when it's done.

Unfortunately, we'll need to redo this PR. I'll update this thread when I've completed the update.

**Comment by nate-double-u** [comment]
I've removed the commit that this PR made.

**Pull request merged**
