### PR TITLE
Add Hindi approvers in CODEOWNERS

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
A task based on the issue #297 (Initiate Hindi Localization Team)

### CODE REVIEW

**Comment by anubha-v-ardhan** [comment]
We also need to add a block for Hindi in config.toml

**Review by CathPag — APPROVED** [review]
LGTM

**Comment by CathPag** [comment]
As @seokho-son mentioned on Slack, we are still testing the process with the Korean team, so we'll hold on merging this until that is the process is confirmed as working well.

**Comment by anubha-v-ardhan** [comment]
@jayesh-srivastava I believe we can close this PR as this change is being done by #342 for all localizations

**Review by anubha-v-ardhan — CHANGES_REQUESTED** [review]
@jayesh-srivastava I believe you can close this PR as this change is being done by #342 for all localizations

**Comment by seokho-son** [comment]
Let me close this PR :) 
codeowners will be handled by #342

**Pull request closed without merging**
