### PR TITLE
New Hugo Site

### PR DESCRIPTION
**Pull request by cjyabraham**

### CODE REVIEW

**Review by CathPag — APPROVED** [review]
LGTM

**Review by JasonMorgan — APPROVED** [review]
LGTM

**Comment by caniszczyk** [comment]
@cjyabraham have a bunch of conflicts to resolve

**Comment by cjyabraham** [comment]
Conflicts are resolved.

**Review by CathPag — APPROVED** [review]
LGTM

**Comment by cjyabraham** [comment]
Here is the netlify preview: https://deploy-preview-229--cncfglossary.netlify.app/

**Pull request merged**
