### PR TITLE
Localized content/hi/zero-trust-architecture.md

### PR DESCRIPTION
**Pull request by shivam-sharma7**
### Describe your changes
- Localized `content/hi/zero-trust-architecture.md` to Hindi.

- Trcking issue: #1354

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @Garima-Negi @anubha-v-ardhan

**Comment by shivam-sharma7** [comment]
please review/ @anubha-v-ardhan

**Comment by shivam-sharma7** [comment]
review/ @Garima-Negi @anubha-v-ardhan

**Comment by Garima-Negi** [comment]
Hi @shivam-sharma7  thank you for your PR.
I shall be reviewing in more depth tomorrow. Meanwhile can you fix the alignment of sentences? They need to be in a paragraph and not new sentence on new line. Thanx!

**Comment by jihoon-seo** [comment]
This PR is a duplicate; please see https://github.com/cncf/glossary/pull/1249#issuecomment-1409749859.

**Comment by sayantani11** [comment]
Hey @shivam-sharma7 as you can see that this particular topic is addressed in another PR, it will be great if you can try to take a different topic. Thanks for the PR tho!

**Pull request closed without merging**
