### PR TITLE
Add issue template for new l10n initiation

### PR DESCRIPTION
**Pull request by seokho-son**
This issue template includes 

- Information for language and language code for l10n
- List of volunteers
- Next actions from maintainers

### CODE REVIEW

**Comment by seokho-son** [comment]
image

**Comment by seokho-son** [comment]
Ref: https://cloud-native.slack.com/archives/C02N2RGFXDF/p1639186123048200

I was requested to update 
- https://github.com/cncf/glossary/blob/main/LOCALIZATION.md

to to describe how to request
- a new localization development branch
- ownership to l10n approvers for l10n directories

I'd like to utilize issue template for this guide.

After this PR has been merged, I am going to update https://github.com/cncf/glossary/blob/main/LOCALIZATION.md to make new l10n volunteers use this issue template.

PTAL: @CathPag @JasonMorgan :)

**Comment by seokho-son** [comment]
PTAL PR #279 after this PR is merged.

**Review by JasonMorgan — APPROVED** [review]

**Review by CathPag — APPROVED** [review]
LGTM

**Pull request merged**
