### PR TITLE
Replace developer-guy with rwxdash as TR approver

### PR DESCRIPTION
**Pull request by developer-guy**
### Describe your changes

I'm stepping down from my role in the Turkish glossary team since I was not an active member of the community so I believe @rwxdash will be more active than I'm. 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by aliok** [comment]
Thanks @developer-guy for all the work you've done and we appreciate that you're stepping down to make other folks in the group recognized.

We've already talked this in the group, but for double check: cc @halil-bugol @eminalemdar @rwxdash 

cc @seokho-son

**Comment by seokho-son** [comment]
Thank you, @developer-guy, for your contributions so far! (Feel free to come back whenever you're available!)

Hello @rwxdash, I'd like to confirm if you are willing to accept this nomination.

If you agree, please review and confirm the following policies:
[Policies for Localization Approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)

Once you have reviewed them, kindly leave a comment on this PR to indicate your confirmation.

**Comment by rwxdash** [comment]
Hey @seokho-son. 

I have read and understood the policies. Happy to take over @developer-guy's responsibilities. Thank you, again, for your contributions!

**Review by nate-double-u — APPROVED** [review]
Thanks for all your work @developer-guy, and welcome @rwxdash, thanks for volunteering to help!

**Comment by seokho-son** [comment]
Thanks! I am going to create another PR to cncf/people to apply this change. (after that I am going to merge this PR)

**Review by seokho-son — APPROVED** [review]

**Comment by seokho-son** [comment]
ref https://github.com/cncf/people/pull/325

**Pull request merged**
