### PR TITLE
[en] More interlinking for containerisation & virtualisation

### PR DESCRIPTION
**Pull request by shurup**
### Describe your changes
Since the style guide encourages links to existing glossary terms, I think all these interlinks in containerisation, virtualisation, and CI/CD are helpful.

It also brings a bit more consistency. E.g., for now, the Continuous Deployment text links to Continuous Delivery and  Continuous Integration, but the Continuous Delivery text doesn't do it.

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by nate-double-u — CHANGES_REQUESTED** [review]
Hi, thanks for this.

We only rarely use the _Related Terms_ heading, preferring to stick with our regular template. If there are related terms, it's best to link them in the text where possible.

**Comment by shurup** [comment]
Thanks @nate-double-u, removed all my "Related Terms" blocks.

**Review by seokho-son — APPROVED** [review]
LGTM! Thanks!

**Comment by asem-hamid** [comment]
@asem-hamid do it for bn

**Review by kumarankit999 — APPROVED** [review]
/lgtm

**Review by iamNoah1 — APPROVED** [review]
lgtm

**Pull request merged**
