### PR TITLE
Settings and initial contents for Korean localization

### PR DESCRIPTION
**Pull request by seokho-son**
This PR is to initiate Korean localization based on   
 - Issue to #288
 - https://github.com/cncf/glossary/blob/main/LOCALIZATION.md guide

Base and target branch of this PR is `dev-ko` which is development branch for Korean localization.

This PR includes
 - `[languages.ko]` section in `config.toml`
 - content/**ko**/ directory
 - i18n/ko.toml
 - Some  translated documents
   - Main page
     - content/ko/_index.md
   - Terms 
      - "Cloud Native Technology": content/ko/cloud_native_tech.md
   - Others
     - contribute: content/ko/contribute/_index.md (partially localized)
     - style-guide: content/ko/style-guide/_index.md (partially localized)

Since Korean localization team owns `content/ko/*` only, 
this PR will require approvals from upstream owners (maintainers).

### CODE REVIEW

**Comment by seokho-son** [comment]
image

**Comment by seokho-son** [comment]
I hope to note that there is no Netlify preview for this branch (`dev-ko`) yet.

**Comment by CathPag** [comment]
@seokho-son, just to clarify, this is to create the Korean branch and that's why you need one of us to approve as well, correct?

**Comment by seokho-son** [comment]
@CathPag 

> this is to create the Korean branch .. ?

I created Korean branch https://github.com/cncf/glossary/tree/dev-ko already. This PR is not about creating a new branch but is to config Korean language to enable Korean option to the glossary website. The configuration will be effective only in `dev-ko`.

I assume this kind of PR is the first PR that each localization team open firstly.

> that's why you need one of us to approve as well, correct?

Each localization team needs to modify [config.toml]( https://github.com/cncf/glossary/blob/main/config.toml) for a new language configuration according to https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#add-a-new-language-setting-to-site-configuration

Even though the target branch of this PR is `dev-ko`, config.toml needs to be properly modified since config.toml will be merged to `main` branch eventually.
So, maintainers would better to check config.toml is configured properly to help localization teams. :) 

[FYI] I added Korean approvers for files in `/contents/ko/` to CODEOWNERS. https://github.com/cncf/glossary/blob/dev-ko/CODEOWNERS#L11
But it seems not work yet since permission setting for `dev-ko` branch is not appropriate yet.
(I guess PR #293 will resolve this problem)

**Comment by CathPag** [comment]
Ok, since you would like a maintainer to review for correctness, let's wait for Jason to come back next week as I can only really review and approve content, not setups.

**Review by JasonMorgan — APPROVED** [review]
Seems good but obviously I don't understand Korean. I'm not sure why the _index.md files are in English but I'm happy to trust your judgement.

**Comment by seokho-son** [comment]
@JasonMorgan Thanks :) 
I just wanted to show basic files that need to be included in a new language configuration to maintainers and new l10n teams. obviously not for requesting Korean review ;)

In case of content/ko/_index.md, the contents in the file is Korean.
File name should be same with the file in English directory (content/en/_index.md).
Then Hugo understands it is a localized document.

**Pull request merged**
