### PR TITLE
 Created definition for serverless

### PR DESCRIPTION
**Pull request by sandipanpanda**
Added the definition of serverless in [definitions](https://github.com/cncf/glossary/tree/main/definitions) directory. This pull request closes issue #176.

### CODE REVIEW

**Comment by CathPag** [comment]
Thank you for your contribution @sandipanpanda! A lot of our maintainers are on vacation and, as you can see in the PRs, we have a backlog. Please give us a little time to review.

**Review by JasonMorgan — APPROVED** [review]

**Review by CathPag — APPROVED** [review]
LGTM

**Comment by sandipanpanda** [comment]
Thank you @CathPag @JasonMorgan for approving.

**Comment by sandipanpanda** [comment]
I found that in [_TEMPLATE.md](_TEMPLATE.md) and other  definitions under the [definitions](https://github.com/cncf/glossary/tree/main/definitions) directory, under **Category:** _technology / property / concept_ is in lower case. For e.g. https://github.com/cncf/glossary/blob/main/definitions/virtualization.md. I followed the template accordingly. Should their first letter be in uppercase as it was changed in this PR. If so, I can open a pull request and make the changes accordingly for all of the definitions at once.

**Comment by JasonMorgan** [comment]
Re ran checks after updating our spell checker.

**Comment by CIPHERTron** [comment]
Hmm, strange. If we see the spellcheck action logs, it's stating that `serverless`, `Serverless` & `IaaS` are misspelled but all the three words are present in wordlist.txt. So, it should ignore those but instead, the check is failing.

**Comment by JasonMorgan** [comment]
@sandipanpanda can you pull the latest changes from main into your branch? It should pass the checks after that.

**Comment by sandipanpanda** [comment]
> @sandipanpanda can you pull the latest changes from main into your branch? It should pass the checks after that.

Done! @JasonMorgan :+1:

**Comment by sandipanpanda** [comment]
@CathPag @JasonMorgan Are there any suggestions for improvements to this definition? Is it safe to change the status of this definition to completed?

**Comment by CathPag** [comment]
Oops, I guess we forgot to update the status. Yes, this is ready to go. Feel free to update the status...and pick a new term if you want :)

**Pull request merged**
