### PR TITLE
Sync branch dev-tw from main(20231011)

### PR DESCRIPTION
**Pull request by ydFu**
### Describe your changes
Initial merging the dev-tw branch into main branch
Task: Update dev-tw based on the latest main.

### Related issue number or link (ex: `resolves #issue-number`)
#2355

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by ydFu** [comment]
@seokho-son @jihoon-seo 
This PR pertains to branch synchronization information. I kindly request your assistance in reviewing this PR, as my next milestone involves merging Traditional Chinese into the main branch and presenting it on the website.

**Review by jihoon-seo — APPROVED** [review]
@ydFu Thank you for what you've been doing for this project!
I am leaving one approval of mine, and below is additional comment:
This PR seems to be not a merge blocker (or in other words, a conflict resolver) of [merging `dev-tw` into `main`](https://github.com/cncf/glossary/compare/main...dev-tw).
I think that we don't have to update the local branch frequently for small number of new commits (for the case of this PR, it is 1), provided that those commits are not crucial, urgent, or required.. 😅
(And of course, telling whether commits are crucial, urgent, or required might be subjective by person to person..)

**Comment by ydFu** [comment]
> @ydFu Thank you for what you've been doing for this project! I am leaving one approval of mine, and below is additional comment: This PR seems to be not a merge blocker (or in other words, a conflict resolver) of [merging `dev-tw` into `main`](https://github.com/cncf/glossary/compare/main...dev-tw). I think that we don't have to update the local branch frequently for small number of new commits (for the case of this PR, it is 1), provided that those commits are not crucial, urgent, or required.. 😅 (And of course, telling whether commits are crucial, urgent, or required might be subjective by person to person..)

Thank you for your review and reminder. I will try my best not to synchronize main to dev-tw with only one commit next time.

The main reason for this change is that when dev-tw was first merged into the main branch, *a necessary sub-task* was to update dev-tw to the latest main, so this change was proposed.

**Review by seokho-son — APPROVED** [review]
LGTM!

**Pull request merged**
