### PR TITLE
Rebase dev-es branch

### PR DESCRIPTION
**Pull request by electrocucaracha**
### Describe your changes

Update dev-es branch before merge in **main**

### Related issue number or link (ex: `resolves #issue-number`)

N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @electrocucaracha 
This PR includes Conflicting files. :)

**Comment by electrocucaracha** [comment]
> Hi @electrocucaracha This PR includes Conflicting files. :)

That's the weird thing @seokho-son because I resolved them locally. Anyway, I'm going to give a try later.

**Comment by electrocucaracha** [comment]
@seokho-son the `Resolve conflicts` button is disabled from my side, could you help me on resolve these rebase conflicts. I'm not sure why it keeps showing them.

**Review by iamNoah1 — COMMENTED** [review]
@electrocucaracha is this still relevant? If yes, there are conflicts that have to be solved FYI :)

**Comment by electrocucaracha** [comment]
> @electrocucaracha is this still relevant? If yes, there are conflicts that have to be solved FYI :)

@iamNoah1 yes, it's. I'm still working on that. I'm not sure why this keep showing conflicts event after solve them locally.

**Comment by electrocucaracha** [comment]
Closing this in favor of #1341

**Pull request closed without merging**
