### PR TITLE
Added definition of SaaS

### PR DESCRIPTION
**Pull request by sandipanpanda**
Added the definition of SaaS in definitions directory. This PR solves issue #198.

### CODE REVIEW

**Comment by CathPag** [comment]
@sandipanpanda, this is great! We took the liberty to tweak the language a little and make it all a little more concise. If you like our changes, we are ready to merge.

**Comment by sandipanpanda** [comment]
Thank you @CathPag for the feedback and improvements.

**Comment by JasonMorgan** [comment]
Override failed checks. PR #212 updated the wordlist.

**Comment by JasonMorgan** [comment]
@sandipanpanda can you give me a thumbs up if you're comfortable with the changes I made to the definition?

**Review by CathPag — APPROVED** [review]
LGTM

**Pull request merged**
