### PR TITLE
[bn] update application-programming-interface

### PR DESCRIPTION
**Pull request by sajibAdhi**
### Describe your changes

Bengali Localization update of application-programming-interface

[Current Preview](https://glossary.cncf.io/bn/application-programming-interface/) | [Deploy Preview](https://deploy-preview-3171--cncfglossary.netlify.app/bn/application-programming-interface/)

### Related issue number or link (ex: `resolves #issue-number`)

Related Issue: #410 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by asem-hamid** [comment]
LGTM

**Comment by asem-hamid** [comment]
LGTM

**Review by asem-hamid — APPROVED** [review]
LGTM

**Review by mitul3737 — APPROVED** [review]
/lgtm

**Pull request merged**
