### PR TITLE
[hi] Rename some markdown files

### PR DESCRIPTION
**Pull request by shivam-sharma7**
### Describe your changes
renames 2 files: `bare_metal_machine.md` and `client_server_architecture.md.`

close: #1732 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by Garima-Negi — APPROVED** [review]

**Review by anubha-v-ardhan — CHANGES_REQUESTED** [review]
Hi @shivam-sharma7, This PR if merged will add `bare-metal-machine` and `client-server-architecture` as additional files making them duplicate of the already existing ones. 

In order to successfully perform a rename, we'll also need to delete already existing ones :)

**Comment by shivam-sharma7** [comment]
> Hi @shivam-sharma7, This PR if merged will add `bare-metal-machine` and `client-server-architecture` as additional files making them duplicate of the already existing ones.
> 
> In order to successfully perform a rename, we'll also need to delete already existing ones :)

okay

**Review by anubha-v-ardhan — APPROVED** [review]
LGTM!
Thank you @shivam-sharma7

**Review by anubha-v-ardhan — CHANGES_REQUESTED** [review]
@shivam-sharma7 DCO check on this PR is failing which basically means the commits are not signed. Can you fix this?
This PR is ready to merge otherwise

**Comment by SaarthakMaini** [comment]
I would recommend running the following commands:

`git commit --amend -s`
`git push --force`

to sign the DCO.

Hope this helps!

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 DCO check on this PR is failing which basically means the commits are not signed. Can you fix this? This PR is ready to merge otherwise

done

**Comment by jihoon-seo** [comment]
@shivam-sharma7 Thank you for your work, but the target branch of this PR is `main`, not `dev-hi`.
Could you either modify this PR to target the `dev-hi` branch (which might be slightly difficult), or
open a new PR by following these steps:
1. In your local dev env, sync your local `dev-hi` branch with the upstream branch `cncf:dev-hi`.
2. Create a new feature branch from your synced local `dev-hi` branch.
3. Create a commit that renames 2 files `bare_metal_machine.md` and `client_server_architecture.md`.
4. Push the feature branch to your forked repo.
5. Open a PR in this repo (`cncf/glossary`), setting the target branch as `dev-hi`, not `main`.

**Comment by shivam-sharma7** [comment]
opened new PR: #2348

**Pull request closed without merging**
