### PR TITLE
Use PageFind for search

### PR DESCRIPTION
**Pull request by cjyabraham**
From https://github.com/cncf/cncf.io/issues/836:

Google Custom Search doesn't seem to produce very good search results on small sites. It'd be better to remove our reliance on Google as well. Instead we can use [PageFind](https://pagefind.app/), which is an open source local search for static sites.

Current issues with GCS on the subsites:
- https://github.com/cncf/glossary/issues/755 addressed by [PageFind multilingual support](https://pagefind.app/docs/multilingual/)
- https://github.com/cncf/glossary/issues/2087
- It's not open source
- It produces poor or [no results on the smaller sites](https://tag-security.cncf.io/search/?q=disappointed#gsc.tab=0&gsc.q=disappointed&gsc.page=1)

Please [test this](https://deploy-preview-3008--cncfglossary.netlify.app/) to see if the search results are useful, complete and that it handles multiple languages effectively.

### CODE REVIEW

**Review by jihoon-seo — APPROVED** [review]
LGTM!
One thing that I want to mention is that
- Currently, it seems that the Bengali, French, and Spanish versions of `search.md` file exist in `main` branch.
  image
- The search feature for e.g., Korean is not working, since there is no Korean version of `search.md` file.
  (e.g., https://deploy-preview-3008--cncfglossary.netlify.app/ko/search/?q=kubernetes show 404 Not Found.)
- To make the search feature working for all languages, each L10n team should localize `search.md` file and apply it to `main` branch.

**Comment by cjyabraham** [comment]
Thanks @jihoon-seo , I've dropped in search.md files in each of the translation directories ready to be translated. At least now they won't get a 404 if they try and search.

**Review by bishal7679 — APPROVED** [review]
LGTM!
Is it visible for Hindi as well?

**Comment by cjyabraham** [comment]
> LGTM! Is it visible for Hindi as well?

yes

**Comment by seokho-son** [comment]
LGTM! Thanks @cjyabraham 

I tested that the functionality works well.
If some strings in the search UI are not localized, I guess we can open a PR to the upstream [PageFind](https://pagefind.app/)

- https://github.com/CloudCannon/pagefind/pull/583 (for Korean for instance)

**Comment by seokho-son** [comment]
Let me merge this PR.

**Review by kumarankit999 — COMMENTED** [review]
Lgtm!!

**Pull request merged**
