### PR TITLE
[zh]Unify file name format, according to the origin English.

### PR DESCRIPTION
**Pull request by Petrie**
Unify file name format, according to the origin English.
Signed-off-by: Petrie <lpfvip2008@gmail.com>

### CODE REVIEW

**Comment by jihoon-seo** [comment]
This commit is proposing the same changes with f86078e in #1031, with these differences:
- This PR is renaming files in `dev-zh` branch.
- f86078e is renaming files in `Jacob953:dev-zh-merge` branch, and consequently `main` branch after merged,
  but not renaming files in `dev-zh` branch.

It seems that these changes are definitely needed in `dev-zh` branch, in prior to applying to `main` branch.

Considering the points above, it would be great to:
1. @Petrie (or @Jacob953, or someone else) open a PR (or update this PR) that 
   **cherry-picks** these commits from [#1031](https://github.com/cncf/glossary/pull/1031) into **`dev-zh`**:
   (Please do not squash when opening PR.)
   - d48fee4
   - 7b70358
   - 83c8d60
   - f86078e
   - 079db8d
2. Before going to Step 3, let's make sure that #1024 is merged.
3. After the PR suggested in Step 1 gets merged, @Petrie (or @Jacob953, or someone else) open a PR that 
   merges `cncf:dev-zh` into `cncf:main`.
   - About your [comment](https://github.com/cncf/glossary/pull/1031#issuecomment-1187289411):
     > Why not use `cncf:dev-zh` as source branch, but `Jacob953:dev-zh-merge`?
   - Yes, it would be great to open a PR that merges `cncf:dev-zh` into `cncf:main` directly (I mean, without creating feature branch),
     if this merging PR has no merge conflicts and thus can be merged cleanly without conflict-resolving efforts.
   - But if there exist merge conflicts, then IMO creating feature branch might be an easier way.

**Comment by Petrie** [comment]
Step 1 completed. 
https://github.com/cncf/glossary/pull/1094 @jihoon-seo

**Comment by Petrie** [comment]
As the step 2 has  completed. 
@Jacob953  Pls continue to finish the step3.  I don't have permission to do that, thanks.

**Comment by hanyuancheung** [comment]
@Petrie pls handle the conflict, than approve it.

**Comment by Petrie** [comment]
> @Petrie pls handle the conflict, than approve it.

Changes in this PR has been merged in https://github.com/cncf/glossary/pull/1094, this pr  can be closed.

**Comment by jihoon-seo** [comment]
This PR has been superseded by #1094.

**Pull request closed without merging**
