### PR TITLE
[ru] Translate microservices-architecture.md

### PR DESCRIPTION
**Pull request by Squoresha**
### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Squoresha** [comment]
Please, check it :)

**Review by kirkonru — COMMENTED** [review]
Thanks for your contribution! Here are some minor corrections from me.

**Comment by Squoresha** [comment]
Thanks for your corrections! Please check it again

**Review by shurup — APPROVED** [review]
Great job! I have literally nothing to suggest :tada:

**Review by kirkonru — APPROVED** [review]

**Pull request merged**
