### PR TITLE
Exclude localized terms from the search

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Exclude localized terms from the search
- Delete unnecessary `.gitkeep` files

### CODE REVIEW

**Review by cjyabraham — APPROVED** [review]
LGTM

**Comment by seokho-son** [comment]
I don't prefer adding the config to all localized files. It is to minimize manage efforts for localized files.

I am not sure we can find anouther way to apply it globally. (By language or directory)
@cjyabraham @jihoon-seo do you have any idea ?

If we cannot find a way, we need to update localization guideline for this settting.

**Comment by cjyabraham** [comment]
I see this as a short-term solution to stop non-English languages pages show up in the search. It's not a great solution because then the search on all other language pages doesn't work. We have a plan, however, to improve things more permanently:

First, I'd like to switch out the search engine to one which supports Hindi in addition to all other languages. See #756.

Second, I'd like to make it so that the search will only search pages that are in the current language. See #755.

I'll keep everyone updated with progress on those issues.

**Comment by seokho-son** [comment]
I believe a permanent solution will be applied. :) 
I hope to bring this issue to a maintainers' meeting to discuss whether this short-term solution is required.

**Comment by seokho-son** [comment]
Maintainers agreed to stay in current status until a solid solution is applied. 
Let's hold this PR until we see some progress on #756, #755.

**Comment by seokho-son** [comment]
Maintainers agreed to stay in current status until a solid solution is applied. 
Let's hold this PR until we see some progress on #756, #755.

**Pull request closed without merging**
