### PR TITLE
Update dev-fr contributors

### PR DESCRIPTION
**Pull request by sestegra**
### Describe your changes

@fydrah decided to step down
@seb-835 has been promoted as approver

The entire dev-fr team:
- shouts out @fydrah for his support, reviews and contributions on dev-fr.
- congratulates @seb-835 on his promotion as approver on dev-fr.

### Related issue number or link (ex: `resolves #issue-number`)

N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @seb-835 
- could you check #723  and leave a comment here to confirm your are going to comply with it ? :)

**Comment by seb-835** [comment]
> Hi @seb-835
> 
> * could you check [Policy for localization approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)  and leave a comment here to confirm your are going to comply with it ? :)

@seokho-son -   done : https://github.com/cncf/glossary/discussions/723#discussioncomment-9333007

**Review by seokho-son — APPROVED** [review]
LGTM! I am going to update cncf/people as well. :)

**Comment by seokho-son** [comment]
- ref: https://github.com/cncf/people/pull/507

**Comment by seokho-son** [comment]
Hi @iamNoah1 @nate-double-u 
Please check this PR and merge. :)

**Review by nate-double-u — APPROVED** [review]

**Comment by nate-double-u** [comment]
Sorry for the delay.

**Pull request merged**
