### PR TITLE
Add and update Issue templates

### PR DESCRIPTION
**Pull request by seokho-son**
Some issue templates seem not used.
 - .github/ISSUE_TEMPLATE/de.yml
 - .github/ISSUE_TEMPLATE/es.yml
 - .github/ISSUE_TEMPLATE/fr.yml
 - .github/ISSUE_TEMPLATE/it.yml
 - .github/ISSUE_TEMPLATE/pt.yml

Also, I propose new issue templates for
 - `Request to add a new term (English)` .github/ISSUE_TEMPLATE/new-term.yml
   - I think we can use the proposed `Request to add a new term (English)` instead of the existing template `English Language Glossary Request`
 - `Request to update existing term (English)` .github/ISSUE_TEMPLATE/update-term.yml

This is to simply issue templates
[Example](https://github.com/seokho-son/glossary/issues/new/choose)
image

[Example](https://github.com/seokho-son/glossary/issues/new?assignees=&labels=lang%2Fen%2Cnew+term&template=new-term.yml&title=%5BNew+term%5D+%60GlossaryTermHere%60)

image

[Example](https://github.com/seokho-son/glossary/issues/new?assignees=&labels=lang%2Fen%2Cupdate+term&template=update-term.yml&title=%5BUpdate+term%5D+%60GlossaryTermHere%60)

image

### CODE REVIEW

**Review by CathPag — COMMENTED** [review]
Looks great, thank you! I know the other languages aren't used (yet). Maybe we can create one template for all nother languages where they can fill in the language in question. What do you think? That way there is at least one.



Request to add a new term (ADD LANGUAGE)

Then: [New term LANGUAGE]: GLOSSARY TERM HERE

what do you think?

**Comment by seokho-son** [comment]
> Request to add a new term (ADD LANGUAGE)

@CathPag Do you mean
Request **to localize** a term (ADD LANGUAGE) ?

**Comment by CathPag** [comment]
I mean a global template where users add the language they are referring to. Just like the fill out the GlossaryTerm, they can add the language.

**Comment by seokho-son** [comment]
@CathPag Updated PR :) according to maintainers' meeting.

(New term)
- new-term.yml
  - Request to add a new term (Default:English)
- new-term-lang.yml
  - Request to add a new term (Optional:Non-English)

(Update term)
- update-term.yml
  - Request to update existing term (English)
- update-term-lang.yml
  - Request to update existing term (Non-English)

**Comment by CathPag** [comment]
+ @iamNoah1 since he contributed the templates (if I remember correctly)

Should we create a non-English version where they can fill in the language?

**Review by JasonMorgan — APPROVED** [review]

**Comment by seokho-son** [comment]
@CathPag the existing templates are from #255 :)

**Pull request merged**
