### PR TITLE
made some changes in the doc- 'automation.md'

### PR DESCRIPTION
**Pull request by a-muk**
I made some changes in the file automation.md . These are very small changes. Please let me know if it is okay.

### CODE REVIEW

**Comment by JasonMorgan** [comment]
Can we link the underlying issue this is addressing? If there is no corresponding issue please create one. Thanks!

**Comment by a-muk** [comment]
@JasonMorgan https://github.com/cncf/glossary/issues/386

**Comment by JasonMorgan** [comment]
Hey @a-muk after looking at a standard definition for automation, ex: https://www.merriam-webster.com/dictionary/automation, it seems like ti covers the term sufficiently well for our purposes. Can you help me understand why/if we should define it separately here?

Regardless, great attempt! Looking forward to seeing more from you as we go forward.

**Comment by a-muk** [comment]
@JasonMorgan I think that the term can be defined in the beginning so that the reader can relate to the whole concept while also seeing the example given in the next line. Is that okay?

**Comment by JasonMorgan** [comment]
@a-muk I think you can write a great definition of the term. My question is more should we publish a CNCF definition when the word itself is well understood outside of our context.

**Comment by a-muk** [comment]
Actually it was an issue mentioned in the glossary repository. The file was already created by someone, I just made some changes in the overall explanation of the term.

**Pull request closed without merging**
