### PR TITLE
[tw] Update style guide in Traditional Chinese

### LINKED ISSUE #2330: [tw] Update `style guide` in Traditional Chinese
1. Update `style guide` in Traditional Chinese 
2. https://glossary.cncf.io/style-guide/
3. Latest changes https://github.com/cncf/glossary/pull/2120

### PR DESCRIPTION
**Pull request by johnlinp**
### Describe your changes

The style guide in Traditional Chinese is out of sync with the English version. This PR keeps it sync with the changes in #2120, and adds 2 more improvements:

- Update the translation of "cloud native" (related to #2283)
- Update the translation of "how it helps" (related to #2318)

### Related issue number or link (ex: `resolves #issue-number`)

related to:
- #2120
- #2283
- #2318

resolves #2330 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by hwchiu — APPROVED** [review]
LGTM

**Review by pichuang — APPROVED** [review]
From my point of view, I think it's easier to read, no problem.

**Comment by ydFu** [comment]
Please refer to this PR https://github.com/cncf/glossary/pull/2120  change range for this adjustment. Please synchronize upstream changes.

**Comment by johnlinp** [comment]
@ydFu Thank you for the review! I've updated my PR.

**Comment by johnlinp** [comment]
> > @ydFu Thank you for the review! I've updated my PR.
> 
> LGTM, thanks please please compress the git commit into one

不好意思，我已經有把你建議的部分壓成一個commit 了，剩下的 commits 是我原本就整理好的 commits ，我覺得這樣比較方便閱讀，請問這樣子可以嗎？

**Comment by ydFu** [comment]
thanks @johnlinp

**Pull request merged**
