### PR TITLE
Merge dev-de into main (for the first German localization live version)

### PR DESCRIPTION
**Pull request by iamNoah1**
Signed-off-by: Noah Ispas (iamNoah1) <noahispas@gmail.com>

replaces: https://github.com/cncf/glossary/pull/1462

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @iamNoah1 

Why do you need to change [CODEOWNERS](https://github.com/cncf/glossary/pull/1463/files#diff-fcf14c4b7b34fe7a11916195871ae66a59be87a395f28db73e345ebdc828085b) ?

**Comment by iamNoah1** [comment]
> Hi @iamNoah1
> 
> Why do you need to change [CODEOWNERS](https://github.com/cncf/glossary/pull/1463/files#diff-fcf14c4b7b34fe7a11916195871ae66a59be87a395f28db73e345ebdc828085b) ?

@seokho-son in the #1462 I saw, that it would override the wording with "Owners of Hindi ..." so I changed it here to be compliant with the rest of the file. Can remove it again if you want.

**Comment by seokho-son** [comment]
@iamNoah1 How about to correct the CODEOWNERS files by rebasing the dev-de branch with the main branch so that the latest contents can be applied to dev-de? (currently, the content is little bit different https://github.com/cncf/glossary/blob/main/CODEOWNERS) 
This will reduce conflicts when we merge dev-de into main branch.

**Comment by iamNoah1** [comment]
> @iamNoah1 How about to correct the CODEOWNERS files by rebasing the dev-de branch with the main branch so that the latest contents can be applied to dev-de? (currently, the content is little bit different https://github.com/cncf/glossary/blob/main/CODEOWNERS)
> This will reduce conflicts when we merge dev-de into main branch.

@seokho-son totally makes sense. I updated this PR to make the rebase and the last refinements (changing state to completed). Closed the other one so this is the main PR to finalize German Content

**Comment by seokho-son** [comment]
Checklist to make localization live.
 - [x] validate all files which are not in the localization directory (content/xx/*)
 - [x] check i18n/xx.toml exist
 - [x] check l10n configuration in config.toml
 - [x] acknowledge to initial localization contributors
 - [x] check Preview works

**Comment by seokho-son** [comment]
Hi @CathPag @jihoon-seo 
I think this PR is ready ! :)

**Review by jihoon-seo — APPROVED** [review]

**Review by CathPag — APPROVED** [review]
LGTM

**Pull request merged**
