### PR TITLE
Platform as a service

### PR DESCRIPTION
**Pull request by manojrayar**
### Describe your changes
Added the new term Platform as a service. 

### Related issue number or link (ex: `resolves #issue-number`)
https://github.com/cncf/glossary/issues/3036

### Checklist before opening this PR (put `x` in the checkboxes)
- [x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by iamNoah1 — CHANGES_REQUESTED** [review]
@manojrayar thanks, ptal at the comment I made in the issue, thanks

**Review by Okabe-Junya — CHANGES_REQUESTED** [review]
see https://github.com/cncf/glossary/pull/3218#pullrequestreview-2192322733

> I am not an official reviewer for the English version, but...
> 
> It looks like you have two PRs open for the PaaS page - the other is #3127. One page is sufficient. It would be better to close one of them, thanks

**Comment by jihoon-seo** [comment]
This PR is to add a new file `content/en/paas-platform-as-a-service.md`,
and the PR #3218 is to update existing file `content/en/platform-as-a-service.md`.

I suggest to close this PR and keep #3218.

**Comment by manojrayar** [comment]
Hi @jihoon-seo , sure. I will do it. 
Thanks.

**Comment by manojrayar** [comment]
Closing this, have raised the PR https://github.com/cncf/glossary/pull/3218 for same.

**Pull request closed without merging**
