### PR TITLE
Update `dev-hi` with `main`

### PR DESCRIPTION
**Pull request by anubha-v-ardhan**
This PR will update the Hindi development branch with changes on main branch.

### CODE REVIEW

**Review by Garima-Negi — APPROVED** [review]
LGTM

**Review by mitul3737 — APPROVED** [review]
LGTM

**Comment by seokho-son** [comment]
Hi @anubha-v-ardhan 

This PR has several conflicts. So, cannot be merged.

**Comment by Garima-Negi** [comment]
> Hi @anubha-v-ardhan
> 
> This PR has several conflicts. So, cannot be merged.

Hi @seokho-son , where can we see the conflicts? I'm only seeing the DCO check fail

**Comment by seokho-son** [comment]
@Garima-Negi 

image

**Comment by Garima-Negi** [comment]
> @Garima-Negi
> 
> image

thanx! created [https://github.com/cncf/glossary/pull/1156](https://github.com/cncf/glossary/pull/1156) without conflicts

**Pull request merged**
