### PR TITLE
Update stateful_apps.md

### PR DESCRIPTION
**Pull request by sudhxnva**
# Update `stateful_apps.md`

This PR addresses issue #147 

I have formatted and edited the definitions using the [style guide](https://github.com/cncf/glossary/blob/main/style-guide.md) reference.

### CODE REVIEW

**Comment by CathPag** [comment]
Thanks, @sudhxnva. We have a few maintainers out of office, so please allow us some time to review as we have quite a few PR waiting for approval as well. Really appreciate your support!

**Comment by JasonMorgan** [comment]
@sudhxnva really great edits! Right now the problem with this definition is that it is kubernetes specific. In order to consider publishing it will need to be broad enough to encompass the whole concept without diving into Kubernetes. We can likely accept it as is and leave it as feedback appreciated. Alternatively if you're willing to rewrite the definition with a broader perspective we could get this published in the next iteration of the glossary. Let me know what you think.

**Comment by JasonMorgan** [comment]
Gone stale, going to close on Tuesday if we don't have any feedback from the author.

**Comment by sudhxnva** [comment]
Hi @JasonMorgan! Sorry for the late response, I have been busy with my semester exams. Thank you for your feedback! I like the idea of possibly merging it for now. I will try making the definitions a not Kubernetes specific at a later time if that's okay with you!

**Pull request closed without merging**
