### PR TITLE
[ja] update redirect settings in Japanese Localization

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Describe your changes

- add redirect rules from `/ja/microservices/` to `/ja/microservices-architecture/` (same as English)
- replace `/ja/microservices-architecture/` to `/ja/microservices/` in `contents/ja` dir

### Background

When localizing, I often found it confusing to link to microservice pages because the destination page differs between Japanese and English.

**English**

https://github.com/cncf/glossary/blob/83d8503c36b5eed1206c7b72a0c99a78f366aa95/content/en/application-programming-interface.md?plain=1#L24

**Japanese**

https://github.com/cncf/glossary/blob/83d8503c36b5eed1206c7b72a0c99a78f366aa95/content/ja/application-programming-interface.md?plain=1#L24

 I thought it would be best to update the redirect rules to resolve this issue.

### Related issue number or link (ex: `resolves #issue-number`)

No issue related to this PR

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
Target pages on the deploy preview site:

- API: https://deploy-preview-2999--cncfglossary.netlify.app/ja/application-programming-interface/
- Distributed Apps: https://deploy-preview-2999--cncfglossary.netlify.app/ja/distributed-apps/
- FaaS: https://deploy-preview-2999--cncfglossary.netlify.app/ja/function-as-a-service/
- Monolithic Apps: https://deploy-preview-2999--cncfglossary.netlify.app/ja/monolithic-apps/
- mTLS: https://deploy-preview-2999--cncfglossary.netlify.app/ja/mutual-transport-layer-security/
- runtime: https://deploy-preview-2999--cncfglossary.netlify.app/ja/runtime/
- service mesh: https://deploy-preview-2999--cncfglossary.netlify.app/ja/service-mesh/
- service: https://deploy-preview-2999--cncfglossary.netlify.app/ja/service/

**Comment by jihoon-seo** [comment]
@Okabe-Junya Thank you for the PR.
One thing is that:
You updated `/ja/microservices-architecture/` links to `/ja/microservices/`, and I guess that you referred the upstream (English) files.
But IMO it is more appropriate to link to the final destination page (in this case, `/lang/microservices-architecture/`), and so we don't need to link to transient URLs (in this case, `/lang/microservices/`).

I tracked why the links in English pages have not been updated, and this is the related PRs:
- [#81](https://github.com/cncf/glossary/pull/81/files): `microservices.md` was added.
- [#206](https://github.com/cncf/glossary/pull/206/files), [#211](https://github.com/cncf/glossary/pull/211/files), [#1199](https://github.com/cncf/glossary/pull/1199/files), : some links to `/microservices/` were added.
- [#1549](https://github.com/cncf/glossary/pull/1549/files): renamed `microservices.md` to `microservices-architecture.md`, and added a redirection rule, but **did not updated the links to `/microservices/`**.

So my suggestion is
1. First we update some links that points `/microservices/` to point `/microservices-architecture/` in all English files, and then
2. Revert some changes of this PR to point `/ja/microservices-architecture/`, not `/ja/microservices/`.

I will open a PR that handles the first part of my suggestion.

**Comment by jihoon-seo** [comment]
@Okabe-Junya 
If #3009 gets merged, then please choose one option from:
1. Revert some changes of this PR to point `/ja/microservices-architecture/`, not `/ja/microservices/`. (Update this PR, not closing)
2. Or, close this PR and open a new one.

Either way is fine to me. 😊

**Comment by Okabe-Junya** [comment]
@jihoon-seo 

Thank you for your comment!! 

I think "Revert some changes of this PR to point `/ja/microservices-architecture/`, not `/ja/microservices/`" means closing this PR.  (Because if revert, no changes in this PR)

**Comment by Okabe-Junya** [comment]
friendly ping @jihoon-seo :)

Can I close this pr? thank you

**Comment by jihoon-seo** [comment]
@Okabe-Junya Sure, please go ahead!

**Pull request closed without merging**
