### PR TITLE
Updated stateless_apps.md

### PR DESCRIPTION
**Pull request by Arvind644**

### CODE REVIEW

**Review by JasonMorgan — APPROVED** [review]

**Comment by JasonMorgan** [comment]
Bit of a weird title as you're modifying stateless, not stateful but we can rename the PR. Otherwise the changes are good.

**Comment by Arvind644** [comment]
@JasonMorgan It is my first time contribute to this one, but I will take care of it next time. Thanks for letting me know my mistakes

**Comment by JasonMorgan** [comment]
No problem, do you mind renaming the PR?

**Comment by Arvind644** [comment]
> No problem, do you mind renaming the PR?

**Comment by Arvind644** [comment]
Yeah I have changed the name of PR

**Comment by JasonMorgan** [comment]
Thanks! Did you close ti intentionally or do you still want it merged?

**Comment by Arvind644** [comment]
Sorry, I just clicked it accidently. I was doing something else

**Pull request closed without merging**
