### PR TITLE
[English]: Load Balancer (issue 330)

### PR DESCRIPTION
**Pull request by TheJaySmith**
#330 PR

### CODE REVIEW

**Comment by JasonMorgan** [comment]
Hey @TheJaySmith this is good work and I'd be happy to help you get it merged. Do you want to merge this as is or are you interested in getting it to completed?

**Comment by TheJaySmith** [comment]
If you or anyone else feels that it's lacking, I can make edits. Otherwise, feel free to merge.

**Comment by JasonMorgan** [comment]
Approving as feedback appreciated. Thanks @TheJaySmith for getting this started!

**Review by JasonMorgan — APPROVED** [review]

**Review by CathPag — APPROVED** [review]
Great start and approved as feedback appreciated

**Pull request merged**
