### PR TITLE
Merge dev-ja into main (for the first Japanese localization live version)

### PR DESCRIPTION
**Pull request by naonishijima**
### Describe your changes

Merge dev-ja int main.

We had translated 23 terms.
https://github.com/cncf/glossary/projects/13#card-90706210

We sincerely thank the contributors who played a key role in the successful localization of the Japanese content within the CNCF glossary.
Contributor list: @kaitoii11 @inductor @yuichi-nakamura @bashi8128 @shizhenhu @HANABE926 @A-aiura @Okabe-Junya
Special thanks: @seokho-son

Check list to make localization live.
- [x] validate all files which are not in the localization directory (content/ja/*)
- [x] check i18n/ja.toml exist
- [x] check l10n configuration in config.toml
- [x] acknowledge to initial localization contributors list
- [x] check Preview works

### CODE REVIEW

**Comment by kaitoii11** [comment]
There's a conflict in `config.toml` so we need to fix that.

**Comment by seokho-son** [comment]
waiting for https://github.com/cncf/glossary/pull/2695 :)

**Comment by seokho-son** [comment]
https://github.com/cncf/glossary/blob/main/content/en/_index.md
has been changed, so https://github.com/cncf/glossary/blob/fccb4bc519df8dae5ff65fab69edd7aa763a59ea/content/ja/_index.md
is outdated a bit mostly about the Acknowledgements part. :) Could you apply the updated parts to dev-ja ?

**Comment by Okabe-Junya** [comment]
It appears that the DCO has not been performed in some commits. Why might this be?

**Comment by Okabe-Junya** [comment]
#2738 has been merged, so I think this PR can now be merged.

It might be a good idea to request a review from CODEOWNERS again.

**Comment by seokho-son** [comment]
I am checking the PR based on the checklist. :)

LGTM except for the `acknowledge to initial localization contributors list`.

Please open a PR to add `acknowledge to initial localization contributors list` to the content/ja/_index.md. :)

The team can select the major contributors who should be listed based on a team discussion. 

The following is one of the examples.
https://github.com/cncf/glossary/blob/main/content/ko/_index.md?plain=1#L27
```
Lastly, the Korean localization of the Cloud Native Glossary was initiated through the contributions of the Cloud Native Glossary Korean Localization Team ([#glossary-localization-korean](https://cloud-native.slack.com/archives/C02PC0MLQKU)), including Jihoon Seo ([서지훈](https://www.linkedin.com/in/jihoon-seo/)), Seokho Son ([손석호](https://www.linkedin.com/in/seokho-son/)), Yunkon Kim ([김윤곤](https://www.linkedin.com/in/%EC%9C%A4%EA%B3%A4-%EA%B9%80-47257914a/)), and various other contributors.
```

**Comment by Okabe-Junya** [comment]
PTAL @seokho-son @jihoon-seo @iamNoah1 @nate-double-u  :)

> LGTM except for the `acknowledge to initial localization contributors list`.
> 
> Please open a PR to add `acknowledge to initial localization contributors list` to the content/ja/_index.md. :)

The PR adding the initial localization contributors list has been merged. 

- #2809 

It seems we are ready to merge the Japanese Localization!!

**Comment by jihoon-seo** [comment]
Thank you for your work, Team Japan!

I have a question:
in preview, some terms in the list are in English, while others are in Japanese characters (I mean, Hiragana, Katakana or Kanji).
Are you okay with this? Or, would it be great to modify the terms in English to Japanese characters?

image

**Comment by Okabe-Junya** [comment]
Thank you!!

I think it's fine as it is. For many Japanese speakers, this order seems to be the most understandable.

However, I would like to leave the final decision to @nao and others who have been leading the Japanese localization project.

FYI: The order in other languages was as follows

### Korean

They seem to be consistently expressing in the format of "Hangul (English)". If we also do it this way, we'll need to create a new PR.

Screenshot 2024-01-25 at 14 54 03

### Simplified Chinese

Like us, they appear to have a mix of English and Kanji. Probably, their order is also sorted by Kanji, just like ours.
ChatGPT
They seem to be consistently expressing in the format of "Hangul (English)". If we also do it this way, we'll need to create a new PR.

Like us, they appear to have a mix of English and Kanji. Probably, their order is also sorted by Kanji, just like ours. (We might have more complexity since we have Katakana in addition to English and Kanji.)

Screenshot 2024-01-25 at 14 57 34

### Traditional Chinese

Traditional Chinese also appears to have a similar order to Simplified Chinese.

Screenshot 2024-01-25 at 14 55 19

**Comment by Okabe-Junya** [comment]
Thank you!!

I think it's fine as it is. For many Japanese speakers, this order seems to be the most understandable.

However, I would like to leave the final decision to @naonishijima  and others who have been leading the Japanese localization project.

FYI: The order in other languages was as follows

### Korean

They seem to be consistently expressing in the format of "Hangul (English)". If we also do it this way, we'll need to create a new PR.

Screenshot 2024-01-25 at 14 54 03

### Simplified Chinese

Like us, they appear to have a mix of English and Kanji. Probably, their order is also sorted by Kanji, just like ours.
ChatGPT
They seem to be consistently expressing in the format of "Hangul (English)". If we also do it this way, we'll need to create a new PR.

Like us, they appear to have a mix of English and Kanji. Probably, their order is also sorted by Kanji, just like ours. (We might have more complexity since we have Katakana in addition to English and Kanji.)

Screenshot 2024-01-25 at 14 57 34

### Traditional Chinese

Traditional Chinese also appears to have a similar order to Simplified Chinese.

Screenshot 2024-01-25 at 14 55 19

**Comment by Okabe-Junya** [comment]
Thank you!!

I think it's fine as it is. For many Japanese speakers, this order seems to be the most understandable.

However, I would like to leave the final decision to @naonishijima  and others who have been leading the Japanese localization project.

FYI: The order in other languages was as follows

### Korean

They seem to be consistently expressing in the format of "Hangul (English)". If we also do it this way, we'll need to create a new PR.

Screenshot 2024-01-25 at 14 54 03

### Simplified Chinese

Like us, they appear to have a mix of English and Kanji. Probably, their order is also sorted by Kanji, just like ours. They seem to be consistently expressing in the format of "Hangul (English)". If we also do it this way, we'll need to create a new PR.

Like us, they appear to have a mix of English and Kanji. Probably, their order is also sorted by Kanji, just like ours. (We might have more complexity since we have Katakana in addition to English and Kanji.)

Screenshot 2024-01-25 at 14 57 34

### Traditional Chinese

Traditional Chinese also appears to have a similar order to Simplified Chinese.

Screenshot 2024-01-25 at 14 55 19

**Comment by naonishijima** [comment]
@jihoon-seo Thank you for your question.

It is common for Japanese people to mix English and Japanese terminology.
Especially in Cloud Native, proper nouns are often written as they are in English.

That's all right.

**Review by jihoon-seo — APPROVED** [review]
LGTM! Thank you for your work guys!

**Review by kaitoii11 — APPROVED** [review]
LGTM!

**Review by iamNoah1 — APPROVED** [review]
LGTM, nice work :) Happy to see another language going live

**Pull request merged**
