### PR TITLE
Scalability page translated to hindi added

### PR DESCRIPTION
**Pull request by NitishKumar06**
Signed-off-by: Nitish Kumar <justnitish06@gmail.com>

The Page (https://glossary.cncf.io/scalability/) needed to be converted into Hindi. The following PR adds the translation of the following page to Hindi.

### CODE REVIEW

**Comment by NitishKumar06** [comment]
@anubha-v-ardhan The following PR (https://github.com/cncf/glossary/pull/1257) has been closed. The new PR for the same changes has been raised here!

**Review by anubha-v-ardhan — CHANGES_REQUESTED** [review]
Thank you @NitishKumar06
Can we remove `.hugo_build.lock` from this PR

**Comment by NitishKumar06** [comment]
Done @anubha-v-ardhan

**Comment by anubha-v-ardhan** [comment]
Hey @NitishKumar06, The [Delete .hugo_build.locl file](https://github.com/cncf/glossary/pull/1275/commits/6f4cf8e77df9b27fd077b46a09db63605c9f42fa) commit was not signed which led to failure of DCO check. Can you fix this please.
Feel free to open a new PR if required.

**Comment by NitishKumar06** [comment]
Sure @anubha-v-ardhan I'll raise a new PR again

**Comment by NitishKumar06** [comment]
@anubha-v-ardhan Kindly go through this PR: https://github.com/cncf/glossary/pull/1284

**Pull request closed without merging**
