### PR TITLE
Redesign to comply with the new CNCF branding

### PR DESCRIPTION
**Pull request by cjyabraham**

### CODE REVIEW

**Comment by cjyabraham** [comment]
This is ready for a final review and merge

**Review by jihoon-seo — APPROVED** [review]
It looks neat to me! 😊

**Comment by seokho-son** [comment]
@cjyabraham 

I hope to check this PR needs rebase with master.

This PR includes changes to `contents/hi/xxx.md` to remove `pre: <i class='fas fa-ruler-horizontal'></i>`
https://github.com/cncf/glossary/pull/702/files#diff-f0035a3662384e762cfe06bd4661211988eae9f632b7e5ab740ef932a16df1acL7

Now, I can find similar header from recently added localized contents from other languages. ([pt-br](https://github.com/cncf/glossary/tree/main/content/pt-br), [it](https://github.com/cncf/glossary/tree/main/content/it))
for instance, https://raw.githubusercontent.com/cncf/glossary/main/content/it/contribute/_index.md

Do we need to apply the changes into the other languages ?

**Comment by cjyabraham** [comment]
Hi @seokho-son , yes. [I have just applied the changes to the it and pt-br languages](https://github.com/cncf/glossary/pull/702/commits/77f7d6b70f0974c229083040d0763dc0824b91d1). It basically just removes the icons from the topnav.

**Review by annalisag-spark — APPROVED** [review]

**Review by edsoncelio — APPROVED** [review]

**Review by CathPag — APPROVED** [review]
Looks great!

**Comment by caniszczyk** [comment]
LGTM

**Review by caniszczyk — APPROVED** [review]

**Pull request merged**
