### PR TITLE
[ko] Update links to point localized pages

### PR DESCRIPTION
**Pull request by jihoon-seo**
~I deliberately set the target branch to `main`, since~ this is kind of hotfix, not a translating job. 😊

### CODE REVIEW

**Comment by seokho-son** [comment]
Some discussion regarding using 'main' branch for l10n fix.

https://github.com/cncf/glossary/pull/832#issuecomment-1116873033

**Comment by jihoon-seo** [comment]
@seokho-son As per your comment, I changed the target branch as `dev-ko`. 😊

**Review by yunkon-kim — APPROVED** [review]
lgtm :-)

**Review by seokho-son — APPROVED** [review]
lgtm

**Pull request merged**
