### PR TITLE
[i18n] Add `xx.toml` entries to CODEOWNERS

### LINKED ISSUE #2199: Reviews for non-English `i18n/xx.toml` are requested to repo maintainers
- Example: #2184

- Suggested solution:
  - move each `i18n/xx.toml` to somewhere else, like `data/i18n/xx/xx.toml`
    (Ref: https://github.com/kubernetes/website/tree/main/data/i18n/ko)
  - create symbolic link (`i18n/xx.toml` -> `data/i18n/xx/xx.toml`)
  - populate `CODEOWNERS` files for each `data/i18n/xx/` directory

Note: if we are to adopt this, then we need to manage & update `data/i18n/xx/xx.toml` files when the root `CODEOWNERS` file gets changed, to make them synced well.

### PR DESCRIPTION
**Pull request by jihoon-seo**
### Describe your changes

This PR is to make GitHub request reviews to localization approvers of each language when a PR that touches `i18n/xx.toml` gets opened.

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2199

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.
    
Note: if we are to adopt this, then we need to manage & update `i18n/data/xx/CODEOWNERS` files when the root `CODEOWNERS` file gets changed, to make them synced well.

When merging this PR, please merge using 'Squash and merge' method.

### CODE REVIEW

**Review by seokho-son — COMMENTED** [review]
Hi @jihoon-seo 

> Note: if we are to adopt this, then we need to manage & update i18n/data/xx/CODEOWNERS files when the root CODEOWNERS file gets changed, to make them synced well.

I hope to avoid syncing distributed CODEOWNERS files.
Instead, I think we can control approvers by using the main [CODEOWNERS ](https://github.com/cncf/glossary/blob/main/CODEOWNERS) file only.

Please note that CODEOWNERS in kubernetes/website and in cncf/glossary work in little bit different way. (k/website uses a prow bot)

```diff
# Approvers for Arabic contents
/content/ar/ @TarekMSayed @same7ammar @AShabana @arezk84
+/data/i18n/ar/ @TarekMSayed @same7ammar @AShabana @arezk84

# Approvers for Bengali contents
/content/bn/ @Arindam200 @Imtiaz1234 @mitul3737 @sajibAdhi
+/data/i18n/bn/ @Arindam200 @Imtiaz1234 @mitul3737 @sajibAdhi

...
```

**Comment by jihoon-seo** [comment]
@seokho-son Good point! I couldn't come up with that.
After seeing your suggestion, this might be able to be achieved by not moving `xx.toml` files and creating symlinks, but just adding lines to existing CODEOWNERS file like:

```diff
# Approvers for Arabic contents
/content/ar/ @TarekMSayed @same7ammar @AShabana @arezk84
+/i18n/ar.toml @TarekMSayed @same7ammar @AShabana @arezk84

# Approvers for Bengali contents
/content/bn/ @Arindam200 @Imtiaz1234 @mitul3737 @sajibAdhi
+/i18n/bn.toml @Arindam200 @Imtiaz1234 @mitul3737 @sajibAdhi
```

@seokho-son How does this seem to you?
I can open a pilot PR to see whether GitHub says that a proposed CODEOWNERS file is okay, like:
image

**Comment by seokho-son** [comment]
@jihoon-seo 

Validation for CODEOWNERS file works for me as well. I think you don't have to open another pilot PR.
I think updating the main CODEOWNERS will pass the validation since existing approvers will be duplicated.

**Review by seokho-son — APPROVED** [review]
LGTM!

**Comment by ydFu** [comment]
LGTM,The verification process has confirmed that the Approvers teams across different language locales `i18n` and `content` are consistent and identical.

**Review by iamNoah1 — APPROVED** [review]

**Pull request merged**
