### PR TITLE
Adding contributor ladder

### PR DESCRIPTION
**Pull request by CathPag**

### CODE REVIEW

**Comment by PadminiRai** [comment]
I'd like to work on this issue.

**Comment by seokho-son** [comment]
@PadminiRai 
It is a PR @CathPag and maintainers are working on this already :)

**Comment by PadminiRai** [comment]
@seokho-son ok

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Review by JasonMorgan — APPROVED** [review]

**Pull request merged**
