### PR TITLE
Update devsecops.md

### PR DESCRIPTION
**Pull request by danpopSD**
suggested some additional definition.

Signed-off-by: danpopsd <dan.papandrea@sysdig.com>

### CODE REVIEW

**Comment by JasonMorgan** [comment]
So this is going to overlap with the changes in #71. Also just being real those titles were mostly just me being sarcastic. Does #71 work for you? If so we can close this.

**Comment by danpopSD** [comment]
do we have a "synonym" or may also be called?

**Comment by JasonMorgan** [comment]
We don't right now but that's a good idea. Do you mind adding that once #70 has been merged?

**Comment by danpopSD** [comment]
sounds good!

**Pull request closed without merging**
