### PR TITLE
[bn] Updated dev-bn with main

### PR DESCRIPTION
**Pull request by mitul3737**
Signed-off-by: Shahriyar Al Mustakim Mitul shahriyarmitul3737@gmail.com
This is an intial PR as may need some improvements!
Tracking issue: #410

### CODE REVIEW

**Comment by mitul3737** [comment]
@jihoon-seo Have a look into this PR 😊

**Review by hanyuancheung — APPROVED** [review]

**Review by jihoon-seo — APPROVED** [review]
Let's move on!

**Comment by jihoon-seo** [comment]
@mitul3737 @Mouly22 @ikramulkayes @Imtiaz1234
Please merge this PR with the merge method "Create a merge commit".

**Comment by seokho-son** [comment]
@jihoon-seo 
I hope to note that
bn l10n approvers cannot merge this kind of PR since this PR includes contents in outside of /contents/bn/*

Let me merge this PR :)

**Comment by mitul3737** [comment]
Thanks @seokho-son @jihoon-seo

**Pull request merged**
