### PR TITLE
Update Docsy to v0.4.0

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Relevant issue: #769
- Update Docsy to [v0.4.0](https://github.com/google/docsy/releases)

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @cjyabraham :) 
Please review this PR. Is it a right time to update Docsy version ?

**Comment by cjyabraham** [comment]
That should be fine, as long as you've tested it thoroughly.

**Review by iamNoah1 — COMMENTED** [review]
Is this PR still up to date?

**Comment by jihoon-seo** [comment]
@iamNoah1 Now I checked again and found that Hugo v0.4.0 was released 11 days ago which is quite recent.
I will update this PR as well. 😊

**Comment by jihoon-seo** [comment]
[Netlify build error](https://app.netlify.com/sites/cncfglossary/deploys/62cbe57fadd699000a49ce63#L86):
> 5:55:49 PM: ────────────────────────────────────────────────────────────────
5:55:49 PM:   1. Build command from Netlify app                             
5:55:49 PM: ────────────────────────────────────────────────────────────────
5:55:49 PM: ​
5:55:49 PM: $ cd themes/docsy && git submodule update -f --init && cd ../.. && hugo
5:55:49 PM: Start building sites …
5:55:51 PM: Total in 1498 ms
5:55:51 PM: Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): SCSS processing failed: file "stdin", line 6, col 1: File to import not found or unreadable: ../vendor/bootstrap/scss/bootstrap.

The error message complains that the file `../vendor/bootstrap/scss/bootstrap` is not found or unreadable,
but I can see that there does exist the file `themes/docsy/assets/vendor/bootstrap/scss/bootstrap.scss` in Docsy v0.4.0.

According to the Netlify build log, Netlify will run `cd themes/docsy && git submodule update -f --init` to build the site, and I think this will update the submodules of Docsy, 
but what is needed here is to update Docsy itself, a submodule of this repo.

So I guess that changing the build command to
- `git submodule update -f --init && hugo` or
- `git submodule update --init --recursive --depth 1 && hugo` ([I brought from kubernetes/website repo](https://github.com/kubernetes/website/blob/main/netlify.toml#L29))

```diff
-cd themes/docsy && git submodule update -f --init && cd ../.. && hugo
+git submodule update -f --init && hugo
OR
+git submodule update --init --recursive --depth 1 && hugo
```
might resolve this error.

@cjyabraham what do you think about this? 😊

**Comment by jihoon-seo** [comment]
FYI: currently I can build the site locally without error:

```
❯ hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z

❯ postcss --version
10.0.0
```

[Build with current Netlify build command]
(Please note that I already updated Docsy to v0.4.0 in my local dev env.)
```
❯ cd themes/docsy && git submodule update -f --init && cd ../.. && hugo
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z
WARN 2022/07/11 19:10:02 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
        {{ $path = .Path }}
  {{ else }}
        {{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.

                   | EN  | HI  | PT-BR | IT  | KO  | ES   
-------------------+-----+-----+-------+-----+-----+------
  Pages            |  85 |  25 |    31 |  23 |  24 |  24  
  Paginator pages  |   0 |   0 |     0 |   0 |   0 |   0  
  Non-page files   |   0 |   0 |     0 |   0 |   0 |   0  
  Static files     | 131 | 131 |   131 | 131 | 131 | 131  
  Processed images |   0 |   0 |     0 |   0 |   0 |   0  
  Aliases          |   1 |   0 |     0 |   0 |   0 |   0  
  Sitemaps         |   2 |   1 |     1 |   1 |   1 |   1  
  Cleaned          |   0 |   0 |     0 |   0 |   0 |   0  

Total in 1420 ms
```

[Build with Suggestion 1 of mine]
```
❯ git submodule update -f --init && hugo
Submodule path 'themes/docsy': checked out '6d751420bd1a54b4707071aa4a5dc8db615c0fda'
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z
WARN 2022/07/11 19:10:27 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
        {{ $path = .Path }}
  {{ else }}
        {{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.

                   | EN  | HI  | PT-BR | IT  | KO  | ES   
-------------------+-----+-----+-------+-----+-----+------
  Pages            |  85 |  25 |    31 |  23 |  24 |  24  
  Paginator pages  |   0 |   0 |     0 |   0 |   0 |   0  
  Non-page files   |   0 |   0 |     0 |   0 |   0 |   0  
  Static files     | 131 | 131 |   131 | 131 | 131 | 131  
  Processed images |   0 |   0 |     0 |   0 |   0 |   0  
  Aliases          |   1 |   0 |     0 |   0 |   0 |   0  
  Sitemaps         |   2 |   1 |     1 |   1 |   1 |   1  
  Cleaned          |   0 |   0 |     0 |   0 |   0 |   0  

Total in 1453 ms
```

[Build with Suggestion 2 of mine]
```
❯ git submodule update --init --recursive --depth 1 && hugo
Start building sites … 
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z
WARN 2022/07/11 19:11:31 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
        {{ $path = .Path }}
  {{ else }}
        {{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.

                   | EN  | HI  | PT-BR | IT  | KO  | ES   
-------------------+-----+-----+-------+-----+-----+------
  Pages            |  85 |  25 |    31 |  23 |  24 |  24  
  Paginator pages  |   0 |   0 |     0 |   0 |   0 |   0  
  Non-page files   |   0 |   0 |     0 |   0 |   0 |   0  
  Static files     | 131 | 131 |   131 | 131 | 131 | 131  
  Processed images |   0 |   0 |     0 |   0 |   0 |   0  
  Aliases          |   1 |   0 |     0 |   0 |   0 |   0  
  Sitemaps         |   2 |   1 |     1 |   1 |   1 |   1  
  Cleaned          |   0 |   0 |     0 |   0 |   0 |   0  

Total in 1442 ms
```

**Comment by jihoon-seo** [comment]
@cjyabraham tried both
`git submodule update -f --init && hugo` and
`git submodule update --init --recursive --depth 1 && hugo`,
but nothing worked.
And we agreed to close this PR for now.
Hope we can resolve this sometime later.

**Pull request closed without merging**
