### PR TITLE
[FR] Merge dev-fr branch into main branch for the third French release

### PR DESCRIPTION
**Pull request by guillaumebernard84**
### Describe your changes

The third release for French localization. 

It adds 18 new translations, and there there is a small fix in the headers on all the words.

Thanks to all the contributors, and especially @seb-835 for his first contributions!

### Related issue number or link (ex: `resolves #issue-number`)
N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by sestegra — APPROVED** [review]
LGTM 🚀

**Comment by seb-835** [comment]
En attente du merge de https://github.com/cncf/glossary/pull/3271  pour review celle la.

**Comment by guillaumebernard84** [comment]
Links are fixed, it can now be merged

**Comment by seokho-son** [comment]
DCO failure due to following reasons, but I don't see any mismatched DCO issue from the log. (guess it is kind of bug)

```
Summary
Commit sha: [b658555](https://github.com/cncf/glossary/pull/3270/commits/b658555b1610cbc2cae8b2e92d56e2267763cf4e), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
Commit sha: [2d60b5f](https://github.com/cncf/glossary/pull/3270/commits/2d60b5f462af44fb1591c0c0fee611fa990bdc98), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
Commit sha: [0fcbbd2](https://github.com/cncf/glossary/pull/3270/commits/0fcbbd2c10c7d34545152c4a5e8188dc451ef7ad), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
Commit sha: [343e6a0](https://github.com/cncf/glossary/pull/3270/commits/343e6a02b56eaa1558931ce7f2ff58833ff83fb4), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
Commit sha: [f78d910](https://github.com/cncf/glossary/pull/3270/commits/f78d9108ff4fed3ff804c570c7e7170a338f5738), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
Commit sha: [57c4831](https://github.com/cncf/glossary/pull/3270/commits/57c48314f26b938a9fb290eeb711290c321ae09f), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
Commit sha: [c0fb45d](https://github.com/cncf/glossary/pull/3270/commits/c0fb45d0d7ffb4f8c1c84af1bdb9d539876ff7d9), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
Commit sha: [de14375](https://github.com/cncf/glossary/pull/3270/commits/de14375c1064a74da0d7d92848adadcb6593402a), Author: Stéphane Este-Gracias, Committer: GitHub; Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)".
```

considering `Expected "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)", but got "Stéphane Este-Gracias [sestegra@gmail.com](mailto:sestegra@gmail.com)` the `expected` and `got` authors are the same, let me set DCO to pass.

And as one of the maintainers, let me merge this PR! 
Thanks to the team and contributors!! :)

**Review by seokho-son — APPROVED** [review]

**Pull request merged**
