### PR TITLE
[zh] Localize 'application_programming_interface

### LINKED ISSUE #851: [zh] Localize 'application_programming_interface'
- [ ] Localize the content/en/application_programming_interface.md to content/zh/ in dev-zh.

### PR DESCRIPTION
**Pull request by Anddd7**
Localize the 'API'. fix #851 

- 'API' is a well-known term, so I only give the full name and translation at the begin.
- Also link the existing zh-cn terms

BTW, about the 'scalability - 扩展/可扩展性', in chinese '扩展' can refer to 'extension' or 'scale', maybe '伸缩/可伸缩性' is better? like #901 #902

### CODE REVIEW

**Review by Jacob953 — APPROVED** [review]
LGTM. Thx.

**Comment by Jacob953** [comment]
> Localize the 'API'. fix #851
> 
> * 'API' is a well-known term, so I only give the full name and translation at the begin.
> * Also link the existing zh-cn terms
> 
> BTW, about the 'scalability - 扩展/可扩展性', in chinese '扩展' can refer to 'extension' or 'scale', maybe '伸缩/可伸缩性' is better? like #901 #902

Make sense. Just make sure it's uniform.

**Comment by Anddd7** [comment]
replaced "扩展" -> "伸缩" for 'scalability'.

**Review by hanyuancheung — APPROVED** [review]

**Comment by hanyuancheung** [comment]
lgtm, @Rocksnake PTAL.

**Review by Jacob953 — APPROVED** [review]
LGTM. Thx!

**Pull request merged**
