### PR TITLE
[zh] merge dev-zh into main

### PR DESCRIPTION
**Pull request by Jacob953**
Follow #1090 

Checklist to make localization live.

- [x] cherry-picks commits from #1094 into dev-zh
- [x] update `cncf:dev-zh` with `cncf:main` #1024 

AND, Thx very much for @jihoon-seo guidance and @Petrie assistance!

### CODE REVIEW

**Review by jihoon-seo — APPROVED** [review]
LGTM!

**Comment by jihoon-seo** [comment]
It would be better to merge this PR after the PR #1104 gets merged into `dev-zh`.

For who merges this PR: please feel free to unhold (or just ignore the `hold` label) and merge if the PR #1104 has been merged!

**Review by hanyuancheung — APPROVED** [review]
lgtm

**Review by seokho-son — APPROVED** [review]
LGTM :) 
Great work !!

**Pull request merged**
