### PR TITLE
update italian contents approvers

### PR DESCRIPTION
**Pull request by sistella**
After a team discussion, we decided to let Francesco be one of the approver

### CODE REVIEW

**Review by meryem-ldn — DISMISSED** [review]

**Comment by seokho-son** [comment]
I agree with changing a team approver.
I will share this PR with maintainers :)

**Comment by seokho-son** [comment]
Hi @fsbaraglia :)
Thank you for your interest for being a localization team approver. Welcome !

Please read the following policy regarding l10n approver, and reply to us.

**[Important]**
 - All candidates need to **leave a comment** that you understood overall policy.
 - The l10n team approvers need to **use your permission appropriately**.
   - The approvers of l10n team will have a push permission to this repository.
It is to make l10n approvers manage (merge) PRs for l10n contributions in your development branch.
Merging a PR to the `main` branch by l10n approvers is restricted.
Even if they are possible to review a PR to the `main` branch and give an approval to the PR, they should not approve the PR. 
So, please do not approve if a PR is not related with your localization.
 - After this PR merged, the approvers will get an **github invitation** for collaborate from settings[bot] of cncf/glossary. You need to accept. 

---

**[PR merge condition to main branch]**
1. only chairs can merge PR to main branch 
2. at least one of codeowners should give approving review
   - codeowners for all files including English contents: https://github.com/cncf/glossary/blob/main/CODEOWNERS#L6 (same as chairs)
3. at least 2 approving reviews are required from approvers.
4. l10n team approvers can give approving review to PR for any file. (but they should not)
   - Ref: https://github.com/cncf/glossary/pull/325#issuecomment-1015024262
   - but since they are not mean to be a reviewer or approver of English contents, we need to guide them not to approve PRs not related with their own l10n.
   - even though l10n team approvers give approving review, they CANNOT merge PR to main branch. it is restricted. (Like this: https://github.com/cncf/glossary/pull/325#issuecomment-1015026130)
   - We will probably have to evolve it over time. Anyway the main branch will be safe by the chairs

**[PR merge condition to dev-xx l10n branch (dev-ko)]**
1. chairs can merge PR to all branches
2. at least one of l10n codeowners should give approving review
    - codeowners for Korean contents: https://github.com/cncf/glossary/blob/main/CODEOWNERS#L13 (same as Korean approvers)
    - if a PR includes files outside of Koean l10n, chairs need to review and merge.
3. at least 2 approving reviews are required from l10n approvers.
4. l10n teams can merge PRs for their dev branch. If a PR includes files outside of l10n contents, They need to get an approval from maintainers (maintainers are codeowners for all files)

---

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Comment by fsbaraglia** [comment]
> Hi @fsbaraglia :)
> 
> Thank you for your interest for being a localization team approver. Welcome !
> 
> 
> 
> Please read the following policy regarding l10n approver, and reply to us.
> 
> 
> 
> **[Important]**
> 
>  - All candidates need to **leave a comment** that you understood overall policy.
> 
>  - The l10n team approvers need to **use your permission appropriately**.
> 
>    - The approvers of l10n team will have a push permission to this repository.
> 
> It is to make l10n approvers manage (merge) PRs for l10n contributions in your development branch.
> 
> Merging a PR to the `main` branch by l10n approvers is restricted.
> 
> Even if they are possible to review a PR to the `main` branch and give an approval to the PR, they should not approve the PR. 
> 
> So, please do not approve if a PR is not related with your localization.
> 
>  - After this PR merged, the approvers will get an **github invitation** for collaborate from settings[bot] of cncf/glossary. You need to accept. 
> 
> 
> 
> ---
> 
> 
> 
> **[PR merge condition to main branch]**
> 
> 1. only chairs can merge PR to main branch 
> 
> 2. at least one of codeowners should give approving review
> 
>    - codeowners for all files including English contents: https://github.com/cncf/glossary/blob/main/CODEOWNERS#L6 (same as chairs)
> 
> 3. at least 2 approving reviews are required from approvers.
> 
> 4. l10n team approvers can give approving review to PR for any file. (but they should not)
> 
>    - Ref: https://github.com/cncf/glossary/pull/325#issuecomment-1015024262
> 
>    - but since they are not mean to be a reviewer or approver of English contents, we need to guide them not to approve PRs not related with their own l10n.
> 
>    - even though l10n team approvers give approving review, they CANNOT merge PR to main branch. it is restricted. (Like this: https://github.com/cncf/glossary/pull/325#issuecomment-1015026130)
> 
>    - We will probably have to evolve it over time. Anyway the main branch will be safe by the chairs
> 
> 
> 
> **[PR merge condition to dev-xx l10n branch (dev-ko)]**
> 
> 1. chairs can merge PR to all branches
> 
> 2. at least one of l10n codeowners should give approving review
> 
>     - codeowners for Korean contents: https://github.com/cncf/glossary/blob/main/CODEOWNERS#L13 (same as Korean approvers)
> 
>     - if a PR includes files outside of Koean l10n, chairs need to review and merge.
> 
> 3. at least 2 approving reviews are required from l10n approvers.
> 
> 4. l10n teams can merge PRs for their dev branch. If a PR includes files outside of l10n contents, They need to get an approval from maintainers (maintainers are codeowners for all files)
> 
> 
> 
> ---

Perfect, Thank you :)

**Review by CathPag — APPROVED** [review]
LGTM

**Pull request merged**
