### PR TITLE
converting to markdown.

### PR DESCRIPTION
**Pull request by JasonMorgan**
Moving our entries to markdown files.

Using the yaml format added complexity with very little gain.

Addresses issue #27

### CODE REVIEW

**Comment by JasonMorgan** [comment]
Put it into draft so we can merge #29 in first.

**Comment by CathPag** [comment]
Looks good to me

**Review by CathPag — APPROVED** [review]
Approved on my end :)

**Review by IdealUsrname — APPROVED** [review]
Files all look good, with no changes missing.

I like the dual-format that allows us flexibility to make changes later on.

**Pull request merged**
