### PR TITLE
Add content/pt-br/bare_metal_machine.md

### PR DESCRIPTION
**Pull request by MrErlison**

### CODE REVIEW

**Review by MrErlison — COMMENTED** [review]
I adjusted this PR for only one file bare_metal_machine. Now, I think there is ok

**Comment by edsoncelio** [comment]
Hey @MrErlison thanks! Could you check the request that I made? With that, I'll approve :)

**Review by edsoncelio — APPROVED** [review]
PTAL @brunoguidone or @jessicalins :)

**Review by brunoguidone — APPROVED** [review]
Review OK

**Pull request merged**
