### PR TITLE
[bn] Merge dev-bn into main

### PR DESCRIPTION
**Pull request by nazma1234**
### Describe your changes
Merging dev-bn into main branch

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by mitul3737 — APPROVED** [review]
LGTM

**Review by Imtiaz1234 — APPROVED** [review]
LGTM

**Comment by mitul3737** [comment]
This website runs successfully!
image

**Comment by seokho-son** [comment]
Hi @nazma1234 

Updating English document from a localization branch directly is not allowed (in general) to prevent conflicts. 
https://github.com/cncf/glossary/pull/1688/commits/158734083473d0377198a2b1f3d8555d0f62faca

This commit includes duplicated changes in a English document (the change has the original author and this PR overwriting it. So we need to avoid this situation.)

A way to update dev-xx branch with latest English document is rebase to or merge commits from main branch)

Other aspects of this PR looks good to me. 
(One minor request from dev-bn approvers. Please try to make a PR has a single commit when it is merged and try to remove meaningless redundant commits such as `update xxx`, `update-1 xxx`, ...)

Could you remove the commit from this PR (branch) ? (please be careful when you handle commits in a branch)

**Pull request closed without merging**
