### PR TITLE
[EN] update Tightly Coupled Architecture

### PR DESCRIPTION
**Pull request by Garima-Negi**
### Describe your changes

This PR fixes the filename and the page title for tightly coupled architecture.
This matches Title in 'loosely coupled architecture'

### Checklist before opening this PR (put `x` in the checkboxes)
- [x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by seokho-son — APPROVED** [review]
Hi @Garima-Negi 
Thanks! LGTM.

(please resolve the merge conflict)

**Comment by seokho-son** [comment]
Hi @Garima-Negi :)
I don't recommend to use the "Resolve conflicts" in github UI, it frequently mix things.

Could you resolve the conflict by your local branch? If you feel difficult on that, you may open a new PR since the suggested change is simple.

**Comment by iamNoah1** [comment]
hei @Garima-Negi, are you able to do it? Or do you need some support?

**Comment by nate-double-u** [comment]
I've rebased the commit on `main`

**Review by nate-double-u — APPROVED** [review]
Thanks for the update @Garima-Negi, and for your patience while we reviewed it.

**Pull request merged**
