### PR TITLE
Create application-programming-interface.md

### LINKED ISSUE #2502: [hi] Localize API for Hindi
Localize Application Programming Interface in Hindi Localization.

Source https://glossary.cncf.io/application-programming-interface/

### PR DESCRIPTION
**Pull request by ARYANis0001**
### Describe your changes
Localization of  API for Hindi

### Related issue number or link
 (resolves #2502 )

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by aj11anuj — COMMENTED** [review]
I want to let you know that, this is a duplicate PR, #1614 already exists.

**Comment by ARYANis0001** [comment]
> I want to let you know that, this is a duplicate PR, #1614 already exists.

Then why issue is raised

**Comment by aj11anuj** [comment]
Closing this one as it's a duplicate.

**Comment by aj11anuj** [comment]
We apologize for the inconvenience caused due to inactivity and busy schedule of us. Currently, the process for Hindi localization is lacking behind and due to which this kind of issues are arising. We will fix whole process in a few days and then you won't face such problems.

**Pull request closed without merging**
