### PR TITLE
Merge dev-ja into main (for the second Japanese localization live version)

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Describe your changes

Merge dev-ja into main to release the Japanese localization v2!!

**Terms to be added**

- #2798 
- #2808 
- #2827 
- #2828 
- #2857 
- #2861 
- #2866 
- #2890
- #2892 
- #2899 
- #2900 

**The following modifications/updates are included**

- #2867 (is already merged into main)
- #2871 
- #2879 
- #2917 

### Related issue number or link (ex: `resolves #issue-number`)

No issue related to this PR

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
@kaitoii11 @naonishijima 

そろそろmainにマージしても良いと思いましたが、どうでしょうか？もう少し待ったほうが良いですかね。。？？

**Comment by naonishijima** [comment]
mainに追加でマージする時のルールはなかったと思うので、ある程度（10件くらい？）まとまったら良いと思います。

**Comment by Okabe-Junya** [comment]
新規単語9つ、修正2つなのでタイミングとしては良さそうな気がします。（個人的にはmainへのマージの間隔は短いほうが良いと思うので、）

（このPRで特に変更は加えていないですが）お手数ですが、レビューいただけると幸いです :)

**Comment by Okabe-Junya** [comment]
PTAL @seokho-son @iamNoah1 @jihoon-seo @nate-double-u :)

Hi folks!!

We are ready to merge `dev-ja` into `main`!!  Please review and merge this PR .

**Comment by seokho-son** [comment]
Thanks!!

On behalf of Japanese team, let me merge this PR. (this PR includes reviewed Japanese content only)

**Review by seokho-son — APPROVED** [review]

**Pull request merged**
