### PR TITLE
[PTBR] Add MrErlison as a Portuguese approver

### PR DESCRIPTION
**Pull request by edsoncelio**
This PR is to add @MrErlison as approver to the Portuguese team.
He’s a great contributor and is helping us a lot.

[Here](https://github.com/cncf/glossary/pulls?q=is%3Apr+author%3AMrErlison) you can a list of the contributions.

### CODE REVIEW

**Comment by edsoncelio** [comment]
Please @jihoon-seo @jihoon-seo could you take a look at it? 🙏🏽

**Comment by edsoncelio** [comment]
@MrErlison could just confirm that you're aware of this please?

**Comment by seokho-son** [comment]
Hi @MrErlison 
Thank you for applying :)

PTAL [Policies for localization approvers (to be confirmed by candidates)](https://github.com/cncf/glossary/discussions/723)

and please leave a comment here to confirm you read the policy and understand it.

**Comment by MrErlison** [comment]
> Hi @MrErlison Thank you for applying :)
> 
> PTAL [Policies for localization approvers (to be confirmed by candidates)](https://github.com/cncf/glossary/discussions/723)
> 
> and please leave a comment here to confirm you read the policy and understand it.

Hi @seokho-son 

I read the policies it and understood.

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Pull request merged**
