### PR TITLE
Feat/service proxy jap

### PR DESCRIPTION
**Pull request by draunger**
I have added service proxy localization in japanese
image

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
@draunger 

As the commenter in #2769 (though not yet a reviewer), I have some comments.

Upon reviewing this PR, it seems there are several issues. Check and correct the following points for the reviewers if you wish to proceed with the review process:

- This PR is directed to the main branch. For Japanese localization, PR need to be made to the dev-ja branch.
- There is a failure in DCO (CI). Please ensure proper signing is added to your commits.
- Your localized file (content/ja/service-proxy.md) does not appear to follow the rules of the Japanese localization project (for example: rules for h2 header titles, full-width and half-width character corrections). Please refer to the document I commented on in #2769 for guidance.
    - https://github.com/cncf/glossary/issues/2769#issuecomment-1898909815
- There is a [template](https://github.com/cncf/glossary/blob/main/.github/pull_request_template.md) for Pull Requests. PR should be created in accordance with it.
    - This should be applied automatically when you open a PR.

**Comment by draunger** [comment]
@Okabe-Junya how to do this dco( ci) failure??

**Comment by Okabe-Junya** [comment]
As one of the Japanese Localization contributors, I would like to comment on the concerns raised in this PR.

Upon reviewing several commits, it seems that this contents do not meet the required quality in terms of language fluency.
(For example: https://github.com/cncf/glossary/pull/2838/commits/4b88e0b7178806dd913eb6751424bb8c4a68194d, https://github.com/cncf/glossary/pull/2838/commits/b25a4716b46c979b344894f01d8b1fb8c5b77fcf)
Since the review process is very labor-intensive, submitted PRs are expected to be of high quality.

As I commented in #2769, the job of Japanese Localization requires a very high level of Japanese language ability (native speaker or equivalent level. you need to understand 「てにをは」「ですます」「半角/全角」and so on).

ref. https://github.com/cncf/glossary/issues/2769#issuecomment-1898909815

Looking at your activities, it appears you are involved in multiple languages. Of course, it would be good if you are proficient in all these languages, but that seems to be a very challenging task.

- https://github.com/cncf/glossary/issues?q=involves%3Adraunger+

While the final decision is up to the maintainers and reviewers, it seems difficult to merge this PR as it is.

**Comment by Okabe-Junya** [comment]
In summary, the following comment expresses what I want to say. (son-san is one of the maintainers of this project)

- https://github.com/cncf/glossary/pull/2605#issuecomment-1815774999

**Comment by draunger** [comment]
@Okabe-Junya means I want to make service proxy Japanese localized more effective am I right.??

**Comment by Okabe-Junya** [comment]
What I want to say is:

- Perform localization tasks in the language you are **most** proficient in.
- PR and files to be changed should follow the template/style guide.
    - As commented, this project has [PR template](https://github.com/cncf/glossary/blob/main/.github/pull_request_template.md) and [style guide](https://github.com/cncf/glossary/blob/dev-ja/content/ja/style-guide/_index.md).
- It may be difficult to accept contributions made by machine translation.
    - The changes made in https://github.com/cncf/glossary/pull/2838/commits/4b88e0b7178806dd913eb6751424bb8c4a68194d https://github.com/cncf/glossary/pull/2838/commits/b25a4716b46c979b344894f01d8b1fb8c5b77fcf seem to be of that nature (or clearly done by someone who is non-native Japanese speaker).
    - （不必要な）句読点やメタタグの変更、h2ヘッダー、不自然な空白の挿入からそのように判断しました

日本語（に関わらずすべての言語の）ローカライズは、その言語のネイティブスピーカーによって行われる必要があります。このPRには明らかにそうではないような変更が多く含まれているため、closeしたいと思います。

**Pull request closed without merging**
