### PR TITLE
[zh] Update dev-zh with main

### PR DESCRIPTION
**Pull request by Jacob953**
### Describe your changes
Update dev-zh with main

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Jacob953** [comment]
I'm willing to handle this stuff #3145 .

The reason why this branch has not been merged to main before is that there are still issues left.

Thx for your reminding @Petrie . We will regularly merge the `dev-zh` branch into the `main` branch so that new contributions can be seen immediately.

**Review by hanyuancheung — APPROVED** [review]
lgtm

**Review by Rocksnake — APPROVED** [review]
LGTM.

**Review by seokho-son — APPROVED** [review]
Let me approve and merge this PR! :)

**Pull request merged**
