### PR TITLE
[bn] Update HEADER TEXT

### PR DESCRIPTION
**Pull request by sarkartanmay393**
Hello @mitul3737, I was having issues updating the previous commit and PR, so closed that PR and committed again the `devops` file only, this is the PR.

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
I need some help. Is everything good in this PR and commit? I am getting a DCO error, I signed off the last commit but still showing that. I think I may have not signed the prev commit that shows this error. Is it so?

**Comment by mitul3737** [comment]
@sarkartanmay393 You need to maintain that signed off format in every PR you create

**Comment by mitul3737** [comment]
@sarkartanmay393  You should follow this format
`Signed-off-by: <Your Name> <Your email>
Localizes ``content/bn/<file_name>``  to Bengali
This is an intial PR as may need some improvements!
Tracking issue: #410
`
You can also see this [docs](https://docs.google.com/document/d/1JssM7ePM0JGHQ_EiZji0l7y1LmGhCoJY_z5k27Ape20/edit?usp=sharing) for more

**Comment by mitul3737** [comment]
@sarkartanmay393  Also you need to create a good PR message like `[bn] Updated the header file for devops.md`

**Pull request closed without merging**
