### PR TITLE
Merge dev-pt into main branch 

### PR DESCRIPTION
**Pull request by edsoncelio**
### Describe your changes
Merge dev-pt into main branch with the following changes:
* Add tags to the definition files
* Add 9 new localized terms

### Related issue number or link (ex: `resolves #issue-number`)
N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

### CODE REVIEW

**Comment by edsoncelio** [comment]
I'll set the DCO to pass manually because there are some PRs inside this one without the signature.

**Comment by seokho-son** [comment]
I know there is DCO issue with squashed commits.
Agree with setting the DCO to pass manually.

**Review by seokho-son — APPROVED** [review]
LGTM!!

Thanks to the team PT ! :)

**Comment by seokho-son** [comment]
@edsoncelio Please make an additional approver from PT team review this PR.

**Review by MrErlison — APPROVED** [review]
Thank you for your support.

**Pull request merged**
