### PR TITLE
[ptbr] Add tags to localized terms

### PR DESCRIPTION
**Pull request by anacunha**
Proposed tags translation requested in #1040:

- `application` - aplicação
- `architecture` - arquitetura
- `fundamentals` - fundamentos
- `infrastructure` - infraestrutura
- `methodology` - metodologia
- `networking` - redes
- `platform` - plataforma
- `security` - segurança

----

- Removed CTRL-M (`^M`) carriage return from `transport-layer-security.md` file

### CODE REVIEW

**Comment by edsoncelio** [comment]
Thank you @anacunha, just a small thing before the LGTM:
* Could [sign your commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) just to pass in the DCO check please?

**Comment by anacunha** [comment]
> Thank you @anacunha, just a small thing before the LGTM:
> 
>     * Could [sign your commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) just to pass in the DCO check please?

Done, @edsoncelio 👍

**Comment by edsoncelio** [comment]
> > Thank you @anacunha, just a small thing before the LGTM:
> > ```
> > * Could [sign your commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) just to pass in the DCO check please?
> > ```
> 
> Done, @edsoncelio 👍

Thank you! We will wait for issue #1048 before merge it :)

**Review by edsoncelio — APPROVED** [review]

**Review by brunoguidone — APPROVED** [review]
LGTM

**Pull request merged**
