### PR TITLE
[ar] Translate "Containerization.md" into Arabic

### PR DESCRIPTION
**Pull request by sultanao**

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Preview: https://deploy-preview-708--cncfglossary.netlify.app/ar/containerization/

**Comment by TarekMSayed** [comment]
LGTM Thanks @sultanao

**Review by TarekMSayed — APPROVED** [review]

**Review by same7ammar — APPROVED** [review]
LGTM Thank you .

**Review by arezk84 — APPROVED** [review]
يبدو ممتاز بالنسبة لي 👍

**Pull request merged**
