### PR TITLE
[hi] localize service_mesh.md

### PR DESCRIPTION
**Pull request by testsabirweb**
This PR is Hindi localization of ```content/hi/service_mesh.md``` 
ref: https://github.com/cncf/glossary/issues/270#issuecomment-1067948488

Please review the PR

### CODE REVIEW

**Review by anubha-v-ardhan — CHANGES_REQUESTED** [review]

**Comment by Garima-Negi** [comment]
LGTM

**Review by Garima-Negi — APPROVED** [review]

**Review by jayesh-srivastava — APPROVED** [review]
lgtm

**Review by anubha-v-ardhan — APPROVED** [review]
LGTM

**Review by anubha-v-ardhan — CHANGES_REQUESTED** [review]
@testsabirweb Can you change the file name to `service-mesh.md`. We prefer keeping the names same as English verison

**Review by Garima-Negi — APPROVED** [review]

**Review by sayantani11 — APPROVED** [review]

**Review by sayantani11 — APPROVED** [review]

**Comment by testsabirweb** [comment]
Hii @anubha-v-ardhan ,
The changes you requested are done, please approve...

**Comment by sayantani11** [comment]
Thanks for the PR!

**Pull request merged**
