### PR TITLE
Localize content/bn/virtual machine.md

### PR DESCRIPTION
**Pull request by sarkartanmay393**
Signed-off-by: <Tanmay Sarkar> <sarkartanmay393@gmail.com>
Localizes ``content/bn/virtual machine.md``  to Bengali
This is an initial PR as it may need some improvements!
Tracking issue: #410

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@mitul3737 Hello, I guess I am having a problem. When I created a new PR for `virtual_machine.md` from a self-made branch `Localize-content/bn/virtual_machine.md`, two file changes showed over there. My previous PR's (`kubernetes.md`) file changes and this (`virtual_machine.md`) is showing. Is it a problem or what? If it is, how can I solve it ?

**Comment by mitul3737** [comment]
@sarkartanmay393 Kindly join the slack channel. We can talk about these at the slack channel

**Comment by mitul3737** [comment]
@sarkartanmay393 You have included 2 files in this branch. You are suggested to create only 1 PR for 1 files only. Therefore , everytime you should create a new branch and add a new file. But in this case, you have kubernetes.md and virtual_machine at the same branch. Also, the file name for virtual machine should not be like this `content/bn/virtual_machine.md` . Rather it should be like `content/bn/virtual-machine.md` . We have already updated the file name format in the #410

**Comment by sarkartanmay393** [comment]
@mitul3737 Okay, let me change the file name. Can tell me one thing, while creating kubernetes file is automatically getting added into new PR ? I have created a new branch for virtual-machine obviously.

**Comment by sarkartanmay393** [comment]
> @sarkartanmay393 Kindly join the slack channel. We can talk about these at the slack channel

Okay sure.

**Pull request closed without merging**
