### PR TITLE
renamed aaS files and adjust their titles to be consistent overall

### PR DESCRIPTION
**Pull request by iamNoah1**
the naming of FaaS, PaaS, IaaS files and their titles have not been consistent. Now they are :)

### CODE REVIEW

**Review by CathPag — APPROVED** [review]
LGTM. Good catch — thanks!

**Comment by iamNoah1** [comment]
@CathPag what do we need to merge it?

**Comment by CathPag** [comment]
@iamNoah1, almost. Per our workflow, we need a second approver. Once that is done, we'll merge :)

**Review by JasonMorgan — APPROVED** [review]

**Comment by JasonMorgan** [comment]
Great change! Thank you!

**Pull request merged**
