### PR TITLE
[Spanish] localize 'Immutable Infrastructure'

### LINKED ISSUE #1377: [Spanish] localize 'Immutable Infrastructure'
Localize the `content/en/immutable-infrastructure.md` document to Spanish

### PR DESCRIPTION
**Pull request by tinniaru3005**
### Describe your changes
Localize the `content/en/immutable-infrastructure.md` document to Spanish

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1377 
Closes #1377 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by tinniaru3005** [comment]
Hey @electrocucaracha, I closed the previous PR and made it again. Can you please tell me if it is okay or if not, which step has to be done differently? I am a bit confused about the branches and how to do them. As it is related to language, I am making the changes directly on GitHub and not cloning it.

**Comment by seokho-son** [comment]
The commit https://github.com/cncf/glossary/pull/1383/commits/51891a282d8ea01ba40a178db2266c6d145847a5 in this PR needs to be removed :)

**Comment by tinniaru3005** [comment]
Hey @electrocucaracha, are the changes fine now?

**Comment by electrocucaracha** [comment]
> Hey @electrocucaracha, are the changes fine now?

I think those changes are fine now. Unfortunately, I can merge them given that I co-authored this, but @raelga @krol3 or @92nqb can take a look

**Review by electrocucaracha — APPROVED** [review]

**Review by ramrodo — APPROVED** [review]
LGTM

**Review by 92nqb — APPROVED** [review]

**Pull request merged**
