### PR TITLE
Add content/pt-br/service.md

### PR DESCRIPTION
**Pull request by MrErlison**
Add content/pt-br/service.md

### CODE REVIEW

**Comment by edsoncelio** [comment]
The definitions for [technology and concepts need to contain three subheaders](https://glossary.cncf.io/style-guide/#three-subheadings), but this definition doesn't contain this.
Do you know If it's right @seokho-son @jihoon-seo? This PR is to service.md definition.

**Comment by jihoon-seo** [comment]
@edsoncelio It seems that the term "Service" is categorized as "concept" but is okay without three subheaders, considering the existing content of this term.
(FYI - The last PR that updated the term "Service": #233)

**Review by edsoncelio — APPROVED** [review]
Thank you!

**Review by brunoguidone — APPROVED** [review]
LGTM

**Pull request merged**
