### PR TITLE
Merge dev-zh into main(for Chinese localization live version)

### PR DESCRIPTION
**Pull request by Jacob953**
Follow #987. Merge Chinese development branch into main. 

Checklist to make localization live.

 - [x] Validate all files which are not in the localization directory (content/zh-cn/*)
 - [x] Insert empty lines before and after the header lines (most of the files already have these, but for example, content/zh-cn/platform_as_a_service.md requires this change.)
 - [x] Add semantic line breaks (this will make the review and maintain jobs easier)
 - [x] Rename markdown filenames (ref: https://github.com/cncf/glossary/commit/2832c5d13329297988223215dabf0f7bbd58db3d)
 - [x] Update relevant links (ref: https://github.com/cncf/glossary/commit/bba3069b8258f2d1fde1df573633b179dbf72b0c)
 - [x] Check Preview works

### CODE REVIEW

**Review by hanyuancheung — APPROVED** [review]
lgtm, thanks for your work!

**Comment by Jacob953** [comment]
Hey, @jihoon-seo. Could you do me a favor? I got a question here. :)
This PR is blocked at the DCO check, so it might be difficult for me to solve alone. Could DCO be set to pass manually?

**Comment by Jacob953** [comment]
Thx a lot for your help, @jihoon-seo! Does this PR still need to be improved?

**Review by jihoon-seo — DISMISSED** [review]
lgtm!

**Comment by Petrie** [comment]
Why not use `cncf:dev-zh` as source branch, but `Jacob953:dev-zh-merge`.

**Comment by jihoon-seo** [comment]
About hold: please see https://github.com/cncf/glossary/pull/1090#issuecomment-1188689860.

**Comment by jihoon-seo** [comment]
The PR #1105 supersedes & closes this PR.

**Comment by seokho-son** [comment]
#1105 has been merged !

Let me close this PR :)

**Pull request closed without merging**
