### PR TITLE
[ja] Enable link checking, and normalize links, add missing

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Describe your changes

- Enable link checking, and normalize links, add missing

### Related issue number or link (ex: `resolves #issue-number`)

ref. #3190 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
cc @chalin

**Comment by Okabe-Junya** [comment]
Just a quick question: Which branch is better to merge into, main or dev-ja?

**Review by naonishijima — APPROVED** [review]
LGTM

**Review by kaitoii11 — APPROVED** [review]
LGTM

**Review by nate-double-u — APPROVED** [review]

**Comment by chalin** [comment]
Thank you for this PR @Okabe-Junya 🙌🏻✨

**Pull request merged**
