### PR TITLE
[bn] Need to add approvers for Bengali Localization

### PR DESCRIPTION
**Pull request by mitul3737**
We need more maintainers for Bengali Localization to keep the PRs checked .

### CODE REVIEW

**Comment by mitul3737** [comment]
@jihoon-seo I hope this PR is okay, right? Created just 1 PR with both files changed

**Comment by seokho-son** [comment]
Hi @Imtiaz1234

Please read [Policies for localization approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)

All candidates need to leave a comment in the PR that you understood policies and information in #723. (l10n teams: please share this message to candidates)

**Comment by Imtiaz1234** [comment]
@seokho-son , I have gone through he policies ☺️

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Review by jihoon-seo — APPROVED** [review]
LGTM!

**Pull request merged**
