### PR TITLE
Rebase dev-ru with the main branch 

### PR DESCRIPTION
**Pull request by kirkonru**
This PR is to rebase the **dev-ru** localization branch to the **main** branch to get new changes.

* No content review is required, since this PR simply updates the dev-ru branch to match the main branch.

### CODE REVIEW

**Comment by kirkonru** [comment]
LGTM

**Comment by kirkonru** [comment]
@seokho-son could you please merge this PR?

**Comment by shurup** [comment]
LGTM

P.S. Sorry that so many people are triggered when we need to rebase. I'll start a Slack thread to discuss if there's any better way to do it next time.

**Comment by seokho-son** [comment]
Thanks! 

As this PR mentioned, 
// No content review is required, since this PR simply updates the dev-ru branch to match the main branch.

Let me merge this PR as one of maintainers.

**Review by seokho-son — APPROVED** [review]

**Pull request merged**
