### PR TITLE
fixed typo in en/content/contribute/_index.md

### PR DESCRIPTION
**Pull request by jaynarayan20**
made necessary changes.

### CODE REVIEW

**Comment by jaynarayan20** [comment]
hey @seokho-son  , @iamNoah1  i've fixed the typo of the issue mentioned above pls check it

**Review by jihoon-seo — APPROVED** [review]

**Comment by jaynarayan20** [comment]
hey @jihoon-seo  @seokho-son @iamNoah1 can you review fixed another typo in the repo.

**Review by seokho-son — APPROVED** [review]
Nice catch ! :)
Thanks @jaynarayan20

**Comment by jaynarayan20** [comment]
thanks

**Pull request merged**
