### PR TITLE
[ja] Following the upstream for `content/ja/_index.md` and minor fixes

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Describe your changes

**Following the upstream**

- update contributors/maintainers
- add the paragraph regarding the Emeritus Maintainers

**minor fixes**

- remove comma
- change the period to the kutenn(`。`)
- add the newline at the end of the file.

### Related issue number or link (ex: `resolves #issue-number`)

- GitHub comment: https://github.com/cncf/glossary/pull/2809#issuecomment-1895363180
- Slack: https://cloud-native.slack.com/archives/C02N2RGFXDF/p1706511157815389?thread_ts=1706414657.825829&cid=C02N2RGFXDF

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
/cc @seokho-son 

I have created this PR to update content that had become outdated. Sorry for the delay.

Best regards :)

**Review by naonishijima — APPROVED** [review]
LGTM

**Comment by seokho-son** [comment]
not a review, but LGTM! :)

**Review by yuichi-nakamura — APPROVED** [review]
LGTM, Thank you.

**Pull request merged**
