### PR TITLE
Create immutable-infrastructure.md

### LINKED ISSUE #1585: Immutable Infrastructure for Hindi
# This issue is to initiate a new l10n Team

Hindi version - Immutable Insfrastructure 
link -  https://glossary.cncf.io/immutable-infrastructure/

### PR DESCRIPTION
**Pull request by Aryan-Singla**
Signed off by: Aryan-Singla [devendergupta4573@gmail.com]

### Describe your changes
Localize Immutable Infrastructure in Hindi

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1585 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by bishal7679** [comment]
Hey @Aryan-Singla as per the guidelines of CNCF glossary you are not allowed to raise multiple PRs at a time. You need to get assigned for that issue first, then you can start working on that!
Apologize for this, but we have to close this PR!

**Comment by Aryan-Singla** [comment]
@bishal7679 No problem. You can assign me first then I will raise the PR

**Comment by bishal7679** [comment]
> @bishal7679 No problem. You can assign me first then I will raise the PR

Let your others PR get merged first!
I hope you understand

**Comment by kumarankit999** [comment]
+1

**Pull request closed without merging**
