### PR TITLE
[tw] Update config.toml

### PR DESCRIPTION
**Pull request by ydFu**
### Describe your changes
Solve the problem of updating `config.toml` in the **main branch**.
Update content:
  - other language config
 
New tw content:
  - weight changes from `11` to `12`
  - change of `[languages.zh-tw.params]`

### Related issue number or link (ex: `resolves #issue-number`)
resolves #2252

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by jihoon-seo — APPROVED** [review]
It seems that this PR does not require localization reviews.
Considering this, LGTM.

**Comment by seokho-son** [comment]
Hi @ydFu :)
Why don't we resolve this issue by rebasing (updating) dev-tw ?
(There will be some conflicts that need to be manually fixed though)

**Comment by ydFu** [comment]
> Hi @ydFu :) Why don't we resolve this issue by rebasing (updating) dev-tw ? (There will be some conflicts that need to be manually fixed though)


Thanks for your reminder,Explain the PR change thinking
In this PR, there are parts that include updating main and adding new tw content. I think that small changes to a single file can reduce the code review workload of cncf owners consist of Maintainers.
Update content:
- other language config

New tw content:
- tw weight changes from 11 to 12
- change of [languages.zh-tw.params]

Use direct `dev-tw` merge/rebase to `main`, it will be a relatively large project such as this issue(https://github.com/cncf/glossary/issues/2355).

If you have any other suggestions, I can also adjust accordingly.

**Comment by seokho-son** [comment]
Hi @ydFu 
Thank you for sharing your idea. :)
Yes, there is pros and cons within the given branch configurations in the Glossary repo.

I still think rebasing dev-tw is more beneficial method this time on the perspective of minimize merge conflicts (changing contents for the same file in different branches may cause merge conflicts. and sometimes we can face conflicts that we are not sure)" 

Regarding the auto-assigned reviewers when we open a PR to merge branches, please nevermind, I think reviewers understand the circumstances. :)

**Comment by ydFu** [comment]
thank for @seokho-son

**Pull request closed without merging**
