### PR TITLE
Create Cloud Native Apps.md

### LINKED ISSUE #2114: [ja] Localize cloud native apps for Japanese
- Localize cloud native apps for Japanese
- https://glossary.cncf.io/cloud-native-apps/

### PR DESCRIPTION
**Pull request by Bhanuteja01**
### Describe your changes
created cloud native apps.md in japanese language

### Related issue number or link (ex: `resolves #issue-number`)
 `resolves #2114 `

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by CathPag** [comment]
Thanks, @Bhanuteja01. I see you are based in India. Can you please confirm that you are a Japanese native speaker or at least fluent in it and that this is not a Google Translate translation? Thank you!

**Comment by Bhanuteja01** [comment]
@CathPag 
You correct i'm from india
I'm learning Japanese language through some tutorial and software 
with that knowledge i completed this task

**Comment by Bhanuteja01** [comment]
@Bhanuteja01
If there any mistake kindly inform me 
I'll rectify

**Comment by Bhanuteja01** [comment]
Once go through the file

**Pull request closed without merging**
