### PR TITLE
[bn] Localize cluster.md

### PR DESCRIPTION
**Pull request by nazma1234**
Signed-off-by: Nazma Khatun  nazma8541@gmail.com
Localizes ``content/bn/cluster.md``  to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #410

### CODE REVIEW

**Review by mitul3737 — APPROVED** [review]
Seems good

**Review by ikramulkayes — APPROVED** [review]
looking fine.

**Review by ikramulkayes — CHANGES_REQUESTED** [review]
change  `ব্যবসা-সমালোচনা` => `ব্যবসা-সংক্রান্ত সমস্যা ` in (L15)

**Review by nazma1234 — COMMENTED** [review]
did change

**Comment by nazma1234** [comment]
@ikramulkayes  can you check now?

**Review by ikramulkayes — APPROVED** [review]
It is okay now. Good job!

**Pull request merged**
