### PR TITLE
add german template file

### PR DESCRIPTION
**Pull request by iamNoah1**

### CODE REVIEW

**Comment by CathPag** [comment]
@iamNoah1, so glad to see you're interested in helping to translate the glossary into German!  We are having a kickoff meeting during our Glossary Working Group meeting this Thursday. If you can, please join us. You can [find the invite here ](https://www.cncf.io/calendar/) by searching for glossary. 

Also, we started a [localization doc](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md) based on what the Kubernetes docs are doing.

**Review by CathPag — APPROVED** [review]
Sieht gut aus! :)

**Comment by iamNoah1** [comment]
@CathPag I will try to attend :)

**Comment by CathPag** [comment]
@iamNoah1, sorry you couldn't make it to the Glossary Working Group. If you're still interested, please join the #glossary-localizations and #glossary-localization-german on the CNCF Slack

**Review by JasonMorgan — APPROVED** [review]

**Pull request merged**
