### PR TITLE
Update approvers for Hindi localization

### PR DESCRIPTION
**Pull request by seokho-son**
### Describe your changes
Add a new approver for Hindi based on a requested by the localization team.
- @abhay-raj19
- @aj11anuj
- @kumarankit999
- @bishal7679

Step down approvers for Hindi based on a requested by the localization team.
- @anubha-v-ardhan 
- @sayantani11 

Thanks to @anubha-v-ardhan @sayantani11 for their valuable contributions so far.
Welcome new localization approver candidates.

- Please note that 
We are going to temporarily increase the maximum number of approvers (so far, it is upto 5 but extend to 6 approvers) and later adjust based on future activities. It is an exceptional case aimed at bolstering the team and only focused on their willingness. 

### Related issue number or link (ex: `resolves #issue-number`)
- https://cloud-native.slack.com/archives/C02PCHEQXK6/p1698053643317859?thread_ts=1696474323.614059&cid=C02PCHEQXK6

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by seokho-son** [comment]
Hello 
- [ ] @abhay-raj19
- [ ] @aj11anuj
- [ ] @kumarankit999
- [ ] @bishal7679

Welcome to the localization approver role!

Please examine and confirm the following policies thoroughly. :)
[Policies for localization approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)

After you confirmed it, please leave a comment in this PR.

**Comment by abhay-raj19** [comment]
Thanks for sharing the new updates @seokho-son.
Read the policy thoroughly and got a good understanding of Approving the changes.

**Comment by bishal7679** [comment]
Thanks for sharing @seokho-son
Went through the policies and understood this regulation 
will comply with the Policies :+1:

**Comment by kumarankit999** [comment]
Thanks @seokho-son
Went through the policies and understood this regulations in this PR

**Comment by aj11anuj** [comment]
@seokho-son 
I understood and will abide by those policies 👍

**Comment by seokho-son** [comment]
ref: https://github.com/cncf/people/pull/312

**Review by nate-double-u — APPROVED** [review]
/lgtm
Thanks everybody!

**Review by jihoon-seo — APPROVED** [review]
Thank you all!

**Pull request merged**
