### PR TITLE
removed "What it is" from style-guide

### LINKED ISSUE #2669: [Portuguese] Update the style guide to reflect the removal of the "What is it" header
## Description
Update the style guide to reflect the removal of the "What is it" header
Ptbr page: https://glossary.cncf.io/pt-br/style-guide/
Original page: https://glossary.cncf.io/style-guide

## References
https://github.com/cncf/glossary/issues/2667
https://github.com/cncf/glossary/issues/2242

### PR DESCRIPTION
**Pull request by professorabhay**
### Describe your changes

removed the `what it is` from the pt-br/style-guide/

close #2669

### CODE REVIEW

**Comment by professorabhay** [comment]
Ok @edsoncelio, I will update all the things.

**Comment by professorabhay** [comment]
Hey @edsoncelio, I will definitely make all the changes by tomorrow. I am busy with my college project. Apologies for the inconvenience!

**Comment by edsoncelio** [comment]
Hi @professorabhay!
What's the source of your branch? dev-pt or main branch?
What I can recommend is to clean up your fork and create a new branch from dev-pt and then try to open the PR again.

**Comment by professorabhay** [comment]
Hi @edsoncelio ! I think there is some misunderstanding. I create a new branch `dev-pt` from the `dev-pt` branch of the origin. But when I open the file to modify then there is no `What is it` header present in the file. After digging more it's already removed in another PR. 

Some Related Images -> 

image
image

The PR #2668 ->
image

**Pull request closed without merging**
