### PR TITLE
Add definition of CaaS

### LINKED ISSUE #262: Add "CaaS"

### PR DESCRIPTION
**Pull request by sandipanpanda**
Fixes #262

### CODE REVIEW

**Comment by jihoon-seo** [comment]
[Spellcheck CI fails](https://github.com/cncf/glossary/runs/4717015925?check_suite_focus=true#step:4:11).

(Currently, [`rojopolis/spellcheck-github-actions` GitHub Action](https://github.com/rojopolis/spellcheck-github-actions) is used for checking spells.)

Adding `caas` and `CaaS` to [`wordlist.txt`](https://github.com/cncf/glossary/blob/main/wordlist.txt) will solve the problem! 😊

**Comment by seokho-son** [comment]
Thank you @jihoon-seo :)
Could you open a PR to resolve it?

**Comment by CathPag** [comment]
@sandipanpanda, glad to see another contribution from you! We created a brand new #glossary channel on the CNCF Slack for this effort. Please join if you can!

**Comment by sandipanpanda** [comment]
Thank you everyone! I would love any feedback or suggestions for improvements.

**Comment by CathPag** [comment]
Yep, coming. We were waiting on the spell check update to be implemented first

**Comment by jihoon-seo** [comment]
> Yep, coming. We were waiting on the spell check update to be implemented first

@CathPag Please check the PR #301 and consider to merge if it looks good to you! 😊

**Comment by JasonMorgan** [comment]
Looks good, with #301 merged you're about ready to go, consider changing the status to completed as the definition looks ready to publish IMO.

**Review by JasonMorgan — CHANGES_REQUESTED** [review]
Please change status to "Completed". Great job as usual.

**Review by CathPag — APPROVED** [review]
Looks great! Made a few small edits directly.

**Comment by jihoon-seo** [comment]
Rebased to apply the changes of the PR #301, and force-pushed.

Now the spellcheck CI passes. 😊

**Review by JasonMorgan — APPROVED** [review]

**Pull request merged**
