### PR TITLE
Updated wordlist.txt with new word "docker"

### LINKED ISSUE #1032: Updating the wordlist folder with the new word

### PR DESCRIPTION
**Pull request by Omkar0114**
fixes #1032

### CODE REVIEW

**Review by iamNoah1 — COMMENTED** [review]
Why do we need that change?

**Comment by Omkar0114** [comment]
The term OR word I added is `docker` is an important term related to cncf and in the glossary, `docker` is not mentioned so we need that change :)

**Comment by iamNoah1** [comment]
@Omkar0114 sure docker is a key vendor for container technologies, but as mentioned in the linked issue we do not update the wordlist unless we need it.

**Comment by Omkar0114** [comment]
Sure, Thanks a lot @iamNoah1 Have a great day ahead!

**Pull request closed without merging**
