### PR TITLE
[tr] devops.md localization to Turkish

### PR DESCRIPTION
**Pull request by symys**
### Describe your changes
Add Turkish I10n for DevOps

Google Doc: https://docs.google.com/document/d/1kX_JAtZo9FnEeJtTV-zZQt4Wu0PxS0skxCBp1v_nF4k/edit#heading=h.mo94ylk0tzfj
Preview: https://deploy-preview-2698--cncfglossary.netlify.app/tr/devops/

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by rwxdash** [comment]
@symys - Can you please fix the commit signings and PR description checklist to make sure everything is in place?

**Review by aliok — APPROVED** [review]
/lgtm
/approve

Thanks, content looks good.

**Review by eminalemdar — APPROVED** [review]

**Comment by aliok** [comment]
@symys 

Now that `dev-tr` branch is merged to `main`, can you rebase your commit onto `main` and create this PR against `main`? Or start from scratch ;)

**Review by rwxdash — APPROVED** [review]

**Comment by aliok** [comment]
@symys 

Sorry, I was wrong earlier. I thought we can now work against the `main` branch, but the Glossary development workflow requires us to still work against the `dev-tr` branch.

See https://cloud-native.slack.com/archives/C02N2RGFXDF/p1709745926614219

**Comment by aliok** [comment]
@symys however, you still need to fix the DCO issue (commit sign off).

**Comment by aliok** [comment]
@symys We're good to go here, except the DCO issue

**Pull request closed without merging**
