### PR TITLE
[EN] Update an existing term (GitOps)

### PR DESCRIPTION
**Pull request by MaryamTavakkoli**
### Describe your changes
Updated an existing term - GitOps

### Related issue number or link (ex: `resolves #issue-number`)
Resolves https://github.com/cncf/glossary/issues/2073 and https://github.com/cncf/glossary/issues/372

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
@MaryamTavakkoli Thank you for your contribution!
But first, it is required that contributors sign off their commits with DCO signature.
You might achieve this by
- `git rebase --signoff HEAD~2` (Ref: https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits)
- and force-push

And it seems that
- the email address configured in your GitHub account, and
- the email address of the commit author (which is from the email address you configured in your local dev env)

does not match.
I recommend you to align those as well, since this will make it easy and clear to identify the commit author's identity (in the form of GitHub account).

PTAL!

**Comment by CathPag** [comment]
...and could we please first finalize the [eBFP PR](https://github.com/cncf/glossary/pull/2050)? We generally don't allow contributors to start working on a new term before the other is finalized, so my apologies for that.

**Comment by MaryamTavakkoli** [comment]
I opened another MR https://github.com/cncf/glossary/pull/2121 and I close this one.

**Comment by MaryamTavakkoli** [comment]
I opened another MR https://github.com/cncf/glossary/pull/2121 and I close this one.

**Pull request closed without merging**
