### PR TITLE
[hi] Rebasing dev-hi branch with main branch

### LINKED ISSUE #1681: Need to rebase all dev-xx (branch for l10n) with main
Hello, this issue is from the maintainers.

Since there are several major changes that affect to development branches for localization (Tags for terms, Deprecated terms, Labeler workflow), all localization branches (dev-xx) needs to be updated.

This is an action item to all localization teams. (especially for the members who are managing development branch itself)

Let me check all localization branches are updated.

- [x] dev-ko
- [x] dev-bn
- [x] dev-hi
- [x] dev-es
- [x] dev-fr
- [x] dev-pt
- [x] dev-zh
- [x] dev-it
- [x] dev-de
- [x] dev-ur
- [x] dev-ar

Please note that there is a target date to complete this issue. After the target date, some PRs to a dev-xx branch which is not updated can face `Some checks were not successful`.

Target date: Feb. 12

### PR DESCRIPTION
**Pull request by shivaabhishek07**
### Describe your changes
Rebasing the dev-hi branch with the main branch.

### Related issue number or link (ex: `resolves #issue-number`)
ref #1681 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by shivaabhishek07** [comment]
It is not the complete PR but for the sake of review in respected areas, I have raised the PR.

**Review by mitul3737 — APPROVED** [review]
LGTM

**Comment by shivaabhishek07** [comment]
Hope everything is done!

**Comment by jihoon-seo** [comment]
@shivaabhishek07 Thank you for your contribution, but this is not an appropriate approach.
Instead, we need to open a PR that merges `main` branch (or its copied branch) into `dev-hi`.
Precisely, it means that we need to push the commits in `main` branch into `dev-hi` "as-is".

For this time, you (or any other contributor) can open the PR at the link https://github.com/cncf/glossary/compare/dev-hi...main
by clicking the green "Create pull request" button.

**Comment by shivaabhishek07** [comment]
@jihoon-seo How about now?

**Review by jihoon-seo — APPROVED** [review]
Now LGTM!

**Review by seokho-son — APPROVED** [review]
LGTM

Thanks @shivaabhishek07 ! :)

**Pull request merged**
