### PR TITLE
[hi] added firewall in hindi

### LINKED ISSUE #764: [hi] Translate `Firewall` into `Hindi`
localization of `Firewall` into Hindi 
- https://glossary.cncf.io/firewall/

### PR DESCRIPTION
**Pull request by starlightknown**
fixes #764 

previous PR #794

### CODE REVIEW

**Comment by Garima-Negi** [comment]
@starlightknown thank you for creating a fresh PR. Please change the base branch from `cncf:main` to `cncf:dev-hi`

**Comment by starlightknown** [comment]
done @Garima-Negi

**Review by iamNoah1 — COMMENTED** [review]
@Garima-Negi @starlightknown changing the target branch in this PR is not enough, the change you want to add has to be based on dev-hi as well :)

**Comment by Garima-Negi** [comment]
> @Garima-Negi @starlightknown changing the target branch in this PR is not enough, the change you want to add has to be based on dev-hi as well :)

Thanx Noah, helping out in Slack

**Comment by sayantani11** [comment]
@starlightknown If you are not able to overcome the issue, the best would be to just make a fresh PR. It will save you the extra work.

**Pull request closed without merging**
