### PR TITLE
[zh] Update Chinese version in main with dev-zh

### PR DESCRIPTION
**Pull request by Jacob953**
### Describe your changes
Update Chinese version in main with dev-zh.

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by hanyuancheung — APPROVED** [review]
LGTM, thanks @Jacob953 !

**Review by Submarinee — APPROVED** [review]
LGTM, thanks @Jacob953 !

**Comment by Jacob953** [comment]
@seokho-son Hi, 31 localizations have been updated for the Chinese version. Could you please review and merge this PR? ;)

**Review by seokho-son — APPROVED** [review]
LGTM!! Thanks! :)

**Pull request merged**
