### PR TITLE
[hi] localizes application-programming-interface.md

### PR DESCRIPTION
**Pull request by WebShivam**
Localizes content/hi/application_programming_interface.md to Hindi

Tracking issue: https://github.com/cncf/glossary/issues/270

Reference: pull #556

### CODE REVIEW

**Review by jayesh-srivastava — APPROVED** [review]
lgtm!

**Comment by jihoon-seo** [comment]
@WebShivam Thank you for your contribution, 
but please branch off from & set merge target as the `dev-hi` branch, not `main` branch. 😊

**Comment by WebShivam** [comment]
Thank you @jihoon-seo  for the correction.
Apologies. I'll take care of this next time :)

**Comment by anubha-v-ardhan** [comment]
@WebShivam There are a large number of unwanted commits on this PR. This probably happened due to changing the branch from `main` to `dev-hi` on GitHub UI, which the branch `api` on fork was branched off from `main`. Can you fix this?

**Pull request closed without merging**
