### PR TITLE
Updated Stateless Apps to New Format

### PR DESCRIPTION
**Pull request by Anubhavjoshi040**

### CODE REVIEW

**Review by CathPag — APPROVED** [review]
Thanks for your contribution! Added sections and links LGTM
Original definition still needs review and approval and will remain in status: feedback appreciated.

**Comment by Anubhavjoshi040** [comment]
Hey @CathPag,  thank you for your approval. Also, I wanted to know if you're still looking forward to building a website and what are the future goals for the glossary.

**Comment by CathPag** [comment]
Yes, that's something the CNCF will help with. We are planning on launching the site by KubeCon NA.

**Review by JasonMorgan — APPROVED** [review]

**Comment by JasonMorgan** [comment]
@Anubhavjoshi040 Can you add CDN to the wordlist.txt on this branch? That will appease our spellchecker and allow me to merge it without the machine complaining.

**Comment by Anubhavjoshi040** [comment]
@JasonMorgan I just added CDN to the wordlist.txt on this branch.

**Comment by Anubhavjoshi040** [comment]
@CathPag Do I have to wait for this PR to be merged before I can work on other issues?

**Comment by CathPag** [comment]
@Anubhavjoshi040, since this is approved, you can work on the next one. Thank you!

**Pull request merged**
