### PR TITLE
Rebase dev-tr branch onto main

### PR DESCRIPTION
**Pull request by aliok**
### Describe your changes
Rebase dev-tr branch onto main. Per https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#localization-team-guidelines

> Localization teams need to get changes from the main branch in their dev-xx branch from time to time. Therefore a PR should be opened where the main branch is merged into dev-xx. The glossary maintainers will then choose the rebase method to complete the PR and keep the history linear.

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by aliok** [comment]
@seokho-son any idea how to bypass DCO here?

Also, is the default merge "rebase"? I don't want a merge commit as it will kill the commit history.

**Comment by seokho-son** [comment]
In case of this PR, approvers do not need to review the content itself.
(just updating dev branch based on upsteam/main)

Let me force merge this PR as a maintainer.

@aliok I set bypass the DCO manually as well (the DCO issue is not from this PR)

**Review by seokho-son — APPROVED** [review]
lgtm

**Comment by aliok** [comment]
Thanks!

**Pull request merged**
