### PR TITLE
Updating how server is launched locally

### PR DESCRIPTION
**Pull request by nate-double-u**
### Describe your changes

Updating how the glossary is launched in local environments
* adding hugo extended to dev-dependencies (new contributors may not have hugo installed globally, or the right version if they do. let's use a specific one in the project)
* adding netlify-cli to dev-dependencies (using netlify-cli to launch the glossary provides a dev environment that more closely resembles prod. We can also test things like redirects when launching this way.)

Updating README as needed.

### Related issue number or link (ex: `resolves #issue-number`)

N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by jihoon-seo — COMMENTED** [review]
This seems a great enhancement!

It works well in my environment:
- no `hugo` executable in `$PATH`
  (to confirm that users do not need `hugo` executable in `$PATH`)
- `npm` 8.5.5

**Review by jihoon-seo — APPROVED** [review]

**Comment by jihoon-seo** [comment]
@nate-double-u Seeing [Netlify build log](https://app.netlify.com/sites/cncfglossary/deploys/64af06ad675b380008baccec#L22), `hugo v0.82.0` is used to build the preview of this PR:
> 5:02:10 AM: Installing Hugo 0.82.0
> 5:02:10 AM: hugo v0.82.0-9D960784+extended linux/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio

Would we need to add `netlify.toml` and specify the Hugo version that Netlify will use?
Like: https://github.com/kubernetes/website/blob/main/netlify.toml
```toml
[build.environment]
NODE_VERSION = "10.20.0"
HUGO_VERSION = "0.111.3"
```

**Comment by cjyabraham** [comment]
Looks good. Thanks!

**Comment by nate-double-u** [comment]
> @nate-double-u Seeing [Netlify build log](https://app.netlify.com/sites/cncfglossary/deploys/64af06ad675b380008baccec#L22), `hugo v0.82.0` is used to build the preview of this PR:
> 
> > 5:02:10 AM: Installing Hugo 0.82.0
> > 5:02:10 AM: hugo v0.82.0-9D960784+extended linux/amd64 BuildDate=2021-03-21T17:28:04Z VendorInfo=gohugoio
> 
> Would we need to add `netlify.toml` and specify the Hugo version that Netlify will use? Like: https://github.com/kubernetes/website/blob/main/netlify.toml
> 
> ```toml
> [build.environment]
> NODE_VERSION = "10.20.0"
> HUGO_VERSION = "0.111.3"
> ```

Good call, i'll make that change today.

**Comment by nate-double-u** [comment]
Took an extra day, but I've added the `netlify.toml` file specifying the hugo and node versions.

**Comment by nate-double-u** [comment]
oops, broke the build. give me a moment 😅

**Comment by nate-double-u** [comment]
A note to future reviewers, `netlify.toml` and `package.json` will need to keep their version of Hugo in sync.

**Review by castrojo — APPROVED** [review]

**Pull request merged**
