### PR TITLE
Localizes `content/bn/distributed-apps.md` to Bengali

### PR DESCRIPTION
**Pull request by PratikDey**
Signed-off-by: [Pratik Dey](https://github.com/cncf/glossary/pull/pratikdey.pro@gmail.com)
Localizes `content/bn/distributed-apps.md` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/cncf/glossary/issues/410

### CODE REVIEW

**Comment by mitul3737** [comment]
Kindly remove "content/bn/blue-green-deployment.md" from this PR

**Review by mitul3737 — CHANGES_REQUESTED** [review]
@PratikDey  Kindly remove "content/bn/blue-green-deployment.md" from this PR. That file is already merged.

**Review by Mouly22 — APPROVED** [review]

**Comment by mitul3737** [comment]
Hey ! Kindly remove `blue-green-deployment.md` from this PR. I can not merge it until you make the changes.

**Comment by sajibAdhi** [comment]
Hey @PratikDey, do you have any update on this PR?
If you are working on this PR kindly let me know.

**Pull request closed without merging**
