### PR TITLE
Remove links to 'Deprecated' / 'Feedback Appreciated' terms

### PR DESCRIPTION
**Pull request by jihoon-seo**
### Describe your changes

From https://github.com/cncf/glossary/issues/2031#issuecomment-1622093398:
> the containerization text refers to the text of "container-image" [https://github.com/cncf/glossary/blob/main/content/en/containerization.md](https://github.com/cncf/glossary/blob/main/content/en/containerization.md?rgh-link-date=2023-07-05T16%3A22%3A27Z)
Does it mean that we have to remove the link to that page in our translation ?

Currently these terms are in 'Feedback Appreciated' status:
- container-image
- digital-certificate
- gitops
- hypervisor
- load-balancer
- stateless-apps

And these are in 'Deprecated' status:
- containers-as-a-service
- database-as-a-service
- debugging
- firewall
- managed-services
- platform-as-a-service
- software-as-a-service
- version-control

This PR removes all the links to the 'Deprecated' or 'Feedback Appreciated' terms, and to their localized versions.

### Related issue number or link (ex: `resolves #issue-number`)

https://github.com/cncf/glossary/issues/2031#issuecomment-1622093398

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by seokho-son** [comment]
Thanks @jihoon-seo 
By the way, if we merge this PR to main branch, related localization branches need to care merge conflicts manually. So, this PR may lead some inconveniences to many folks. What do you think so?

**Comment by jihoon-seo** [comment]
@seokho-son Thank you for your comment.
As you said, some merge conflicts might occur when each localization team
- applies their updates on dev branch into `main` branch, or
- syncs their dev branches with `main`.

But my guess is that those merge conflicts will happen only when contributors touch the lines that this PR touches,
and currently the activity of updating existing localized terms seems to possess relatively low amount, compared to whole contribution activities in this repo (seeing https://github.com/cncf/glossary/pulls?q=is%3Apr+update).

And later if merge conflicts occur, then it would be able for maintainers or other contributors to guide with e.g., how to resolve the merge conflict.

How do you like this? 😊

**Review by electrocucaracha — APPROVED** [review]

**Review by sajibAdhi — APPROVED** [review]

**Review by mitul3737 — APPROVED** [review]

**Review by Jacob953 — APPROVED** [review]

**Review by nate-double-u — APPROVED** [review]
Thanks for this @jihoon-seo, this is a big PR.

I've reviewed the `en` changed, and they look good to me.

**Comment by seokho-son** [comment]
Hi @jihoon-seo,
Please address the merge conflict. It seems challenging to obtain approvals for all associated content (localizations). Let me see whether to force merge this PR or involve all related approvers so they are aware of this change in the main branch.

**Comment by jihoon-seo** [comment]
@seokho-son Okay, I resolved merge conflict by rebasing. 😊

**Review by edsoncelio — APPROVED** [review]

**Comment by iamNoah1** [comment]
@seokho-son @jihoon-seo what do we need to do in order to finish this one?

**Review by ramrodo — APPROVED** [review]

**Review by seokho-son — APPROVED** [review]
LGTM.
Let me merge this PR!

**Pull request merged**
