### PR TITLE
[fr] Add sestegra as an fr approver in dev-fr branch

### PR DESCRIPTION
**Pull request by sestegra**
### Describe your changes

Cherry-pick commit from. `main` branch

### Related issue number or link (ex: `resolves #issue-number`)

N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by jihoon-seo — APPROVED** [review]
Regarding #2064, `@sestegra` is already listed in https://github.com/cncf/people/blob/main/config.yaml#L519,
so it seems that no override by Sheriff will happen.

**Comment by seokho-son** [comment]
Hi @sestegra 

Since this PR is to update the latest codeowner in main branch by using cherry-picked commit, looks good to me as is.

I prefer updating the dev-fr branch entirely since there are many changes in main branch. (need to rebase and adjust merge conflicts manually)

Which method does your team prefer?

**Review by seokho-son — APPROVED** [review]

**Comment by sestegra** [comment]
Hi @seokho-son,
Yes, you can proceed with your preference, as it's easier to manage.

**Comment by seokho-son** [comment]
Thanks @sestegra :)
Please open another PR to update dev-fr branch. I will merge the PR quickly. ;)

(most preferred way to update a dev branch is just creating a PR like https://github.com/cncf/glossary/compare/dev-fr...main , but we cannot use it this time because of merge conflicts).

**Comment by sestegra** [comment]
@seokho-son
I pushed `CODEOWNERS` and `.github/settings.yaml` file from `main` branch on this PR.
Then, I created another PR to fix merge conflicts #2180 to use `dev-fr..main` merges in the future.

**Pull request merged**
