### PR TITLE
Add content\ja\tightly-coupled-architectures.md

### PR DESCRIPTION
**Pull request by nikhilchauhangithub**
### Describe your changes
Add content\ja\tightly-coupled-architectures.md (localize to japanese)

### Related issue number or link (ex: `resolves #issue-number`)
#2137

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by kaitoii11** [comment]
This seems to me like a translation using Google Translate.  Can you please confirm that you are a native Japanese speaker and are not using Google Translate?

**Comment by nikhilchauhangithub** [comment]
I did this with the help of my High School japanese teacher

**Comment by nikhilchauhangithub** [comment]
In my high school, we have the open elective subject of Japanese, and did
this contribution with the help of my high school teacher

**Comment by jihoon-seo** [comment]
@nikhilchauhangithub Thank you for your interest on Japanese localization jobs, but contributing with the help of someone else (your high school teacher in this case) seems not a sustainable way to contribute.
It seems that you are based in India, so you might contribute by taking Hindi localization jobs.

**Comment by nikhilchauhangithub** [comment]
I did this whole work by myself, i didn't take help for work, just for
crosschecking, btw thanks for advice, i applied for hindi localize issues,
kindly assign them to me. Thank you

**Comment by CathPag** [comment]
We appreciate the effort, but localization is not translation. It also requires cultural context. Please join a team that focuses on your native language. If there is none, find some volunteers and create a new one. You'll see that that will be a lot more fun :)

**Pull request closed without merging**
