### PR TITLE
Localize cloud computing for Korean (push permission test)

### PR DESCRIPTION
**Pull request by seokho-son**
This PR provides
Localized `content/en/cloud_computing.md` document.
(also to check push permission)

### CODE REVIEW

**Comment by seokho-son** [comment]
It seems 

https://github.com/cncf/glossary/blob/main/CODEOWNERS works well. :)
image

**Review by jihoon-seo — APPROVED** [review]

**Comment by jihoon-seo** [comment]
It seems that I have had the permission to merge. 😊

image

**Comment by seokho-son** [comment]
FYI: current collaborators and permission.

image

**Comment by seokho-son** [comment]
FYI: some settings not working. (settings App issue)
 - `Restrict who can push to matching branches` collaborator who does not accept invitation is not listed
 - in case of jihoon-seo, I added him by myself in Github UI (not using settings.yaml app)
 - `Eviekim` who is not collaborator yet is not listed

image

**Comment by seokho-son** [comment]
https://github.com/cncf/glossary/blob/main/.github/settings.yml
image

**Review by Eviekim — APPROVED** [review]

**Comment by Eviekim** [comment]
Screenshot 2022-01-18 at 11 55 03
I do have the permission to review and approve PR as well!

**Comment by seokho-son** [comment]
@Eviekim @jihoon-seo 
Please merge this PR. You can merge a PR in dev-ko branch.

**Pull request merged**
