### PR TITLE
[Portuguese] Update tightly coupled architecture and microservices architecture

### LINKED ISSUE #3179: [Portuguese] Rename and update the content of tightly-coupled-architectures.md and microservices.md
Rename the following files:
* `tightly-coupled-architectures.md` -> `tightly-coupled-architecture.md`
* `microservices.md` -> `microservices-architecture.md`

And update the content with the original (`content/en/`)

### PR DESCRIPTION
**Pull request by camilosm**
### Describe your changes

Renamed and updated the following files:

`tightly-coupled-architectures.md` -> `tightly-coupled-architecture.md`
`microservices.md` -> `microservices-architecture.md`

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #3179

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by camilosm** [comment]
@edsoncelio I think everything is in order now. Let me know if I've messed something up.

**Comment by edsoncelio** [comment]
> @edsoncelio I think everything is in order now. Let me know if I've messed something up.

Hi @camilosm, thanks!!
I have just another minor request: Could you open one PR per definition? I saw that you opened this one for microservices and tightly coupled architecture.

**Comment by camilosm** [comment]
No problem @edsoncelio. I did both in this one because they were both in the same issue. Since the PR must be from `dev-pt` branch, should I make one for one of the definitions, wait for approval, then update the same branch with the other definition and open another one?

**Comment by edsoncelio** [comment]
> No problem @edsoncelio. I did both in this one because they were both in the same issue. Since the PR must be from `dev-pt` branch, should I make one for one of the definitions, wait for approval, then update the same branch with the other definition and open another one?

Hi, we can keep it that way!
It was my fault; I saw now that I created the issue with both actions.

As soon as possible, I'll start the review; thanks!!

**Comment by camilosm** [comment]
@edsoncelio let me know if there is anything I should correct

**Review by edsoncelio — APPROVED** [review]

**Comment by edsoncelio** [comment]
PTAL @MrErlison @jessicalins @brunoguidone

**Comment by MrErlison** [comment]
@camilosm Nice contribution!

**Review by MrErlison — APPROVED** [review]

**Comment by camilosm** [comment]
@MrErlison thank you!

**Pull request merged**
