### PR TITLE
[pt-BR] Translate feedback section

### PR DESCRIPTION
**Pull request by edsoncelio**
Translate the feedback section to pt-BR.

Related to #675.

### CODE REVIEW

**Comment by edsoncelio** [comment]
Preview:
image

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Comment by seokho-son** [comment]
@jihoon-seo This PR needs to be merged. for #675 :)

**Review by jihoon-seo — APPROVED** [review]
@seokho-son I was thinking that it would be great if at least one of `pt-br` approvers approves for the `pt-br` strings.. 😊

@brunoguidone @jessicalins Could you please take a look and approve? 😊

**Review by jessicalins — APPROVED** [review]
LGTM! :rocket:

**Pull request merged**
