### PR TITLE
feat: add content es/observability

### PR DESCRIPTION
**Pull request by krol3**
Translation observability.md to Spanish. Related issue https://github.com/cncf/glossary/issues/409

### CODE REVIEW

**Comment by jihoon-seo** [comment]
To CNCF Glossary maintainers (@CathPag @JasonMorgan @cjyabraham @seokho-son ...):
it seems that Netlify preview build is not configured for `dev-es` branch.
PTAL! 😊

**Comment by cjyabraham** [comment]
Ok, I've added the `dev-es` branch. You may need to commit to it in order to trigger the deploy.

**Review by electrocucaracha — APPROVED** [review]
/lgtm

**Review by raelga — APPROVED** [review]

**Comment by raelga** [comment]
@krol3 Puedes hacer un nuevo commit, por ejemplo quitando el último salto de linea o haz un nuevo commit, súbelo, borra el commit en local y sube de nuevo con un force-push. Así activamos el despliegue de netlify.

**Pull request merged**
