### PR TITLE
Add @guillaumebernard84 as an fr approver

### PR DESCRIPTION
**Pull request by sestegra**
### Describe your changes

In recognition of @guillaumebernard84's dedicated contributions to the French localization team, this PR elevates him to the role of approver.

### Related issue number or link (ex: `resolves #issue-number`)

N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by huats — APPROVED** [review]
It is well deserved !

**Review by caniszczyk — APPROVED** [review]

**Comment by seokho-son** [comment]
Hi @guillaumebernard84,
Thank you for your valuable contributions to the French localization so far!
Please review the [Policy for Localization Approvers (Pending Candidate Confirmation) #723](https://github.com/cncf/glossary/discussions/723). After review it, please leave a comment on this PR to confirm that you've read and understood the policy. :)

**Comment by seokho-son** [comment]
Hi @sestegra 
Could you share the above message to @guillaumebernard84 ? :)

**Comment by guillaumebernard84** [comment]
> Hi @guillaumebernard84, Thank you for your valuable contributions to the French localization so far! Please review the [Policy for Localization Approvers (Pending Candidate Confirmation) #723](https://github.com/cncf/glossary/discussions/723). After review it, please leave a comment on this PR to confirm that you've read and understood the policy. :)

Hello @seokho-son , I have read and understood the policy 👍

**Comment by seokho-son** [comment]
Thanks!

After https://github.com/cncf/people/pull/289 , I am going to merge this PR. :)

**Review by seokho-son — APPROVED** [review]
LGTM!

**Pull request merged**
