### PR TITLE
[ko] Update _index.md

### PR DESCRIPTION
**Pull request by yunkon-kim**
### Describe your changes
This PR reflects changes in the main branch.

### Related issue number or link (ex: `resolves #issue-number`)
#2387

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @yunkon-kim 
Could you check the checklist yourself? :)

**Comment by yunkon-kim** [comment]
@seokho-son 
Oh~ I'm sorry I didn't check the checklist. I have checked those.

**Review by jihoon-seo — APPROVED** [review]
LGTM 입니다!

**Comment by yunkon-kim** [comment]
@seokho-son PTAL ^^

**Review by seokho-son — APPROVED** [review]
LGTM!

**Pull request merged**
