### PR TITLE
Adds Zero Trust Architecture.

### PR DESCRIPTION
**Pull request by ChrisJBurns**
- adds ZTA to the Glossary.

### CODE REVIEW

**Comment by CathPag** [comment]
Thanks for your PR, @ChrisJBurns! We'll be reviewing sometime next week.

**Comment by ChrisJBurns** [comment]
@CathPag  any update on this?

**Review by JasonMorgan — CHANGES_REQUESTED** [review]
Please set the status to "Feedback Appreciated".

**Review by JasonMorgan — APPROVED** [review]

**Comment by JasonMorgan** [comment]
Hye @ChrisJBurns Sorry about the delay, I'll try and get you merged today. Thanks for getting this submitted!

**Comment by ChrisJBurns** [comment]
Great, thanks @JasonMorgan

**Review by CathPag — APPROVED** [review]

**Pull request merged**
