### PR TITLE
Merge dev-ko into main (for the first Korean localization live version)

### PR DESCRIPTION
**Pull request by seokho-son**
Merge Korean development branch into main.

Requirements to go live have been completed.
 - #379

---

Check list to make localization live.
 - [x] validate all files which are not in the localization directory (content/xx/*)
 - [x] check i18n/xx.toml exist
 - [x] check l10n configuration in config.toml
 - [x] acknowledge to initial localization contributors list
 - [x] check Preview works

### CODE REVIEW

**Comment by seokho-son** [comment]
acknowledge to initial localization contributors list

will be resolved by 

#800

**Review by jihoon-seo — APPROVED** [review]
LGTM 입니다. 😊

**Review by yunkon-kim — APPROVED** [review]
LGTM !!! 😄

**Comment by seokho-son** [comment]
@jihoon-seo 
This PR seems ready to be merged !!

Please check and merge this PR. 
Preferred merge method: `Create a merge commit`

**Pull request merged**
