### PR TITLE
Typo Changes from 'document' to 'manifest file'

### PR DESCRIPTION
**Pull request by dipankardas011**
Signed-off-by: Dipankar Das <dipsonu10@hotmail.com>

### CODE REVIEW

**Comment by jihoon-seo** [comment]
One can also see:
- https://github.com/kubernetes/website/pull/30066
- https://github.com/kubernetes/website/pull/30066/files#diff-d634fb9d23b84e3df8f51b2d53be10dcac4a22aa2fb9270944869d51ab8258bbR48

```diff
-Here's the configuration file for a LimitRange:
+Here's an example manifest for a LimitRange:
```

**Comment by dipankardas011** [comment]
@jihoon-seo want to ask what is 100m CPU limit and 100M CPU limit mean? and how are they different

**Comment by jihoon-seo** [comment]
@dipankardas011 I replied you via Slack DM.

**Review by iamNoah1 — APPROVED** [review]
thanks @dipankardas011 
lgtm

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Pull request merged**
