### PR TITLE
Update issue template for updating a term

### PR DESCRIPTION
**Pull request by seokho-son**
This PR updates issue template for updating a term.

Based on the suggestion (adding triage process for the issue template for updating term) 
by @iamNoah1 :)

### CODE REVIEW

**Comment by CathPag** [comment]
We should also add a checkbox confirming the term meets the cloud native definition criteria. This should probably go right under "There is no existing issue yet. "

- [ ] This term meets the [CNCF's cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md)

**Comment by jihoon-seo** [comment]
@CathPag It seems that you suggested about [the template for adding a new term](https://github.com/cncf/glossary/blob/main/.github/ISSUE_TEMPLATE/new-term.yml), is this right? 😊

**Comment by CathPag** [comment]
> @CathPag It seems that you suggested about [the template for adding a new term](https://github.com/cncf/glossary/blob/main/.github/ISSUE_TEMPLATE/new-term.yml), is this right? 😊

Oops, you're right :)

**Review by iamNoah1 — APPROVED** [review]
lgtm

**Pull request merged**
