### PR TITLE
Modify a sentence in cloud native definition clearly

### PR DESCRIPTION
**Pull request by seokho-son**
This PR modifies a sentence in cloud native definition clearly.

I think people who search a definition for cloud native tech may not understand what is ‘promise of the cloud’.

So, I'd like to remove ‘promise of the cloud’ and refine the sentence.

### CODE REVIEW

**Comment by seokho-son** [comment]
I think the current setting for Labeler works for `main` branch.

**Comment by jihoon-seo** [comment]
For now (with `.github/workflows/labeler.yml` like this:),
```yaml
on:
- pull_request_target
```

the Labeler workflow will be executed for all possible activity types, [which are](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target):
- assigned
- unassigned
- labeled
- unlabeled
- opened
- edited
- closed
- reopened
- synchronize
- converted_to_draft
- ready_for_review
- locked
- unlocked
- review_requested
- review_request_removed
- auto_merge_enabled
- auto_merge_disabled

And you can see that the workflow has been executed 2 times by now.
https://github.com/cncf/glossary/actions/workflows/labeler.yml
image

---

I cannot guess why the workflow was not executed when you opened the PR #471 🤔
Maybe.. if not specified, then the workflow runs only for `main` branch? 🤔

If this guess is right, then we need this option too:
```YAML
    branches:    
      - '**'
```

**Comment by seokho-son** [comment]
@jihoon-seo I think we need both 'opened' and 'synchro'. 
After we push or update commits in a PR, labels can be updated too according to the files that the commits include.

> Maybe.. if not specified, then the workflow runs only for main branch? 🤔

I think so :)

**Review by CathPag — APPROVED** [review]
LGTM

**Review by iamNoah1 — APPROVED** [review]
lgtm

**Pull request merged**
