### PR TITLE
[tr] Merge main into dev-tr

### PR DESCRIPTION
**Pull request by aliok**
### Describe your changes
Merge main into dev-tr

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by aliok** [comment]
@seokho-son can you skip the DCO checks here?

**Comment by jihoon-seo** [comment]
I manually set DCO to pass.

**Review by jihoon-seo — APPROVED** [review]
LGTM! Thank you for your work @aliok

**Comment by aliok** [comment]
@seokho-son sorry to ping you again, but can you merge this one manually?

**Review by seokho-son — APPROVED** [review]

**Pull request merged**
