### PR TITLE
[ar] Translate 'Container Image' into Arabic

### PR DESCRIPTION
**Pull request by sultanao**

### CODE REVIEW

**Review by sultanao — COMMENTED** [review]
Edited punctuation , namely commas.

**Review by sultanao — COMMENTED** [review]
Reviewed again.

**Review by TarekMSayed — APPROVED** [review]
Thanks @sultanao  for the good job

**Review by same7ammar — APPROVED** [review]
Thanks, @sultanao  for awesome contribution .

**Pull request merged**
