### PR TITLE
add Adriana to german approver team

### PR DESCRIPTION
**Pull request by iamNoah1**

### CODE REVIEW

**Review by CathPag — APPROVED** [review]
LGTM

**Review by jihoon-seo — APPROVED** [review]

**Comment by iamNoah1** [comment]
You are right @seokho-son. In this case I think we can skip the whole procedure, what do you think @CathPag?. Catherine joined David and me on the german localization only because we did not have a third person until Adriana joined. She is one of the "initial" approvers and we had already a kick off meeting with her.

**Comment by CathPag** [comment]
Now that we have three German approvers (including Adriana), I can be removed. I was always just a placeholder :)

**Comment by iamNoah1** [comment]
> Now that we have three German approvers (including Adriana), I can be removed. I was always just a placeholder :)

done :)

**Pull request merged**
