### PR TITLE
[es] Merge the `dev-es` branch into `main` branch

### PR DESCRIPTION
**Pull request by ramrodo**
### Describe your changes

This PR will merge `dev-es` updated branch into `main` branch

### Related issue number or link (ex: `resolves #issue-number`)

N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by ramrodo** [comment]
@seokho-son not sure why/how we passed two commits not signed well on DCO. Could you/we use `squash and merge` option to fix this?

**Comment by iamNoah1** [comment]
I think you should be able to do it on the dev-es branch yourself :) You can see how to do it here: https://github.com/cncf/glossary/pull/2962/checks?check_run_id=22000165768. If you have any issues you can ping us again and we assist. @ramrodo

**Comment by seokho-son** [comment]
Anyway, to merge this type PR, admin(some of maintainers) needs to mege. 
Let me merge to expedite localization efforts.

**Review by seokho-son — APPROVED** [review]
lgtm

**Pull request merged**
