### PR TITLE
[es] Enable link checking and normalize links

### PR DESCRIPTION
**Pull request by ramrodo**
<s>Before merging this PR, we should merge first https://github.com/cncf/glossary/pull/3221 to update our `dev-es` branch and then, submit these changes to `main` branch.</s>

<s>Merge first https://github.com/cncf/glossary/pull/3229 to include the new term and content updated.</s>

<s>Merge first https://github.com/cncf/glossary/pull/3231 to include `dev-es` branch to main and include the latest changes.</s>

### Describe your changes

- Contributes to https://github.com/cncf/glossary/issues/3190
- Normalizes links, adding a trailing slash, as reported by the link checker

### Related issue number or link (ex: `resolves #issue-number`)

https://github.com/cncf/glossary/issues/3190

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by ramrodo** [comment]
/cc @Okabe-Junya @electrocucaracha @krol3 
Could you please take a look at this PR?

**Review by electrocucaracha — APPROVED** [review]
/lgtm

**Review by krol3 — APPROVED** [review]
awesome work !!

**Comment by ramrodo** [comment]
@nate-double-u  could you help me to review and merge this PR, please?

**Review by nate-double-u — APPROVED** [review]
Interesting, I'm not sure why merging would be blocked here -- you've got two approvals from the Spanish Approvers list.

Let's see if a general approve helps get it unstuck (maybe it has to do with the .htmltest.yml file change).

LGTM

**Pull request merged**
