### PR TITLE
Add image files for how-go guide

### PR DESCRIPTION
**Pull request by seokho-son**
This PR is to add image files for how-go guide that will be improved by PR #321.

static/images/how-to/**howto-XX.png**

PR #321 needs to be updated after this PR has been merged.

PTAL @CathPag

### CODE REVIEW

**Review by CathPag — APPROVED** [review]
Thank you!!

**Review by jihoon-seo — DISMISSED** [review]

**Comment by seokho-son** [comment]
@jihoon-seo I hope to make l10n team approvers cannot approve PR which has English contents.
However, it seems hard to avoid since the approvers need to have a write permission.

@jihoon-seo could you tell me you can merge this pull request ?
image

@JasonMorgan @CathPag Please don't worry. We are testing permission. We know what we are doing ;)

**Comment by jihoon-seo** [comment]
GitHub says that I am not authorized to merge this pull request. 😊

image

**Comment by seokho-son** [comment]
@jihoon-seo 
Thanks ! It is an appropriate restriction.

Please cancel the approval :)

**Review by JasonMorgan — APPROVED** [review]

**Pull request merged**
