### PR TITLE
Added Cloud Native Security File

### PR DESCRIPTION
**Pull request by aryasoni98**
### Describe your changes
Created a file `cloud-native-security.md` to localize the page: `glossary/content/ja` into japanese

### Related issue number or link (ex: `resolves #issue-number`)
#2112 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `git-config` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @naonishijima 
Please guide @aryasoni98 to use the right dev branch for Japanese localization. :)

**Comment by aryasoni98** [comment]
Please review my PR @caniszczyk @seokho-son @jihoon-seo @CathPag @JasonMorgan @iamNoah1

**Comment by naonishijima** [comment]
Hi @aryasoni98.
Please check my comment https://github.com/cncf/glossary/pull/2126/#issuecomment-1589160231 .
We can not PR to main branch. Localization Japanese branch is dev-ja.

**Comment by aryasoni98** [comment]
> Hi @aryasoni98. Please check my comment #2126. We can not PR to the main branch. Localization Japanese branch is dev-ja.

I just make another PR #2140 please check it. So, should I close this PR

**Pull request closed without merging**
