### PR TITLE
[ja] hotfix: fix typo in Initial localization contributors list

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Describe your changes

There was a typo in the contributor's name. The name `yuichi-nakamura` san was mistakenly written as `yuishi-nakamura`. This typo has been corrected.

Screenshot 2024-01-28 at 12 52 07

### Related issue number or link (ex: `resolves #issue-number`)

no issue related to this PR

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
I think this should be corrected promptly. Therefore, I would like to merge it into the main instead of the dev-ja branch (after merged, main will be merged into dev-ja).

**Review by naonishijima — APPROVED** [review]
LGTM

**Review by kaitoii11 — APPROVED** [review]
LGTM

**Comment by seokho-son** [comment]
Since this fix is a hot fix, let me approve and merge this PR. (as a maintainer)
Team Japanese ~! Please update dev-ja after this PR so that you can minimize upcoming merge conflict.

Also, the glossary repo does not recommend using main branch as PR base for contents in localization area.
PTAL thought behind of it. :)
https://cloud-native.slack.com/archives/C02N2RGFXDF/p1706464829614969?thread_ts=1706414657.825829&cid=C02N2RGFXDF

> Thank you for your suggestion. I understand the inconvenience of having to work across branches even for minor and urgent modifications when utilizing the localization branch. However, considering the current branch and permission settings in the Glossary repository, there are some concerns about directly making modifications in languages other than English in the main branch.
> 1. There's a higher likelihood of merge conflicts when opening PRs between branches. Currently, we try to minimize working on localized content in the main branch to reduce the possibility of these conflicts. When merge conflicts occur, contributors have to manually add commits to resolve them, which many find cumbersome. Also, PRs not between upstream branches require more thorough review by the maintainers. (Considering the number of languages we localize, this adds to the maintainer's workload.)
> 2. Merge permissions on the main branch are exclusively held by repository maintainers. Thus, when a PR related to localization (even if it's minor) is opened in main, it requires a maintainer's review. (Note that cncf/glossary has a different authority structure and handling method from kubernetes/website.)
> 3. If we start allowing PRs in main for localization work, there's a risk that new contributors, who may not have checked the guidelines in advance, could frequently open localization PRs in main. Each of these PRs would require reiterating the guidelines.

> Anyway, maintainers can participate and assist in pre-discussed situations (like truly urgent hotfixes or when content changes are needed across all languages).
> By the way, the current repository configuration is not the only solution. If you have any better ideas, please feel free to suggest them.
>

**Review by seokho-son — APPROVED** [review]
LGTM!

**Pull request merged**
