### PR TITLE
[EN] add Ingress

### LINKED ISSUE #422: [English]: Ingress
### Details (optional)

I'm happy to work on this content.

### PR DESCRIPTION
**Pull request by aakankshabhende**
### Describe your changes
Added ingress definition to glossary

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #422 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by CathPag** [comment]
Thanks for your contribution, @aakankshabhende. I've added this to our [review process board.](https://github.com/cncf/glossary/projects/10) As you can see we have a little bit of a backlog, but you can follow progress on it.

**Review by iamNoah1 — CHANGES_REQUESTED** [review]
@aakankshabhende Thank you for the contribution. It contains some valuable information, but unfortunately also some misleading and not precise enough information as well. Please understand that being the official CNCF Cloud Native Glossary we aim for very high quality. Please don't feel discouraged by the feedback provided in the PR. These are only suggestions and opinions. Happy to discuss this.

**Comment by aakankshabhende** [comment]
Yes, I will push the commits for required changes soon.

**Comment by aakankshabhende** [comment]
Making a new PR so closing this.

**Pull request closed without merging**
