### PR TITLE
[zh] Localize contributor-ladder

### PR DESCRIPTION
**Pull request by Jacob953**
Follow: #844 
**Done**
- [x] Localize contributor-ladder/_index.md to dev-zh
- [x] remove topnav icons
- [x] update links those unlocalized & correct typos following #869

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @Jacob953 

This PR includes other commits from other authors.
I think the feature branch (Jacob953:dev-zh) needs to be rebased with the latest (upstream) dev-zh

**Comment by Jacob953** [comment]
Hi, @jihoon-seo PTAL!
I've updated the links following #869, and sorry for the increase in your workload due to my poor consideration.

**Comment by seokho-son** [comment]
Hi @Jacob953 

This PR looks good to me, 
but I think at least one zh approver needs to review the localized content (content/zh-cn/contributor-ladder/_index.md)
Please invite reviewers :)

**Review by hanyuancheung — APPROVED** [review]
this PR looks good to me ditto!
Thank you @Jacob953 

cc @seokho-son

**Review by Rocksnake — APPROVED** [review]
This PR looks good to me. Thanks.

**Pull request merged**
