### PR TITLE
chore: Add feedback templating

### PR DESCRIPTION
**Pull request by iamNoah1**

### CODE REVIEW

**Comment by jihoon-seo** [comment]
It would be great if at least one of `de` approvers approves for the `de` strings. 😊

@DaveVentura @Petria3s Could you please take a look and approve? 😊

**Review by Petria3s — APPROVED** [review]

**Review by Petria3s — APPROVED** [review]

**Comment by iamNoah1** [comment]
@jihoon-seo done, could you approve please ;)

**Review by jihoon-seo — APPROVED** [review]
LGTM!

**Review by seokho-son — APPROVED** [review]
lgtm

**Pull request merged**
