### PR TITLE
devRel : Added new term in glossary

### LINKED ISSUE #2427: [New term] `DevRel`
#### What this term is about? (briefly)
- DevRel also known as Developer Relations or Developer Advocacy, is a role that exists in developer companies that target the developers' markets. DevRel helps to educate developers and get people into the community to contribute. There are multiple DevRel types exist that help to scale communities
#### Why this term needs to be added? (briefly) 
1. there should be page about DevRel engineer what they actually do.
2. they are developer, or community builder much to be know about this.
3.  I want this this term to be added like Devops in side drawer we can search with tag.
4. learn new about this role in community. 
- 

### 2. Checklist

- [X] The suggested term fits the [cloud native definition](https://github.com/cncf/toc/blob/main/DEFINITION.md) or is essential to understanding cloud native terms. (We hope to avoid adding general or broad terminologies)
- [X] There is no existing issue yet. [(shift+click to check existing issues)](https://github.com/cncf/glossary/issues?q=label%3A%22new+term%22)
- [X] The term has not already been declined in the past. [(shift+click to check)](https://github.com/cncf/glossary/issues?q=is%3Aissue+is%3Aclosed+label%3A%22triage%2Fnot+accepted%22)
- [X] The term does not already exist in the [glossary](https://glossary.cncf.io).
- [X] I understand that maintainers will assess if the term should be part of the Glossary. (Please be patient)
- [x] I want to work on this term and confirm that I meet the criteria as outlined in "[who can contribute](https://glossary.cncf.io/contribute/#who-can-contribute)". (If not checked, maintainers will assign another volunteer)

### (Note)

Maintainers will assign a label after assessment procedure. 
(from `triage/awaiting` to `triage/accepted` or `triage/not accepted`)

A contributor can be assigned to this issue after the issue get the `triage/accepted` label.
The assignee needs to check [Style Guide](https://glossary.cncf.io/style-guide/).

### PR DESCRIPTION
**Pull request by Madhurchandran**
### Describe your changes
###I actually create issue there is no term about devRel
##Why this term needs to be added? 
1. there should be page about DevRel engineer what they actually do.
2. they are developer, or community builder much to be know about this.
3. I want this this term to be added like Devops in side drawer we can search with tag.
 learn new about this role in community.

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
- But I take help from chatGPT so my english not so good
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Madhurchandran** [comment]
@caniszczyk review my pull request

**Comment by Madhurchandran** [comment]
signed-off-by: MadhurChandran madhurchandran2003@gmail.com

**Comment by nate-double-u** [comment]
> @caniszczyk review my pull request

Hi @Madhurchandran,

Thank you for your contribution and for opening this PR. I appreciate your enthusiasm in wanting to get it reviewed. Currently, our review queue is quite full but you can track the progress [on our review board](https://github.com/orgs/cncf/projects/26).

I wanted to mention that while I understand you're keen to move forward, it's always good to maintain a courteous tone when requesting reviews. It's possible that the way this request for a review was phrased could come off as a bit direct, though I understand that might not have been your intention.

Before we can proceed with the review, there are some checks that need to be passed. One of them is the DCO check. You can find instructions on how to rectify this in the [DCO section of the workflow above](https://github.com/cncf/glossary/pull/2464/checks?check_run_id=17359835746).

**Comment by nate-double-u** [comment]
@Madhurchandran, thanks for your interest and effort in contributing to our project, especially if this is one of your first ventures into open source. Welcome! I want to recommend this article: “[Do you want to start contributing to open source and need help figuring out where to begin?](https://contribute.cncf.io/contributors/getting-started/)” which provides a thorough guide on diving into open source projects, particularly in the cloud native realm.

In the CNCF Glossary, we have [a process for proposing and accepting new terms](https://glossary.cncf.io/contribute/#propose-new-terms), which starts with raising an issue which then needs to be accepted by the editorial team. I see that you have opened [an issue for `devRel` already](https://github.com/cncf/glossary/issues/2427); I’ll make sure that it is brought up with the team as soon as possible for triage.

Since devRel hasn’t been [triaged as a new term yet](https://github.com/orgs/cncf/projects/26/views/5), I would recommend holding off on any further work on this PR until the issue has been triaged and approved. If the term does get accepted, we can revisit the PR and give more guidance on how to align it with [our publication format](https://glossary.cncf.io/style-guide/#definition-template).

For now, I’m going to close this PR. Please feel free to reopen it again if `devRel` is accepted as a new term.

**Comment by Madhurchandran** [comment]
@nate-double-u how can I verify the DCO section of overflow, i don't understand how to do it can you explain it

**Pull request closed without merging**
