### PR TITLE
Definition for mTLS (mutual Transport Layer Security)

### PR DESCRIPTION
**Pull request by Alt-Shivam**
New PR for Definition of mTLS (mutual Transport Layer Security)
Old PR #271

### CODE REVIEW

**Comment by jihoon-seo** [comment]
[Spellcheck CI fails](https://github.com/cncf/glossary/runs/4876344705?check_suite_focus=true#step:4:11).

(Currently, [`rojopolis/spellcheck-github-actions` GitHub Action](https://github.com/rojopolis/spellcheck-github-actions) is used for checking spells.)

Adding `mtls` to [`wordlist.txt`](https://github.com/cncf/glossary/blob/main/wordlist.txt) will solve the problem! 😊

**Comment by Alt-Shivam** [comment]
Thanks @jihoon-seo ,

**Comment by jihoon-seo** [comment]
[Spellcheck CI fails again](https://github.com/cncf/glossary/runs/4878957466?check_suite_focus=true#step:4:11).

Adding `tls` and `iot` to [`wordlist.txt`](https://github.com/cncf/glossary/blob/main/wordlist.txt) will solve the problem! 😊

Plus, @Alt-Shivam Could you squash your commits (including the future ones) into single commit and then force-push? 😊

**Comment by Alt-Shivam** [comment]
Yeah Sure.

**Review by CathPag — APPROVED** [review]
Looks great, thank you!!

**Review by seokho-son — APPROVED** [review]
LGTM :) 
Thanks!

**Pull request merged**
