### PR TITLE
Update dev-ko branch with main branch

### PR DESCRIPTION
**Pull request by yunkon-kim**
This PR will update `dev-ko` branch with `main` branch.

I rebased `dev-ko` with `main` and handled conflicts.

### CODE REVIEW

**Review by seokho-son — APPROVED** [review]
LGTM

**Comment by seokho-son** [comment]
Preferred merge method: `Create a merge commit`

**Comment by seokho-son** [comment]
PTAL @jihoon-seo

**Review by jihoon-seo — APPROVED** [review]
LGTM too!

**Pull request merged**
