### PR TITLE
distributed-apps.md localized to Hindi

### PR DESCRIPTION
**Pull request by NitishKumar06**
Fix: #1315

### CODE REVIEW

**Review by Garima-Negi — APPROVED** [review]
Looks good overall.
Please fix the sentence alignment and spacing for paragraph. The sentences must be continuous like in original `en` version

**Review by Garima-Negi — APPROVED** [review]
LGTM!

**Comment by seokho-son** [comment]
Hi, please let me know, when this PR has additional approval from a dev-hi approver (waiting for 2 approvals).
I will merge this PR to bypass the failed workflow. (it is a temporal situation)

**Comment by seokho-son** [comment]
Hi @NitishKumar06

I am waiting for 2 approvals (from Hindi approvers). 
I cannot review Hindi contents. I will merge this PR as a maintainer after the PR achieve the requirement.
image

**Pull request merged**
