### PR TITLE
added Site Reliability Engineering

### PR DESCRIPTION
**Pull request by Nawaz027**
added the term Site Reliability Engineering. Any suggestions and improvements are highly appreciated. @CathPag please have a look.

### CODE REVIEW

**Comment by Nawaz027** [comment]
sure, and thanks for providing the resources @JasonMorgan

**Comment by JasonMorgan** [comment]
@Nawaz027 are you still working on this? Happy to reassign if you'd like to try something else.

**Comment by Nawaz027** [comment]
Hey @JasonMorgan, sorry for the delay. I will do the changes and deliver by tomorrow.

**Comment by Nawaz027** [comment]
Hey @JasonMorgan, I did the change as suggested. Can you please go through it and share the feedback in case of any need for improvement.
Thanks!

**Comment by CathPag** [comment]
Thanks for the updates, @Nawaz027 — this is a great definition! Below is my suggestion and these are my comments for the updates:

- Ops part was missing (SRE = ops + software engineering)
- The "how software engineering applies to infrastructure and ops" needed a little more context. It took me a while to understand what you meant, so I expanded a little
- SLA and SLO are SRE tools. If we mention them, it should be in the 3rd part (how it helps) but it also feels too specific for a glossary definition, so I'd just drop that. 
- The "problem it addresses" should focus on the problem only, so I removed any SRE mention.
- Not to confuse the reader, I spelled Site Reliability Engineers out when referring to the engineers and kept SRE for the approach (engineering) 
- I made some edits while keeping the essence 

Jason may have some revisions to my suggestion as well. 

****
## What it is
Site Reliability Engineering or SRE is a discipline that combines operations and software engineering. The latter is applied to infrastructure and operations problems, specifically. Meaning, instead of building product features, Site Reliability Engineers build systems to run applications. There are similarities with DevOps, but while DevOps focuses on getting code to production, SRE ensures that code running in production works properly.

## Problem it addresses
Ensuring applications run reliably requires multiple capabilities, from performance monitoring, alerting, debugging to troubleshooting. Without these, system operators can only react to problems vs. proactively working towards avoiding them — downtime only becomes a matter of time. 

## How it helps
An SRE approach minimizes the cost, time, and effort of the software development process by continuously improving the underlying system. The system continuously measures and monitors the infrastructure and application components. When something goes wrong, the system points Site Reliability Engineers to when, where, and how to fix it. This approach helps create highly scalable and reliable software systems by automating operational tasks.

**Comment by Nawaz027** [comment]
thanks @CathPag for the review and making the definition more understandable and clear. @JasonMorgan can I implement the above suggestions or do you have any revisions?

**Comment by JasonMorgan** [comment]
I like @CathPag's changes a lot. If you don't mind putting it in your own words I'm happy to review and approve the final version.

**Comment by Nawaz027** [comment]
Done. @JasonMorgan Please have a look.

**Review by CathPag — APPROVED** [review]
LGTM, thanks for the contribution! 🎉

**Review by JasonMorgan — APPROVED** [review]
LGTM, can you update the status to "Completed"? Great work with this!

**Comment by JasonMorgan** [comment]
@Nawaz027 you're almost there! Can you add SRE to the wordlist.txt? After that we can merge it.

**Comment by Nawaz027** [comment]
done @JasonMorgan . Please have a look

**Review by JasonMorgan — APPROVED** [review]

**Pull request merged**
