### PR TITLE
Create kubernetes.md

### LINKED ISSUE #2458: [hi] Localize Kubernetes for Hindi
Localize Kubernetes in the glossary for Hindi

https://glossary.cncf.io/kubernetes/

### PR DESCRIPTION
**Pull request by ARYANis0001**
### Describe your changes
Localize Kubernetes for Hindi

### Related issue number or link (ex: `resolves #issue-number`)
resolves #2458 
### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by ARYANis0001 — COMMENTED** [review]
Updated

**Review by aj11anuj — COMMENTED** [review]
Thank you for your willingness to help us in localizing effort. But i want to let you know that this is a duplicate PR, we already have #1615. So, we cannot accept this one. Make sure there is no open Issue/PR for the content that you want to localize, otherwise your efforts won't be worth it. But don't get disheartened as you can help us in localizing other terms, for which a PR is not raised yet :)

**Comment by aj11anuj** [comment]
Closing it as it's a duplicate PR

**Comment by ARYANis0001** [comment]
> Closing it as it's a duplicate PR

Hey Anuj can you help me how to get to know is there any duplicate PR exit of issue

**Comment by aj11anuj** [comment]
Its so simple @ARYANis0001, just search "the title of content you want to localize" in issues tab by removing some cmds like (is:issue) and adding some cmds like (label:lang/hi) and you will be able to see it like below.
Screenshot (840)

**Pull request closed without merging**
