### PR TITLE
[tr] new contributors are added to _index.md page

### PR DESCRIPTION
**Pull request by 0ZeKa0**
### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by aliok — APPROVED** [review]
Thanks for adding everyone's name!

**Review by eminalemdar — APPROVED** [review]

**Comment by seokho-son** [comment]
@aliok Please feel free to open a new PR for `dev-tr -> main` to apply the ack names in this PR. :)

**Comment by aliok** [comment]
@0ZeKa0 

Now that `dev-tr` branch is merged to `main`, can you rebase your commit onto `main` and create this PR against `main`? Or start from scratch ;)

**Comment by 0ZeKa0** [comment]
Does changes work as expected @aliok ?

**Review by rwxdash — APPROVED** [review]

**Comment by aliok** [comment]
I might have misdirected you folks. Let's see the answer for this comment: https://github.com/cncf/glossary/pull/2939#issuecomment-1972774029

**Comment by aliok** [comment]
@0ZeKa0  

Sorry, I was wrong earlier. I thought we can now work against the `main` branch, but the Glossary development workflow requires us to still work against the `dev-tr` branch.

See https://cloud-native.slack.com/archives/C02N2RGFXDF/p1709745926614219

Can you change this PR to target `dev-tr` again? Sorry for the inconvenience.

**Comment by 0ZeKa0** [comment]
done

**Comment by aliok** [comment]
@0ZeKa0 we're almost there :) Can you sign off your commits and push them again please?

**Pull request closed without merging**
