### PR TITLE
Update `dev-ko` branch with the main branch

### PR DESCRIPTION
**Pull request by seokho-son**
### Describe your changes
This PR updates `dev-ko` branch to include the latest changes in the main branch.

### Related issue number or link (ex: `resolves #issue-number`)
- based on #1681

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @yunkon-kim 
I think it is time to check the [Check outdated terms / Check outdated terms (pull_request)](https://github.com/cncf/glossary/actions/runs/4074392100/jobs/7019483971) works as intended. (since it is failing)

**Comment by Petrie** [comment]
> Hi @yunkon-kim I think it is time to check the [Check outdated terms / Check outdated terms (pull_request)](https://github.com/cncf/glossary/actions/runs/4074392100/jobs/7019483971) works as intended. (since it is failing)

Same error at https://github.com/cncf/glossary/pull/1712 @yunkon-kim

**Comment by yunkon-kim** [comment]
Sorry for the inconvenience by "check outdated terms/check outdated terms (pull_request)" issue.

I will handle the issue apart from this PR,

**Review by yunkon-kim — APPROVED** [review]

**Comment by seokho-son** [comment]
Let me close this PR and request it to other Korean contributors :)

**Pull request closed without merging**
