### PR TITLE
Rebase dev-ja from main branch

### PR DESCRIPTION
**Pull request by naonishijima**
### Describe your changes

Rebase dev-ja from main branch and manual fix a conflict.

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by naonishijima** [comment]
Maybe config.toml is conflict a file but I can't find a conflict place in Files changed. What should I do?

**Comment by kaitoii11** [comment]
> Maybe config.toml is conflict a file but I can't find a conflict place in Files changed. What should I do?

Looking at the file locally, we need to resolve the below. And maybe we need to fix the weight as well?

```
@@@ -140,12 -141,21 +141,30 @@@ weight = 1
  [languages.ur.params]
  description = "CNCF کلاؤڈ کی مقامی لغت کا مقصد کلاؤڈ مقامی ایپلی کیشنز کے بارے میں بات کرتے وقت استعمال ہونے والی عام اصطلاحات کے حوالے کے طور پر استعمال کرنا ہے۔"

++<<<<<<< HEAD
 +[languages.ja]
 +title = "クラウドネイティブ用語集"
 +description = "CNCF クラウドネイティブ用語集プロジェクトは、クラウドネイティブアプリケーションについて話すときに使われる一般的な用語のリファレンスとして使用することを目的としています。"
 +languageName ="日本語 (Japanese)"
 +contentDir = "content/ja"
 +weight = 11
++=======
+ [languages.fr]
+ title = "Glossaire Cloud Native"
+ languageName ="Français (French)"
+ contentDir = "content/fr"
+ weight = 11
+ [languages.fr.params]
+ description = "Le projet de Glossaire CNCF Cloud Native a pour objectif de référencer les termes courants utilisés dans les différentes applications Cloud Natives."
+
+ [languages.zh-tw]
+ title = "Cloud Native(雲端原生) Glossary"
+ languageName ="繁體中文 (Traditional Chinese)"
+ contentDir = "content/zh-tw"
+ weight = 12
+ [languages.zh-tw.params]
+ description = "CNCF 雲端原生 Glossary 專案旨在用作討論雲端原生應用程式時常用術語的參考"
++>>>>>>> main
```

**Comment by naonishijima** [comment]
@kaitoii11 Thank you for advice!
I was trying to fix a conflict following the "use the command line" instruction. however I got the following error when I pushed. Perhaps something is wrong.

```
# git push -u origin main
Enumerating objects: 13, done.
Counting objects: 100% (13/13), done.
Delta compression using up to 8 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 819 bytes | 819.00 KiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: Waiting on code owner review from caniszczyk, iamNoah1, inductor, jihoon-seo, kaitoii11, nate-double-u, seokho-so
n, and/or yuichi-nakamura. You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-
branches/ for more information.
To https://github.com/cncf/glossary.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cncf/glossary.git'
```

**Comment by kaitoii11** [comment]
I don't think you can push to main branch directly. You might want to fix changes on dev-ja branch.

**Comment by seokho-son** [comment]
Hi @naonishijima @kaitoii11 
To help the Ja team, I've opened a PR that hopefully resolves the conflict here.

https://github.com/cncf/glossary/pull/2704

**Comment by kaitoii11** [comment]
Still having a merge conflict, unfortunately.

**Comment by naonishijima** [comment]
Do we need to create a new PR?

**Comment by seokho-son** [comment]
Let's close this PR since this PR cannot resolve merge conflict.
We can use https://github.com/cncf/glossary/pull/2738 :)

**Pull request closed without merging**
