### PR TITLE
add Baris as german loc approver

### PR DESCRIPTION
**Pull request by iamNoah1**
Signed-off-by: Noah Ispas (iamNoah1) <noahispas@gmail.com>

### Describe your changes

Add @bcubk as an approver for german content. 

**Important**
All candidates need to leave a comment that you understood overall policy.
The l10n team approvers need to use your permission appropriately.
The approvers of l10n team will have a push permission to this repository.
It is to make l10n approvers manage (merge) PRs for l10n contributions in your development branch.
Merging a PR to the main branch by l10n approvers is restricted.
Even if they are possible to review a PR to the main branch and give an approval to the PR, they should not approve the PR.
So, please do not approve if a PR is not related with your localization.
After this PR merged, the approvers will get an github invitation for collaborate from settings[bot] of cncf/glossary. You need to accept.

### CODE REVIEW

**Review by jihoon-seo — APPROVED** [review]

**Review by bcubk — APPROVED** [review]

**Comment by bcubk** [comment]
@iamNoah1, it's probably a silly question, but how do I have to acknowledge the section?

**Comment by seokho-son** [comment]
Hi @iamNoah1 
I opened another PR to include @bcubk to approver list.

PTAL: https://github.com/cncf/glossary/pull/1464
(I think this PR can be closed)

**Comment by seokho-son** [comment]
Hi @bcubk ~! 
Welcome to Glossary ! :)
Please check https://github.com/cncf/glossary/pull/1464 PR. 
You can just read description in the PR carefully and leave a message in #1464

**Comment by iamNoah1** [comment]
Yes, let's close it.

**Pull request closed without merging**
