### PR TITLE
[FR] Fix previous merge

### PR DESCRIPTION
**Pull request by sestegra**
### Describe your changes

Fix the duplicated `ur` configuration block in `config.toml` and add updates from #2238 

### Related issue number or link (ex: `resolves #issue-number`)

N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by Krast76 — APPROVED** [review]

**Comment by seokho-son** [comment]
Hi @sestegra 
I have a suggestion for you. When you are applying content from the main branch into a dev branch, you might find it useful to use this link: https://github.com/cncf/glossary/compare/dev-fr...main that uses original commits. It could make the process easier. Thank you.

**Comment by sestegra** [comment]
Hi @seokho-son;
I'll follow your suggestion for the next time.
I resolved a merge conflict in this PR that was preventing the preview from being generated: see https://github.com/cncf/glossary/pull/2263#issuecomment-1656137832

Can you take a look at this pull request that addresses the issue with preview generation on the dev-fr branch?

**Review by jihoon-seo — APPROVED** [review]
I hope that after merging this PR, the Netlify build errors in these PRs get resolved:
- #2254
- #2258
- #2261
- #2263
- #2272

**Comment by jihoon-seo** [comment]
@sestegra Thank you for your efforts.
Now, could you try rebasing one of those PRs, so that we can see whether the Netlify build error gets resolved?

**Comment by sestegra** [comment]
@jihoon-seo Thank you, Netlify builds are working now.

**Pull request merged**
