### PR TITLE
Settings and initial contents for Arabic localization

### PR DESCRIPTION
**Pull request by same7ammar**
This PR is to initiate Arabic localization based on Issue to https://github.com/cncf/glossary/issues/326

https://github.com/cncf/glossary/blob/main/LOCALIZATION.md guide

**1. [languages.ar] section in config.toml
2. content/ar/ directory
3.  i18n/ar.toml
4.  Some translated documents**

- [ ] Main page:  -> content/ar/_index.md
- [ ] Terms:
               "Cloud Native Technology": content/ar/cloud_native_tech.md
- [ ] Others : 
 How to contribute:  content/ar/contribute/_index.md
Style guide: content/ar/style-guide/_index.md

image

image

image

### CODE REVIEW

**Comment by seokho-son** [comment]
This PR is a cleaner version of PR #406 (commits)

**Comment by seokho-son** [comment]
We are going to check following tasks in this PR. (target branch is dev-ar)

- [ ] 3-1. Adding a new language setting to site configuration https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#3-1-adding-a-new-language-setting-to-site-configuration
- [ ] 3-2. Adding a file for site strings https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#3-2-adding-a-file-for-site-strings
- [ ] 3-3. Adding a new localization directory https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#3-3-adding-a-new-localization-directory
- [ ] 3-4. Minimum required content https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#3-4-minimum-required-content
- [ ] 3-5. Check configuration works https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#3-5-check-configuration-works-and-open-a-pr

**Review by seokho-son — APPROVED** [review]
Great job @same7ammar !
LGTM :)

**Comment by same7ammar** [comment]
> Great job @same7ammar ! LGTM :)

  Thank you so much for your support :)

**Review by CathPag — APPROVED** [review]
Looks great!

**Pull request merged**
