### PR TITLE
[zh] Update links to point localized pages

### PR DESCRIPTION
**Pull request by jihoon-seo**
- Update links to the localized version if exists.
- Replace absolute links (`https://glossary.cncf.io/some_URI`) with relative ones.
  (Remove hardcoded site domain name)
- Replace a link to 'http' with one to 'https'.
- Fix some broken links.

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Dear Chinese contributors,
if you use full-width (em-size) parenthesis characters (`（`, `）`) when making Markdown hyperlinks,
that hyperlinks would be broken:

[Markdown code]
image

[Netlify preview]
image

So, please use half-width parenthesis characters (`(`, `)`) when making Markdown hyperlinks!

The 2nd commit (da34813) of this PR is to fix this issue.

**Comment by Rocksnake** [comment]
> Dear Chinese contributors, if you use full-width (em-size) parenthesis characters (`（`, `）`) when making Markdown hyperlinks, that hyperlinks would be broken:
> 
> [Markdown code] image
> 
> [Netlify preview] image
> 
> So, please use half-width parenthesis characters (`(`, `)`) to make Markdown hyperlinks!
> 
> The 2nd commit ([da34813](https://github.com/cncf/glossary/commit/da34813cc92617acb9cce23f4ae9778649048250)) of this PR is to fix this issue.

Geat thanks, we will pay attention to these specifications later.

**Review by Rocksnake — APPROVED** [review]
lgtm

**Review by Jacob953 — APPROVED** [review]
Thx! LGTM!

**Pull request merged**
