### PR TITLE
update application-programming-interface.md

### PR DESCRIPTION
**Pull request by withgaurav**
Signed-off-by: Gaurav Shukla <gaurav.shukla.gs48@gmail.com>

### Describe your changes
I have read `application-programming-interface.md` this is very beautifully written. But for the people's concern I tried to make it more readable and understandable because there are many peoples who only speak `Bangla`. So I have tried to contribute. I will wait for your feedback.

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by iamNoah1** [comment]
Thanks for the contribution @withgaurav. Have you made contact with the respective localization team on Slack?

**Comment by withgaurav** [comment]
Thankyou for your response @iamNoah1. I didn't got any link of Slack to join.

**Comment by iamNoah1** [comment]
@withgaurav then please make sure to read the [contribution guide](https://glossary.cncf.io/contribute/)

**Comment by withgaurav** [comment]
@iamNoah1 Contributing guide helped me a lot. Thankyou so much @iamNoah1. Looking forward to contribute more in this organization

**Comment by mitul3737** [comment]
@withgaurav you can contact the Bengali localization team on #glossary-localization-bengali

**Review by mitul3737 — APPROVED** [review]
LGTM

**Review by Imtiaz1234 — APPROVED** [review]
LGTM

**Comment by Imtiaz1234** [comment]
Hey @withgaurav  , kindly create a PR to merge your file to `cncf:dev-bn` branch. You did create this PR for `cncf-main` branch which is prohibited

**Pull request closed without merging**
