### PR TITLE
[ko] Modify architecture tag to localized terms

### PR DESCRIPTION
**Pull request by hongju-jeong**
Relevant with: https://github.com/cncf/glossary/discussions/1116#discussioncomment-3330107

### CODE REVIEW

**Comment by seokho-son** [comment]
@hongju-jeong 
Thank you for this enhancement. :)

By the way, `tags` in CN Grossary (upstream) is WIP and the current title for the tags can be changed in future. 
(So, l10n teams do not need to give too much efforts on localizing `tags`)

/cc @yunkon-kim @jihoon-seo

**Review by seokho-son — APPROVED** [review]
LGTM ;)

**Comment by yunkon-kim** [comment]
@seokho-son thanks for your advice about `tags`.

I understand the `upstream` status/intention. When reviewing Korean contents, I will review 'tags' in terms of alignment.

**Review by yunkon-kim — APPROVED** [review]
LGTM ^^

**Pull request merged**
