### PR TITLE
Updated monolithic apps to new format

### PR DESCRIPTION
**Pull request by Anubhavjoshi040**
Monolithic application >> update to new format  #143

### CODE REVIEW

**Comment by Anubhavjoshi040** [comment]
@CathPag Didn't find anything specific to update other than the format, the definition seems complete so I changed the status to completed. Let me know if any changes are required.

**Comment by CathPag** [comment]
Thanks! We are on a very tight schedule and will review this in the week of Oct 6.

**Review by JasonMorgan — APPROVED** [review]

**Comment by JasonMorgan** [comment]
@Anubhavjoshi040 unfortunately the directory structure changed while this was being reviewed. Can you either resolve the conflict or open a new PR with the appropriate file being changed? THis file moved from `definitions/` to `content/en`.

**Review by CathPag — COMMENTED** [review]
Great definition, just made a few edits.  I think Jason requested a change before approving fully

**Comment by Anubhavjoshi040** [comment]
@CathPag I'm not sure how I can resolve the conflict. The file has been moved to `content/en` and this branch is 11 commits behind main. 😐

**Comment by CathPag** [comment]
In that case, please create a new PR and close this one

**Comment by JasonMorgan** [comment]
OBE

**Pull request closed without merging**
