### PR TITLE
Adding update discussion link to guide

### PR DESCRIPTION
**Pull request by CathPag**
Signed-off-by: Catherine Paganini <74001907+CathPag@users.noreply.github.com>

### CODE REVIEW

**Review by iamNoah1 — COMMENTED** [review]
I like the link to the discussion, but I would rather put it to the bottom, because the last section already talks about the english terms vs localized terms.

**Comment by CathPag** [comment]
Updated @iamNoah1. Let me know what you think

**Review by iamNoah1 — APPROVED** [review]
lgtm :)

**Review by seokho-son — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
