### PR TITLE
Rename portuguese content dir from pt to pt-br

### PR DESCRIPTION
**Pull request by edsoncelio**
This PR is just to rename the content dir to the Portuguese localization team from `content/pt` to `content/pt-br` and fix the codeowners file to get give the permissions to the right folder

After that, I'll open a PR to update the dev branch (`dev-pt`)

### CODE REVIEW

**Comment by edsoncelio** [comment]
Just for information, @seokho-son this will fix a problem that we are having with the assignment to the Portuguese reviewers, I totally forgot about this folder name change :/

**Review by jessicalins — APPROVED** [review]
good catch! :tada:

**Review by brunoguidone — APPROVED** [review]
Ok !

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Pull request merged**
