### PR TITLE
[bn] Update dev-bn branch with main

### PR DESCRIPTION
**Pull request by nate-double-u**
I've removed the commit that #3290 made, and have merged `main` into `dev-bn` to bring this up to speed with where #3290 was.

Follow up to https://github.com/cncf/glossary/pull/3290

related issue: https://github.com/cncf/glossary/issues/410

### CODE REVIEW

**Comment by nate-double-u** [comment]
I'm concerned I've not done this quite right because of commit 16582127d235eb12c0f0df1fc079bd0476264204.

**Comment by asem-hamid** [comment]
> I'm concerned I've not done this quite right because of commit [1658212](https://github.com/cncf/glossary/commit/16582127d235eb12c0f0df1fc079bd0476264204).

Let's do it now. ig it will work enough for now . 

Thank you @nate-double-u helping me in this situation .

LGTM

**Comment by asem-hamid** [comment]
LGTM

**Review by seokho-son — APPROVED** [review]
lgtm! thanks

Since this PR does not need to review its content, let me merge as one of the maintainers.

**Comment by asem-hamid** [comment]
Thank you, @nate-double-u. The message has been removed now.

image

@seokho-son  thanks for approving

**Pull request merged**
