### PR TITLE
[ru] Localize digital-certificate.md

### PR DESCRIPTION
**Pull request by vickylikh**
### Checklist before opening this PR (put `x` in the checkboxes)
- [ x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by shurup** [comment]
Currently, this PR contains changes affecting the original (English) file (`content/en/devops.md`) due to including 3rd-party commits from another branch (`main` instead of `dev-ru`). We should remove them to proceed with working on a Russian localisation only. See the [Localization team guidelines](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#localization-team-guidelines) (especially, item 2 in this list) for more information.

**Review by tym83 — COMMENTED** [review]
I think, that more preferable translation for entity is "сущность", not object. It is IMHO, but it seems more correct. But maybe I'm just choking:)

**Comment by vickylikh** [comment]
> Currently, this PR contains changes affecting the original (English) file (`content/en/devops.md`) due to including 3rd-party commits from another branch (`main` instead of `dev-ru`). We should remove them to proceed with working on a Russian localisation only. See the [Localization team guidelines](https://github.com/cncf/glossary/blob/main/LOCALIZATION.md#localization-team-guidelines) (especially, item 2 in this list) for more information.

@shurup The issue here seems to be that my fork was created later than the `dev-ru` branch was last synchronized with the `main` branch. As a result my copy of the `main` branch includes some changes the `dev-ru` branch doesn't. So GitHub seems to try updating the `dev-ru` branch with my PR including not only my commits but also the newer commits from the `main` branch. Any suggestions how to deal with this? I don't see any way to remove the 3rd party commits.

**Comment by shurup** [comment]
@vickylikh you need to rebase your branch against `dev-ru`. The first answer [here](https://stackoverflow.com/questions/40009820/git-rebase-one-branch-on-top-of-another-branch) is relevant to the case.

**Comment by vickylikh** [comment]
> @vickylikh you need to rebase your branch against `dev-ru`. The first answer [here](https://stackoverflow.com/questions/40009820/git-rebase-one-branch-on-top-of-another-branch) is relevant to the case.

Thanks. I realized I'd forked the repo the wrong way (the branch `main` only). Will delete the fork and try again. Sorry for the mess.

**Pull request closed without merging**
