### PR TITLE
fixed broken links

### LINKED ISSUE #1547: broken links in _index.md of contribute directory of english language
image

### PR DESCRIPTION
**Pull request by withgaurav**
Signed-off-by: Gaurav Shukla <gaurav.shukla.gs48@gmail.com>

### Describe your changes
I've fixed broken links in _index.md english language 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by CathPag** [comment]
Thanks, @withgaurav. Where did you see broken images? It [looks right on the website](https://glossary.cncf.io/contribute/). The preview won't display the images correclty, but that is normal.

**Comment by withgaurav** [comment]
image
Here in this README file (_index.md) images are not showing. I'm not talking about website.I have seen that images in the glossary repository
Below link will redirect you to that file https://github.com/cncf/glossary/blob/main/content/en/contribute/_index.md

**Comment by seokho-son** [comment]
Hi @withgaurav 

They are not broken links. :) 

This repository is to generate the Cloud native Glossary website https://glossary.cncf.io/ (based on HUGO).
The links are for website and they work in the website. 

Those links does not work in page view of Github repository.

**Comment by withgaurav** [comment]
Okay @seokho-son thankyou I also noticed the same thing right now

**Comment by seokho-son** [comment]
Thanks ~! 
Let me close this PR. :)

**Pull request closed without merging**
