### PR TITLE
Merge `main` into branch `dev-ja`

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Describe your changes

merge upstream/main into upstream/dev-ja

### Background

There are several ways to merge the dev-ja branch into the main branch, but this has become complicated due to a number of PRs being created.

Currently, since main and dev-ja are conflicting, we cannot be merged directly. I think the easiest way to resolve this is to merge the main branch into dev-ja and then merge #2677.

### Related issue number or link (ex: `resolves #issue-number`)

no issue related in this PR

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
I think the easiest way to resolve the issue is to merge this PR instead of a rebase, and then merge #2677.

(And then, I believe we will be able to close #2695 and #2700.)

@seokho-son @jihoon-seo @naonishijima @kaitoii11

What do you think about this approach?

**Review by jihoon-seo — APPROVED** [review]
This looks good to me. Thank you @Okabe-Junya !

**Review by kaitoii11 — APPROVED** [review]

**Comment by Okabe-Junya** [comment]
It appears that there is a failure in the DCO check. Why might this be? How should this be resolved?... Executing the following commands might resolve the issue, but there could be side effects

```bash
git rebase HEAD~250 --signoff
git push --force-with-lease origin merge-main
```

**Comment by naonishijima** [comment]
@Okabe-Junya  You can manually DCO on via Details.

**Comment by Okabe-Junya** [comment]
I think there are several issues with making DCO changes (following the instructions written in the details) in this PR.

1. It seems inappropriate to rewrite DCOs that have already been done by others.
2. Changing the DCO might lead to conflicts again.
3. In other similar PRs, this issue does not appear to be happening.
    a. e.g. #2689, #2625  

Therefore, I am hoping for this CI to pass, but...

**Comment by naonishijima** [comment]
@seokho-son @jihoon-seo Do you have any idea or advice to merge this PR?

**Comment by Okabe-Junya** [comment]
Thank you for your thoughtful response.

This issue seems a bit difficult. I respect the opinions of reviewers and other maintainers(of course, including you). if this PR is not necessary, I'm fine with closing it or creating another PR.

I hope this issue will be resolved successfully.

(It seems that there are not enough reviews from CODEOWNERS to merge this PR. Since @.kaitoii11  is not a CODEOWNER, it appears that there are not enough approvers.)

**Comment by seokho-son** [comment]
There are no objections from the maintainers, so I am going to merge the PR. 
Thanks @Okabe-Junya @naonishijima @kaitoii11 :)

(@Okabe-Junya, regarding the reviews from CODEOWNERS, it's hard to get all approvals for special PRs like this, which do not require a code review. Maintainers use their authority (bypass branch protections) to merge these kinds of PRs.)

**Review by seokho-son — APPROVED** [review]

**Pull request merged**
