### PR TITLE
[ja] Merge dev-ja into main @v4

### PR DESCRIPTION
**Pull request by Okabe-Junya**
### Describe your changes

Merge dev-ja into main to release the Japanese localization v4!!

**Terms to be added**

- #2968 
- #2987 
- #2992 
- #3017 
- #3021 
- #3022 
- #3032 
- #3033
- #3034 
- #3035
- #3042 
- #3043 

**The following modifications/updates are included**

- #2999 
- #3006 
- #3025 
- #3030 
- #3039
- #3040 
- #3045 
- #3049 
- #3050

### Related issue number or link (ex: `resolves #issue-number`)

No issue related to this PR

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by kaitoii11 — APPROVED** [review]
LGTM

**Review by naonishijima — APPROVED** [review]
LGTM

**Review by iamNoah1 — APPROVED** [review]
awesome work folks :) thanks a lot 

lgtm

Only thing I am a bit concerned is the DCO. Please make sure for future commits to have them all pass DCO.

**Comment by seokho-son** [comment]
Thanks!! on be half of the Japanese team, let me approve and merge this PR.

**Review by seokho-son — APPROVED** [review]

**Pull request merged**
