### PR TITLE
Update dev-pt branch with main branch

### PR DESCRIPTION
**Pull request by edsoncelio**
This PR is to update `dev-pt` branch with `main` branch

### CODE REVIEW

**Comment by edsoncelio** [comment]
I'll leave this PR as a draft until I open an issue with all the updates from the `content/en` to the `dev-pt` branch.
cc @brunoguidone @jessicalins

**Comment by edsoncelio** [comment]
Issue created: https://github.com/cncf/glossary/issues/887

**Comment by seokho-son** [comment]
@edsoncelio 

So, this PR is WIP ? :)
PR to merge from main to dev-xx branch dose not require Code (contents) review. (commits into [dev-pt](https://github.com/cncf/glossary/tree/dev-pt) from [main](https://github.com/cncf/glossary))

Let maintainers know when you think this PR is ready to be merged !

**Comment by edsoncelio** [comment]
> @edsoncelio
> 
> So, this PR is WIP ? :) PR to merge from main to dev-xx branch dose not require Code (contents) review. (commits into [dev-pt](https://github.com/cncf/glossary/tree/dev-pt) from [main](https://github.com/cncf/glossary))
> 
> Let maintainers know when you think this PR is ready to be merged!

It's done for merge @seokho-son, I've already created the issue with the updates!

**Review by seokho-son — APPROVED** [review]
lgtm

**Pull request merged**
