### PR TITLE
[bn] Update main branch with dev-bn

### PR DESCRIPTION
**Pull request by sajibAdhi**
### Describe your changes

Update main branch with dev-bn
- removes header `এটা কি (what it is)`
- tags localization
- Content Updates
  - content/bn/_TEMPLATE.md
  - content/bn/auto-scaling.md
  - content/bn/bare-metal-machine.md
  - content/bn/container-orchestration.md
  - content/bn/container.md
  - content/bn/contribute/_index.md
  - content/bn/data-center.md
  - content/bn/debugging.md
  - content/bn/digital-certificate.md
  - content/bn/distributed-apps.md
  - content/bn/distributed-systems.md
  - content/bn/ebpf.md
  - content/bn/gitops.md
  - content/bn/ingress.md
  - content/bn/kubernetes.md
  - content/bn/load-balancer.md
  - content/bn/observability.md
  - content/bn/pod.md
  - content/bn/role-based-access-control.md
  - content/bn/runtime.md
  - content/bn/security-chaos-engineering.md
  - content/bn/serverless.md
  - content/bn/stateful-apps.md
  - content/bn/stateless-apps.md
  - content/bn/style-guide/_index.md
  - content/bn/virtualization.md

### Related issue number or link (ex: `resolves #issue-number`)

Related Issues: #2896
Tracking Issue: #410 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by asem-hamid** [comment]
style guide and some files are remain  to update . can you merge it after that .

**Comment by asem-hamid** [comment]
@sajibAdhi  open this PR . We are ready to merged .

**Review by mitul3737 — APPROVED** [review]

**Review by Imtiaz1234 — APPROVED** [review]

**Comment by asem-hamid** [comment]
@seokho-son Check Please

**Comment by asem-hamid** [comment]
@seokho-son  Thank you for merging our PR

**Pull request merged**
