### PR TITLE
[EN] update chaos engineering

### PR DESCRIPTION
**Pull request by ankitaludbe**
### Describe your changes
Added bullet points to make the doc more readable

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by ankitaludbe** [comment]
diving into the open source with these little changes😇

**Comment by ankitaludbe** [comment]
Hi @nate-double-u, did I do it right?

**Comment by nate-double-u** [comment]
Not quite -- now both commits have different signatures. I think it was more correct with the first one, and I'm not actually sure why it didn't register. So, we'll sort it out with the merge at the end (we'll squash it and make sure the signature is right then).

**Comment by ankitaludbe** [comment]
@nate-double-u Can you please tell me how?

**Comment by nate-double-u** [comment]
> @nate-double-u Can you please tell me how?

honestly, I'm not sure what went wrong. Looking at your first commit, the DCO should have passed.

As per the [DCO instructions provided above](https://github.com/cncf/glossary/pull/2390/checks?check_run_id=16756671773):

> Commit sha: [d0ec620](https://github.com/cncf/glossary/pull/2390/commits/d0ec620b0161374dbb75c8c9b255863ea2cbebfa), Author: Ankita, Committer: GitHub; Expected "Ankita [86849431+ankitaludbe@users.noreply.github.com](mailto:86849431+ankitaludbe@users.noreply.github.com)", but got "Ankita [86849431+ankitaludbe@users.noreply.github.com](mailto:86849431+ankitaludbe@users.noreply.github.com)".

(and please be sure that I didn't close this PR because of the DCO issues)

**Comment by ankitaludbe** [comment]
@nate-double-u, I totally understand it and thank you so much for letting me know. I will try to improve and do more worthwhile contributions.

**Pull request closed without merging**
