### PR TITLE
Updated Kubernetes.md to localize traditional chinese language  

### PR DESCRIPTION
**Pull request by ranjan2829**

### CODE REVIEW

**Comment by johnlinp** [comment]
Hi @ranjan2829,

Thank you for the PR! I see your translation is in Simplified Chinese. However, the issue #2297 is meant to translate the content into Traditional Chinese. Are you willing to modify your PR? Thanks!

**Comment by ranjan2829** [comment]
@johnlinp sure i'll change it to traditional chinese!

**Comment by hwchiu** [comment]
Hi, @ranjan2829 

你的 PR 整個從系統上就是流程錯誤，首先繁體中文化翻譯有自己的 branch 要處理，不是直接推到 main，更不是直接修改英文語系的內容，你這樣會導致整個英文版本的內容都錯誤，請先上 Slack 瞭解每個語系的翻譯流程

再者你的翻譯內容非常的機器化，整個語句與語法都不是繁體中文用法，翻譯不應該是單純的機器翻譯，而是要該母語人士去消化理解並且轉換為該語言的慣用語句

**Comment by hwchiu** [comment]
@ranjan2829 

Both of your "changed" files already have issues opened and assigned for handling. Therefore, the Traditional Chinese translations of these two documents should prioritize those contributors. Please refrain from making any further changes related to the Traditional Chinese translations in this PR. There are several issues with the process, such as directly modifying the original English content.

If you'd like to contribute, please follow the official process by opening an issue. For more details, you can join the Slack channel "glossary-localization-traditional-chinese". Additionally, please note that we do not accept machine-generated translations. Contributions should be made in your native language to ensure smooth and reasonable sentences through proofreading.

**Pull request closed without merging**
