### PR TITLE
[bn] fix typo /bn/zero-trust-architecture.md

### PR DESCRIPTION
**Pull request by Musanna-al-akil**
To align with standard bangla grammar rules and maintain consistency throughout the doc, a space has been added after every comma in this doc file.

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by sajibAdhi — APPROVED** [review]
LGTM

**Comment by asem-hamid** [comment]
Related issue number : #410

LGTM

**Review by asem-hamid — APPROVED** [review]

**Comment by asem-hamid** [comment]
@Musanna-al-akil  Thanks for contributing 

Please change targeted  branch from main to dev-bn

**Comment by asem-hamid** [comment]
@Musanna-al-akil Thanks for contributing

**Pull request merged**
