### PR TITLE
[zh] Update Chinese version in main with dev-zh

### PR DESCRIPTION
**Pull request by Jacob953**
### Describe your changes
Update Chinese version in main with dev-zh

### Related issue number or link (ex: `resolves #issue-number`)
#3145 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by hanyuancheung — APPROVED** [review]
lgtm

**Review by Rocksnake — APPROVED** [review]
LGTM.

**Comment by iamNoah1** [comment]
@Jacob953 I think originally also the other way around was requested. Merging main into dev-zh. Just as friendly reminder.

**Comment by Jacob953** [comment]
> @Jacob953 I think originally also the other way around was requested. Merging main into dev-zh. Just as friendly reminder.

Thx for your kind reminder. It has already been done in #3374, though I might have missed the issue.

**Comment by iamNoah1** [comment]
Nice @Jacob953 yeah missed it. Then I go ahead and close #3145

**Pull request merged**
