### PR TITLE
Update dev-ko branch with main branch

### PR DESCRIPTION
**Pull request by seokho-son**
This PR is to 

update outdated English contents in `dev-ko` branch 
with the latest changes in English contents from `main` branch.
(copy all commits in `main` into `dev-ko`)

### CODE REVIEW

**Review by jihoon-seo — APPROVED** [review]
LGTM!
(CC: @yunkon-kim )

**Comment by seokho-son** [comment]
@JasonMorgan This PR needs approval from a maintainer :)

Please note that, this PR is to update `dev-ko` branch and no impact to `main` branch.

**Comment by seokho-son** [comment]
I'd like to change the way to update dev-ko branch into `rebasing dev-ko based on upstream/main`.
In order to prevent some complex situations by duplicated commits between `main` and `dev-ko` branches.

@jihoon-seo @yunkon-kim 

What do you think so ?

**Comment by seokho-son** [comment]
Let me close this PR. I will reopen a PR with a rebased dev-ko branch

**Pull request closed without merging**
