### PR TITLE
Update CODEOWNERS for Bengali branch

### PR DESCRIPTION
**Pull request by mitul3737**
### Describe your changes
We need to update the code owners for the Bengali Branch

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Comment by seokho-son** [comment]
Hi @mitul3737,

We believe sufficient time has passed for a lazy consensus. We would like to replace @Mouly22 and @ikramulkayes with @Arindam200 and @sajibAdhi.

Maintainers will update `CODEOWNERS` file first (via #2134).

In the meantime, please leave comment here to confirm that each approver candidate (@Arindam200 and @sajibAdhi) understands the policy and information for localization approvers.

- #723

**Comment by sajibAdhi** [comment]
Hello, @seokho-son 
I understood policies and information for localization approvers.

**Comment by Arindam200** [comment]
Hello, @seokho-son! 

I fully understand the policies and information for localization approvers.

Thank you.

**Comment by seokho-son** [comment]
Thanks! let me close this PR and continue settings in other PRs.
- https://github.com/cncf/people/pull/248
- https://github.com/cncf/glossary/pull/2134

By the way, I'd like to clarify that we don't say a `localization approver` is a `maintainer` of cloud native glossary. :)
https://glossary.cncf.io/contributor-ladder/

When introducing oneself, it would be more accurate to mention a `localization approver` or involved in maintaining Bengali localization.  (there is no role name called `localization maintainer` as well - so far).

**Pull request closed without merging**
