### PR TITLE
I18n of feedback section

### PR DESCRIPTION
**Pull request by jihoon-seo**
This PR is related with https://github.com/cncf/glossary/issues/470#issuecomment-1050450210 .

After this PR gets merged, I will open a PR that applies L10n of Feedback section to `dev-ko` branch. 😊

### CODE REVIEW

**Comment by seokho-son** [comment]
@jihoon-seo do we need to add `layouts/partials/feedback.html` ?

**Comment by seokho-son** [comment]
Yeh, I understood :) 

in our docsy theme (https://github.com/cncf/glossary/tree/main/themes)

https://github.com/google/docsy/blob/master/layouts/partials/feedback.html#L19 is hard-coded 

> <button class="btn btn-primary mb-4 feedback--answer feedback--answer-yes">Yes</button>

**Comment by seokho-son** [comment]
@cjyabraham 
"Feedback" section is displayed in English and it is not localizable #470 :)

Do we need to use Feedback footer on documents in https://glossary.cncf.io/ ? (is it useful ?)

**Comment by cjyabraham** [comment]
In the last 3 months 32 people have clicked one of those feedback buttons. 91% of submissions said they found the page "helpful". You can see [the full results broken down by page here](https://analytics.google.com/analytics/web/#/report/content-event-events/a140890431w286641791p251311085/_u.date00=20211123&_u.date01=20220223&explorer-segmentExplorer.segmentId=analytics.eventLabel&_r.drilldown=analytics.eventCategory:Helpful&explorer-table.plotKeys=%5B%5D&explorer-table.rowCount=100) including some pages which received negative feedback.

Looks like there is [an open PR for the docsy theme](https://github.com/google/docsy/issues/175) that would allow translation of the Feedback section. I imagine I could just copy that over to get it in our instance. Sound good?

**Review by iamNoah1 — COMMENTED** [review]
The only feedback I have is to maybe add indentation for the HTML stuff. Also what @cjyabraham said could be verified. The simpler we can make it, the better at least IMHO

**Comment by cjyabraham** [comment]
Actually, looking at the code a bit more closely, it look almost identical to the other PR, just using `T` instead of `i18n` as a function. Not sure what the impact of that is...

**Comment by jihoon-seo** [comment]
@cjyabraham @iamNoah1 @seokho-son Thank you for checking.
According to [this page](https://gohugo.io/functions/i18n/), it seems that we can use both `i18n` and `T` Hugo functions.
> `T` is an alias to `i18n`.

---

And here is the preview of this PR: https://deploy-preview-483--cncfglossary.netlify.app/abstraction/#:~:text=Feedback,No

**Comment by seokho-son** [comment]
I prefer to adopt files from upstream repo (docsy) to avoid maintaining customized files. 

However, since the upstream repo (docsy) is not ready yet, 

Why don't we accept the customized changes in this PR and revert the customized changes if docsy modifies the feedback section by merging the PR https://github.com/google/docsy/pull/179 later.

If yes, I prefer similar variable names with the upstream PR https://github.com/google/docsy/pull/179/files

> [feedback_title]
other = "Feedback"
[feedback_question]
other = "Was this page helpful?"
[feedback_answer_yes]
other = "Yes"
[feedback_answer_no]
other = "No"

I guess @cjyabraham can make final decision :)
I will agree with any decision from @cjyabraham

**Comment by cjyabraham** [comment]
I agree. The [docsy PR](https://github.com/google/docsy/pull/179) seems stale, last edited in 2020, so let's merge this in for now. Looks good 👍

**Comment by jihoon-seo** [comment]
@cjyabraham Thanks, and I reflected @seokho-son's suggestion. 😊

To who merge this PR: Please do "Squash and merge". 😊

**Review by iamNoah1 — APPROVED** [review]
lgtm

**Review by seokho-son — APPROVED** [review]
LGTM :)

**Pull request merged**
