### PR TITLE
add cgroups, namespaces, and orchestrator to wordlist

### PR DESCRIPTION
**Pull request by castrojo**
### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

### CODE REVIEW

**Review by nate-double-u — APPROVED** [review]
LGTM, thanks @castrojo

**Comment by nate-double-u** [comment]
related to #2033

**Comment by jihoon-seo** [comment]
How about we cherry-pick the commits in this PR to #2033, to process this wordlist update in #2033, not in a separate PR? Those 2 jobs (adding 'Runtime' and updating wordlist accordingly) are highly related so it would be reasonable to be in one PR, and by this way the failed workflow (spellcheck) in #2033 will pass. 😊

**Comment by nate-double-u** [comment]
> How about we cherry-pick the commits in this PR to #2033, to process this wordlist update in #2033, not in a separate PR? Those 2 jobs (adding 'Runtime' and updating wordlist accordingly) are highly related so it would be reasonable to be in one PR, and by this way the failed workflow (spellcheck) in #2033 will pass. 😊

I'd also be good with this happening in #2033 -- the words are being added to the spell check list in support of the new definition.

**Comment by jihoon-seo** [comment]
@nate-double-u Thank you for your opinion. I pushed the commit into #2033, so we now can close this PR.
@castrojo Thank you for addressing this PR!

**Comment by iamNoah1** [comment]
> @nate-double-u Thank you for your opinion. I pushed the commit into #2033, so we now can close this PR.
> @castrojo Thank you for addressing this PR!

Thanks @jihoon-seo can you share how you did it? I tried to make changes to the PR without success. Changes on the file in the PR can be made through the suggestion feature, but how can I commit and push something to the branch of the author of the PR?

**Comment by jihoon-seo** [comment]
@iamNoah1 Sure 😊 here are the steps I followed:
1. Make sure that you can push new commits to the branch of the author.
   image
2. On your local dev env, checkout the branch of the author. (I am using [GitHub CLI](https://github.com/cli/cli) for this):
   image
3. Add some commits.
4. Push newly added commits to the branch of the author.
   1. Add the author's fork as a new 'git remote' on your local dev env.
      (e.g., `git remote add akshatcoder-hash git@github.com:akshatcoder-hash/glossary.git`, where the URL can be retrieved from the fork's GitHub UI:)
      image
   2. Actual push
      (e.g., `git push akshatcoder-hash runtime-en`, where `akshatcoder-hash` is the 'git remote' name you added in the previous step, and `runtime-en` is the branch name of the feature branch.)

PTAL!

BTW let me close this PR, because this change is reflected in #2033.

**Pull request closed without merging**
