### PR TITLE
Fix visualization bug in navbar-lang-selector

### PR DESCRIPTION
**Pull request by 92nqb**
It solves #931 

### Evidence

Screenshot 2022-06-08 at 09 49 04

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Hello @92nqb, thank you for your contribution!

For anyone's information:
Currently, there is a open PR (#930) that also fixes #931 by modifying SCSS: see [here](https://github.com/cncf/glossary/pull/930/files#diff-1eea53605e04631cf5b5307d1f27eb125121316a58c492532d937130b2836e8fR329-R332).
(CC: @cjyabraham)

**Comment by cjyabraham** [comment]
This solution might be slightly better than mine so I'm fine with it being merged.

**Review by jihoon-seo — APPROVED** [review]
LGTM! Thanks!

**Comment by seokho-son** [comment]
@92nqb Thank you for the contribution !
(Thanks to @cjyabraham @jihoon-seo for the PR coordination)

/lgtm

**Review by seokho-son — APPROVED** [review]

**Pull request merged**
